// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nutritionssort/nutritionssort_.proto

/*
Package nutritionssort is a generated protocol buffer package.

It is generated from these files:
	nutritionssort/nutritionssort_.proto

It has these top-level messages:
	NutritionsSort
*/
package nutritionssort

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import weightperweightsort "github.com/21stio/go-playground/grpc/schema/weightperweightsort"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NutritionsSort struct {
	Kcal             *weightperweightsort.WeightPerWeightSort `protobuf:"bytes,1,opt,name=kcal" json:"kcal,omitempty"`
	Fat              *weightperweightsort.WeightPerWeightSort `protobuf:"bytes,2,opt,name=fat" json:"fat,omitempty"`
	SaturatedFat     *weightperweightsort.WeightPerWeightSort `protobuf:"bytes,3,opt,name=saturatedFat" json:"saturatedFat,omitempty"`
	Carbohydrates    *weightperweightsort.WeightPerWeightSort `protobuf:"bytes,4,opt,name=carbohydrates" json:"carbohydrates,omitempty"`
	Sugar            *weightperweightsort.WeightPerWeightSort `protobuf:"bytes,5,opt,name=sugar" json:"sugar,omitempty"`
	Roughages        *weightperweightsort.WeightPerWeightSort `protobuf:"bytes,6,opt,name=roughages" json:"roughages,omitempty"`
	Proteins         *weightperweightsort.WeightPerWeightSort `protobuf:"bytes,7,opt,name=proteins" json:"proteins,omitempty"`
	Salt             *weightperweightsort.WeightPerWeightSort `protobuf:"bytes,8,opt,name=salt" json:"salt,omitempty"`
	Thiamin          *weightperweightsort.WeightPerWeightSort `protobuf:"bytes,9,opt,name=thiamin" json:"thiamin,omitempty"`
	Magnesium        *weightperweightsort.WeightPerWeightSort `protobuf:"bytes,10,opt,name=magnesium" json:"magnesium,omitempty"`
	Iron             *weightperweightsort.WeightPerWeightSort `protobuf:"bytes,11,opt,name=iron" json:"iron,omitempty"`
	Hash             *string                                  `protobuf:"bytes,12,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte                                   `json:"-"`
}

func (m *NutritionsSort) Reset()                    { *m = NutritionsSort{} }
func (m *NutritionsSort) String() string            { return proto.CompactTextString(m) }
func (*NutritionsSort) ProtoMessage()               {}
func (*NutritionsSort) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NutritionsSort) GetKcal() *weightperweightsort.WeightPerWeightSort {
	if m != nil {
		return m.Kcal
	}
	return nil
}

func (m *NutritionsSort) GetFat() *weightperweightsort.WeightPerWeightSort {
	if m != nil {
		return m.Fat
	}
	return nil
}

func (m *NutritionsSort) GetSaturatedFat() *weightperweightsort.WeightPerWeightSort {
	if m != nil {
		return m.SaturatedFat
	}
	return nil
}

func (m *NutritionsSort) GetCarbohydrates() *weightperweightsort.WeightPerWeightSort {
	if m != nil {
		return m.Carbohydrates
	}
	return nil
}

func (m *NutritionsSort) GetSugar() *weightperweightsort.WeightPerWeightSort {
	if m != nil {
		return m.Sugar
	}
	return nil
}

func (m *NutritionsSort) GetRoughages() *weightperweightsort.WeightPerWeightSort {
	if m != nil {
		return m.Roughages
	}
	return nil
}

func (m *NutritionsSort) GetProteins() *weightperweightsort.WeightPerWeightSort {
	if m != nil {
		return m.Proteins
	}
	return nil
}

func (m *NutritionsSort) GetSalt() *weightperweightsort.WeightPerWeightSort {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *NutritionsSort) GetThiamin() *weightperweightsort.WeightPerWeightSort {
	if m != nil {
		return m.Thiamin
	}
	return nil
}

func (m *NutritionsSort) GetMagnesium() *weightperweightsort.WeightPerWeightSort {
	if m != nil {
		return m.Magnesium
	}
	return nil
}

func (m *NutritionsSort) GetIron() *weightperweightsort.WeightPerWeightSort {
	if m != nil {
		return m.Iron
	}
	return nil
}

func (m *NutritionsSort) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*NutritionsSort)(nil), "nutritionssort.NutritionsSort")
}

func init() { proto.RegisterFile("nutritionssort/nutritionssort_.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0xd3, 0xbf, 0x6a, 0x23, 0x31,
	0x10, 0x06, 0x70, 0x7c, 0xfe, 0x2f, 0xfb, 0x5c, 0xa8, 0x12, 0x57, 0x99, 0x23, 0x85, 0x9b, 0xec,
	0x12, 0x97, 0xc6, 0xa4, 0x30, 0xc1, 0x55, 0x30, 0xc1, 0x29, 0x02, 0x69, 0xc2, 0x78, 0xad, 0x48,
	0x22, 0x5e, 0x69, 0x19, 0x8d, 0x08, 0x7e, 0x8d, 0x3c, 0x71, 0xd0, 0x3a, 0x71, 0xd8, 0xe0, 0x46,
	0xdd, 0xb7, 0x03, 0xbf, 0x0f, 0x34, 0xc3, 0xb2, 0x2b, 0x1b, 0x08, 0x0d, 0x19, 0x67, 0xbd, 0x77,
	0x48, 0x79, 0xf3, 0xf3, 0x25, 0xab, 0xd0, 0x91, 0xe3, 0x93, 0xe6, 0xf8, 0x5f, 0xf6, 0x2e, 0x8d,
	0xd2, 0x54, 0x49, 0x3c, 0x85, 0x9a, 0x5e, 0x98, 0x7d, 0xf9, 0xff, 0x1f, 0x3d, 0x36, 0xd9, 0x9c,
	0x2b, 0x1e, 0x1d, 0x12, 0x5f, 0xb2, 0xce, 0x5b, 0x01, 0x07, 0xd1, 0x9a, 0xb6, 0x66, 0xa3, 0xf9,
	0xec, 0x52, 0x63, 0xf6, 0x54, 0xc7, 0x07, 0x89, 0xa7, 0x10, 0xdd, 0xb6, 0x56, 0x7c, 0xc1, 0xda,
	0xaf, 0x40, 0xe2, 0x4f, 0x22, 0x8e, 0x88, 0xdf, 0xb3, 0xb1, 0x07, 0x0a, 0x08, 0x24, 0xf7, 0x6b,
	0x20, 0xd1, 0x4e, 0x2c, 0x69, 0x68, 0xbe, 0x61, 0x7f, 0x0b, 0xc0, 0x9d, 0xd3, 0xc7, 0x7d, 0x9c,
	0x79, 0xd1, 0x49, 0xac, 0x6b, 0x72, 0x7e, 0xcb, 0xba, 0x3e, 0x28, 0x40, 0xd1, 0x4d, 0xec, 0x39,
	0x31, 0xbe, 0x66, 0x43, 0x74, 0x41, 0x69, 0x50, 0xd2, 0x8b, 0x5e, 0x62, 0xc7, 0x0f, 0xe5, 0x77,
	0x6c, 0x10, 0x6f, 0x27, 0x8d, 0xf5, 0xa2, 0x9f, 0x58, 0x73, 0x96, 0xf1, 0xca, 0x1e, 0x0e, 0x24,
	0x06, 0xa9, 0x57, 0x8e, 0x8a, 0xaf, 0x58, 0x9f, 0xb4, 0x81, 0xd2, 0x58, 0x31, 0x4c, 0x2c, 0xf8,
	0x86, 0x71, 0x1f, 0x25, 0x28, 0x2b, 0xbd, 0x09, 0xa5, 0x60, 0xa9, 0xfb, 0x38, 0xd3, 0xf8, 0x12,
	0x83, 0xce, 0x8a, 0x51, 0xea, 0x4b, 0xa2, 0xe2, 0x9c, 0x75, 0x34, 0x78, 0x2d, 0xc6, 0xd3, 0xd6,
	0x6c, 0xb8, 0xad, 0xf3, 0x6a, 0xf9, 0xbc, 0x50, 0x86, 0x74, 0xd8, 0x65, 0x85, 0x2b, 0xf3, 0xf9,
	0x8d, 0x27, 0xe3, 0x72, 0xe5, 0xae, 0xab, 0x03, 0x1c, 0x15, 0xba, 0x60, 0xf7, 0xb9, 0xc2, 0xaa,
	0xc8, 0x7d, 0xa1, 0x65, 0x09, 0xbf, 0xfe, 0xcc, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x89,
	0xcf, 0xb1, 0xb9, 0x03, 0x00, 0x00,
}
