// Code generated by protoc-gen-go. DO NOT EDIT.
// source: credentialkindfilter/credentialkindfilter_.proto

/*
Package credentialkindfilter is a generated protocol buffer package.

It is generated from these files:
	credentialkindfilter/credentialkindfilter_.proto

It has these top-level messages:
	CredentialKindFilter
*/
package credentialkindfilter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import credentialkind "github.com/21stio/go-playground/grpc/schema/credentialkind"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CredentialKindFilter struct {
	Is               *credentialkind.CredentialKind  `protobuf:"varint,1,opt,name=is,enum=credentialkind.CredentialKind" json:"is,omitempty"`
	Not              *credentialkind.CredentialKind  `protobuf:"varint,2,opt,name=not,enum=credentialkind.CredentialKind" json:"not,omitempty"`
	In               []credentialkind.CredentialKind `protobuf:"varint,3,rep,name=in,enum=credentialkind.CredentialKind" json:"in,omitempty"`
	NotIn            []credentialkind.CredentialKind `protobuf:"varint,4,rep,name=notIn,enum=credentialkind.CredentialKind" json:"notIn,omitempty"`
	Hash             *string                         `protobuf:"bytes,5,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *CredentialKindFilter) Reset()                    { *m = CredentialKindFilter{} }
func (m *CredentialKindFilter) String() string            { return proto.CompactTextString(m) }
func (*CredentialKindFilter) ProtoMessage()               {}
func (*CredentialKindFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CredentialKindFilter) GetIs() credentialkind.CredentialKind {
	if m != nil && m.Is != nil {
		return *m.Is
	}
	return credentialkind.CredentialKind_CREDENTIAL_EMAIL_PASSWORD_CREDENTIAL
}

func (m *CredentialKindFilter) GetNot() credentialkind.CredentialKind {
	if m != nil && m.Not != nil {
		return *m.Not
	}
	return credentialkind.CredentialKind_CREDENTIAL_EMAIL_PASSWORD_CREDENTIAL
}

func (m *CredentialKindFilter) GetIn() []credentialkind.CredentialKind {
	if m != nil {
		return m.In
	}
	return nil
}

func (m *CredentialKindFilter) GetNotIn() []credentialkind.CredentialKind {
	if m != nil {
		return m.NotIn
	}
	return nil
}

func (m *CredentialKindFilter) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*CredentialKindFilter)(nil), "credentialkindfilter.CredentialKindFilter")
}

func init() { proto.RegisterFile("credentialkindfilter/credentialkindfilter_.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x48, 0x2e, 0x4a, 0x4d,
	0x49, 0xcd, 0x2b, 0xc9, 0x4c, 0xcc, 0xc9, 0xce, 0xcc, 0x4b, 0x49, 0xcb, 0xcc, 0x29, 0x49, 0x2d,
	0xd2, 0xc7, 0x26, 0x18, 0xaf, 0x57, 0x50, 0x94, 0x5f, 0x92, 0x2f, 0x24, 0x82, 0x4d, 0x52, 0x4a,
	0x05, 0x55, 0x14, 0xcd, 0x04, 0xa8, 0x5e, 0xa5, 0x4f, 0x8c, 0x5c, 0x22, 0xce, 0x70, 0x19, 0xef,
	0xcc, 0xbc, 0x14, 0x37, 0xb0, 0x76, 0x21, 0x3d, 0x2e, 0xa6, 0xcc, 0x62, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0x3e, 0x23, 0x39, 0x3d, 0x54, 0xcd, 0x7a, 0xa8, 0x3a, 0x82, 0x98, 0x32, 0x8b, 0x85, 0x0c,
	0xb8, 0x98, 0xf3, 0xf2, 0x4b, 0x24, 0x98, 0x88, 0xd2, 0x00, 0x52, 0x0a, 0xb6, 0x21, 0x4f, 0x82,
	0x59, 0x81, 0x99, 0x28, 0x1b, 0xf2, 0x84, 0x4c, 0xb8, 0x58, 0xf3, 0xf2, 0x4b, 0x3c, 0xf3, 0x24,
	0x58, 0x88, 0xd2, 0x02, 0x51, 0x2c, 0x24, 0xc4, 0xc5, 0x92, 0x91, 0x58, 0x9c, 0x21, 0xc1, 0xaa,
	0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x3b, 0x39, 0x45, 0x39, 0xa4, 0x67, 0x96, 0x64, 0x94, 0x26,
	0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x1b, 0x19, 0x16, 0x97, 0x64, 0xe6, 0xeb, 0xa7, 0xe7, 0xeb, 0x16,
	0xe4, 0x24, 0x56, 0xa6, 0x17, 0xe5, 0x97, 0xe6, 0xa5, 0xe8, 0xa7, 0x17, 0x15, 0x24, 0xeb, 0x17,
	0x27, 0x67, 0xa4, 0xe6, 0x26, 0x62, 0x0d, 0x7b, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x79,
	0xa2, 0x4b, 0xa7, 0x01, 0x00, 0x00,
}
