// Code generated by protoc-gen-go. DO NOT EDIT.
// source: floatfilter/floatfilter_.proto

/*
Package floatfilter is a generated protocol buffer package.

It is generated from these files:
	floatfilter/floatfilter_.proto

It has these top-level messages:
	FloatFilter
*/
package floatfilter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FloatFilter struct {
	Set              *bool     `protobuf:"varint,1,opt,name=set" json:"set,omitempty"`
	Is               *float64  `protobuf:"fixed64,2,opt,name=is" json:"is,omitempty"`
	Not              *float64  `protobuf:"fixed64,3,opt,name=not" json:"not,omitempty"`
	Lt               *float64  `protobuf:"fixed64,4,opt,name=lt" json:"lt,omitempty"`
	Lte              *float64  `protobuf:"fixed64,5,opt,name=lte" json:"lte,omitempty"`
	Gt               *float64  `protobuf:"fixed64,6,opt,name=gt" json:"gt,omitempty"`
	Gte              *float64  `protobuf:"fixed64,7,opt,name=gte" json:"gte,omitempty"`
	In               []float64 `protobuf:"fixed64,8,rep,name=in" json:"in,omitempty"`
	NotIn            []float64 `protobuf:"fixed64,9,rep,name=notIn" json:"notIn,omitempty"`
	Hash             *string   `protobuf:"bytes,10,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *FloatFilter) Reset()                    { *m = FloatFilter{} }
func (m *FloatFilter) String() string            { return proto.CompactTextString(m) }
func (*FloatFilter) ProtoMessage()               {}
func (*FloatFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FloatFilter) GetSet() bool {
	if m != nil && m.Set != nil {
		return *m.Set
	}
	return false
}

func (m *FloatFilter) GetIs() float64 {
	if m != nil && m.Is != nil {
		return *m.Is
	}
	return 0
}

func (m *FloatFilter) GetNot() float64 {
	if m != nil && m.Not != nil {
		return *m.Not
	}
	return 0
}

func (m *FloatFilter) GetLt() float64 {
	if m != nil && m.Lt != nil {
		return *m.Lt
	}
	return 0
}

func (m *FloatFilter) GetLte() float64 {
	if m != nil && m.Lte != nil {
		return *m.Lte
	}
	return 0
}

func (m *FloatFilter) GetGt() float64 {
	if m != nil && m.Gt != nil {
		return *m.Gt
	}
	return 0
}

func (m *FloatFilter) GetGte() float64 {
	if m != nil && m.Gte != nil {
		return *m.Gte
	}
	return 0
}

func (m *FloatFilter) GetIn() []float64 {
	if m != nil {
		return m.In
	}
	return nil
}

func (m *FloatFilter) GetNotIn() []float64 {
	if m != nil {
		return m.NotIn
	}
	return nil
}

func (m *FloatFilter) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*FloatFilter)(nil), "floatfilter.FloatFilter")
}

func init() { proto.RegisterFile("floatfilter/floatfilter_.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xd0, 0x31, 0x4b, 0x04, 0x31,
	0x10, 0x05, 0x60, 0xb2, 0x7b, 0xa7, 0x77, 0x39, 0x10, 0x09, 0x16, 0x53, 0xc9, 0x62, 0xb5, 0x8d,
	0x17, 0xb4, 0x11, 0x5b, 0x8b, 0x03, 0xdb, 0x2d, 0x6d, 0x64, 0x5d, 0x73, 0x93, 0x40, 0x2e, 0xb3,
	0x24, 0xb3, 0x85, 0xbf, 0xce, 0xbf, 0x76, 0x24, 0x69, 0xb6, 0x7b, 0xef, 0xf1, 0xc1, 0xc0, 0xc8,
	0xc7, 0xb3, 0xa7, 0x91, 0xcf, 0xce, 0xb3, 0x89, 0x7a, 0x95, 0xbf, 0x8f, 0x73, 0x24, 0x26, 0x75,
	0x58, 0x6d, 0x4f, 0xff, 0x42, 0x1e, 0x4e, 0xb9, 0x9f, 0x4a, 0x57, 0xf7, 0xb2, 0x4d, 0x86, 0x41,
	0x74, 0xa2, 0xdf, 0x0d, 0x39, 0xaa, 0x3b, 0xd9, 0xb8, 0x04, 0x4d, 0x27, 0x7a, 0x31, 0x34, 0x2e,
	0x65, 0x11, 0x88, 0xa1, 0x2d, 0x43, 0x8e, 0x59, 0x78, 0x86, 0x4d, 0x15, 0x9e, 0xb3, 0xf0, 0x6c,
	0x60, 0x5b, 0x85, 0x67, 0x93, 0x05, 0x32, 0xdc, 0x54, 0x81, 0x45, 0x20, 0x1b, 0xb8, 0xad, 0x02,
	0xab, 0x70, 0x01, 0x76, 0x5d, 0x5b, 0xae, 0x04, 0xf5, 0x20, 0xb7, 0x81, 0xf8, 0x33, 0xc0, 0xbe,
	0x4c, 0xb5, 0x28, 0x25, 0x37, 0x76, 0x4c, 0x16, 0x64, 0x27, 0xfa, 0xfd, 0x50, 0xf2, 0xc7, 0xfb,
	0xd7, 0x1b, 0x3a, 0xb6, 0xcb, 0xcf, 0x71, 0xa2, 0x8b, 0x7e, 0x7d, 0x49, 0xec, 0x48, 0x23, 0x3d,
	0xcf, 0x7e, 0xfc, 0xc3, 0x48, 0x4b, 0xf8, 0xd5, 0x18, 0xe7, 0x49, 0xa7, 0xc9, 0x9a, 0xcb, 0xb8,
	0x7e, 0xc8, 0x35, 0x00, 0x00, 0xff, 0xff, 0x01, 0xfa, 0x4f, 0xcb, 0x2a, 0x01, 0x00, 0x00,
}
