// Code generated by protoc-gen-go. DO NOT EDIT.
// source: passdeletesocialaccountsrequestrequestfilter/passdeletesocialaccountsrequestrequestfilter_.proto

/*
Package passdeletesocialaccountsrequestrequestfilter is a generated protocol buffer package.

It is generated from these files:
	passdeletesocialaccountsrequestrequestfilter/passdeletesocialaccountsrequestrequestfilter_.proto

It has these top-level messages:
	PassDeleteSocialAccountsRequestRequestFilter
*/
package passdeletesocialaccountsrequestrequestfilter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import requestmetafilter "github.com/21stio/go-playground/grpc/schema/requestmetafilter"
import deletesocialaccountsrequestfilter "github.com/21stio/go-playground/grpc/schema/deletesocialaccountsrequestfilter"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PassDeleteSocialAccountsRequestRequestFilter struct {
	Meta                        *requestmetafilter.RequestMetaFilter                                 `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	DeleteSocialAccountsRequest *deletesocialaccountsrequestfilter.DeleteSocialAccountsRequestFilter `protobuf:"bytes,2,opt,name=deleteSocialAccountsRequest" json:"deleteSocialAccountsRequest,omitempty"`
	And                         []*PassDeleteSocialAccountsRequestRequestFilter                      `protobuf:"bytes,3,rep,name=and" json:"and,omitempty"`
	Or                          []*PassDeleteSocialAccountsRequestRequestFilter                      `protobuf:"bytes,4,rep,name=or" json:"or,omitempty"`
	Not                         []*PassDeleteSocialAccountsRequestRequestFilter                      `protobuf:"bytes,5,rep,name=not" json:"not,omitempty"`
	Hash                        *string                                                              `protobuf:"bytes,6,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized            []byte                                                               `json:"-"`
}

func (m *PassDeleteSocialAccountsRequestRequestFilter) Reset() {
	*m = PassDeleteSocialAccountsRequestRequestFilter{}
}
func (m *PassDeleteSocialAccountsRequestRequestFilter) String() string {
	return proto.CompactTextString(m)
}
func (*PassDeleteSocialAccountsRequestRequestFilter) ProtoMessage() {}
func (*PassDeleteSocialAccountsRequestRequestFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0}
}

func (m *PassDeleteSocialAccountsRequestRequestFilter) GetMeta() *requestmetafilter.RequestMetaFilter {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *PassDeleteSocialAccountsRequestRequestFilter) GetDeleteSocialAccountsRequest() *deletesocialaccountsrequestfilter.DeleteSocialAccountsRequestFilter {
	if m != nil {
		return m.DeleteSocialAccountsRequest
	}
	return nil
}

func (m *PassDeleteSocialAccountsRequestRequestFilter) GetAnd() []*PassDeleteSocialAccountsRequestRequestFilter {
	if m != nil {
		return m.And
	}
	return nil
}

func (m *PassDeleteSocialAccountsRequestRequestFilter) GetOr() []*PassDeleteSocialAccountsRequestRequestFilter {
	if m != nil {
		return m.Or
	}
	return nil
}

func (m *PassDeleteSocialAccountsRequestRequestFilter) GetNot() []*PassDeleteSocialAccountsRequestRequestFilter {
	if m != nil {
		return m.Not
	}
	return nil
}

func (m *PassDeleteSocialAccountsRequestRequestFilter) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*PassDeleteSocialAccountsRequestRequestFilter)(nil), "passdeletesocialaccountsrequestrequestfilter.PassDeleteSocialAccountsRequestRequestFilter")
}

func init() {
	proto.RegisterFile("passdeletesocialaccountsrequestrequestfilter/passdeletesocialaccountsrequestrequestfilter_.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xcf, 0x4a, 0xf4, 0x30,
	0x14, 0xc5, 0xe9, 0x9f, 0xef, 0x03, 0x33, 0xbb, 0xac, 0xc2, 0xb8, 0x29, 0xe2, 0xa2, 0xc8, 0x98,
	0x62, 0x57, 0x6e, 0x95, 0xc1, 0x85, 0x20, 0x48, 0xdd, 0x48, 0x37, 0x1a, 0xd3, 0xd8, 0x56, 0xda,
	0xde, 0x9a, 0xdc, 0x2e, 0x7c, 0x01, 0xdf, 0xce, 0x77, 0x92, 0x66, 0xb2, 0x1b, 0xec, 0x90, 0xc5,
	0xac, 0x6e, 0x12, 0xee, 0xef, 0x9c, 0x73, 0x13, 0x42, 0x5e, 0x47, 0x61, 0x4c, 0xa5, 0x3a, 0x85,
	0xca, 0x80, 0x6c, 0x45, 0x27, 0xa4, 0x84, 0x69, 0x40, 0xa3, 0xd5, 0xe7, 0xa4, 0x0c, 0xba, 0xf2,
	0xde, 0x76, 0xa8, 0x74, 0xe6, 0xd3, 0xfc, 0xc2, 0x47, 0x0d, 0x08, 0x74, 0xe3, 0x03, 0xad, 0x2f,
	0xdc, 0xb6, 0x57, 0x28, 0x9c, 0xe9, 0xde, 0x89, 0x53, 0x5e, 0xdf, 0x2f, 0xa8, 0x3a, 0xf6, 0x60,
	0x87, 0xd3, 0x3a, 0xfb, 0x89, 0xc9, 0xe6, 0x51, 0x18, 0xb3, 0xb5, 0xc0, 0x93, 0x05, 0x6e, 0x1c,
	0x50, 0xec, 0x00, 0x57, 0xee, 0x2c, 0x47, 0xaf, 0x49, 0x3c, 0x27, 0x62, 0x41, 0x12, 0xa4, 0xab,
	0xfc, 0x9c, 0xef, 0xa5, 0xe4, 0xae, 0xff, 0x41, 0xa1, 0xd8, 0x31, 0x85, 0x25, 0xe8, 0x77, 0x40,
	0x4e, 0xab, 0xbf, 0x6d, 0x58, 0x68, 0x15, 0xb7, 0xfc, 0x60, 0x76, 0xbe, 0x10, 0xd6, 0x39, 0x2e,
	0x19, 0xd1, 0x8e, 0x44, 0x62, 0xa8, 0x58, 0x94, 0x44, 0xe9, 0x2a, 0x2f, 0xb9, 0xcf, 0x3b, 0x71,
	0x9f, 0xbb, 0x2a, 0x66, 0x1b, 0xfa, 0x41, 0x42, 0xd0, 0x2c, 0x3e, 0xba, 0x59, 0x08, 0x7a, 0x9e,
	0x6c, 0x00, 0x64, 0xff, 0x8e, 0x3f, 0xd9, 0x00, 0x48, 0x29, 0x89, 0x1b, 0x61, 0x1a, 0xf6, 0x3f,
	0x09, 0xd2, 0x93, 0xc2, 0xae, 0x6f, 0xcb, 0xf2, 0xb9, 0x6e, 0xb1, 0x99, 0xde, 0xb8, 0x84, 0x3e,
	0xcb, 0xaf, 0x0c, 0xb6, 0x90, 0xd5, 0x70, 0x39, 0x76, 0xe2, 0xab, 0xd6, 0x30, 0x0d, 0x55, 0x56,
	0xeb, 0x51, 0x66, 0x46, 0x36, 0xaa, 0x17, 0x5e, 0x1f, 0xeb, 0x37, 0x00, 0x00, 0xff, 0xff, 0xe9,
	0xed, 0x2e, 0x64, 0xb4, 0x03, 0x00, 0x00,
}
