// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commenttermkindfilter/commenttermkindfilter_.proto

/*
Package commenttermkindfilter is a generated protocol buffer package.

It is generated from these files:
	commenttermkindfilter/commenttermkindfilter_.proto

It has these top-level messages:
	CommentTermKindFilter
*/
package commenttermkindfilter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import commenttermkind "github.com/21stio/go-playground/grpc/schema/commenttermkind"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommentTermKindFilter struct {
	Is               *commenttermkind.CommentTermKind  `protobuf:"varint,1,opt,name=is,enum=commenttermkind.CommentTermKind" json:"is,omitempty"`
	Not              *commenttermkind.CommentTermKind  `protobuf:"varint,2,opt,name=not,enum=commenttermkind.CommentTermKind" json:"not,omitempty"`
	In               []commenttermkind.CommentTermKind `protobuf:"varint,3,rep,name=in,enum=commenttermkind.CommentTermKind" json:"in,omitempty"`
	NotIn            []commenttermkind.CommentTermKind `protobuf:"varint,4,rep,name=notIn,enum=commenttermkind.CommentTermKind" json:"notIn,omitempty"`
	Hash             *string                           `protobuf:"bytes,5,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (m *CommentTermKindFilter) Reset()                    { *m = CommentTermKindFilter{} }
func (m *CommentTermKindFilter) String() string            { return proto.CompactTextString(m) }
func (*CommentTermKindFilter) ProtoMessage()               {}
func (*CommentTermKindFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CommentTermKindFilter) GetIs() commenttermkind.CommentTermKind {
	if m != nil && m.Is != nil {
		return *m.Is
	}
	return commenttermkind.CommentTermKind_COMMENT
}

func (m *CommentTermKindFilter) GetNot() commenttermkind.CommentTermKind {
	if m != nil && m.Not != nil {
		return *m.Not
	}
	return commenttermkind.CommentTermKind_COMMENT
}

func (m *CommentTermKindFilter) GetIn() []commenttermkind.CommentTermKind {
	if m != nil {
		return m.In
	}
	return nil
}

func (m *CommentTermKindFilter) GetNotIn() []commenttermkind.CommentTermKind {
	if m != nil {
		return m.NotIn
	}
	return nil
}

func (m *CommentTermKindFilter) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*CommentTermKindFilter)(nil), "commenttermkindfilter.CommentTermKindFilter")
}

func init() { proto.RegisterFile("commenttermkindfilter/commenttermkindfilter_.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4a, 0xce, 0xcf, 0xcd,
	0x4d, 0xcd, 0x2b, 0x29, 0x49, 0x2d, 0xca, 0xcd, 0xce, 0xcc, 0x4b, 0x49, 0xcb, 0xcc, 0x29, 0x49,
	0x2d, 0xd2, 0xc7, 0x2a, 0x1a, 0xaf, 0x57, 0x50, 0x94, 0x5f, 0x92, 0x2f, 0x24, 0x8a, 0x55, 0x56,
	0x4a, 0x0d, 0x4d, 0x18, 0xdd, 0x10, 0xa8, 0x76, 0xa5, 0xdf, 0x8c, 0x5c, 0xa2, 0xce, 0x10, 0xa9,
	0x90, 0xd4, 0xa2, 0x5c, 0xef, 0xcc, 0xbc, 0x14, 0x37, 0xb0, 0x09, 0x42, 0x06, 0x5c, 0x4c, 0x99,
	0xc5, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x7c, 0x46, 0x0a, 0x7a, 0x68, 0xda, 0xf5, 0xd0, 0xf4, 0x04,
	0x31, 0x65, 0x16, 0x0b, 0x19, 0x71, 0x31, 0xe7, 0xe5, 0x97, 0x48, 0x30, 0x11, 0xa9, 0x05, 0xa4,
	0x18, 0x6c, 0x4b, 0x9e, 0x04, 0xb3, 0x02, 0x33, 0x91, 0xb6, 0xe4, 0x09, 0x99, 0x71, 0xb1, 0xe6,
	0xe5, 0x97, 0x78, 0xe6, 0x49, 0xb0, 0x10, 0xa9, 0x09, 0xa2, 0x5c, 0x48, 0x88, 0x8b, 0x25, 0x23,
	0xb1, 0x38, 0x43, 0x82, 0x55, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x76, 0x72, 0x8e, 0x72, 0x4c,
	0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0x02, 0x19, 0xa2, 0x6f, 0x64, 0x58, 0x5c, 0x92, 0x99, 0xaf, 0x9f,
	0x9e, 0xaf, 0x5b, 0x90, 0x93, 0x58, 0x99, 0x5e, 0x94, 0x5f, 0x9a, 0x97, 0xa2, 0x9f, 0x5e, 0x54,
	0x90, 0xac, 0x5f, 0x9c, 0x9c, 0x91, 0x9a, 0x9b, 0x88, 0x3d, 0x22, 0x00, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x58, 0x38, 0x13, 0x7b, 0xb6, 0x01, 0x00, 0x00,
}
