SOURCE_MAKE=. ./.make/make.sh

provision:
	@${SOURCE_MAKE} && provision

build:
	@${SOURCE_MAKE} && build

deploy:
	@${SOURCE_MAKE} && deploy

info:
	@${SOURCE_MAKE} && info

gen:
	@${SOURCE_MAKE} && gen

package:
	@${SOURCE_MAKE} && package

package_pip:
	@${SOURCE_MAKE} && package_pip

tag:
	@${SOURCE_MAKE} && tag