// Code generated by protoc-gen-go. DO NOT EDIT.
// source: passupdatecompaniesrequestrequestfilter/passupdatecompaniesrequestrequestfilter_.proto

/*
Package passupdatecompaniesrequestrequestfilter is a generated protocol buffer package.

It is generated from these files:
	passupdatecompaniesrequestrequestfilter/passupdatecompaniesrequestrequestfilter_.proto

It has these top-level messages:
	PassUpdateCompaniesRequestRequestFilter
*/
package passupdatecompaniesrequestrequestfilter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import requestmetafilter "github.com/21stio/go-playground/grpc/schema/requestmetafilter"
import updatecompaniesrequestfilter "github.com/21stio/go-playground/grpc/schema/updatecompaniesrequestfilter"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PassUpdateCompaniesRequestRequestFilter struct {
	Meta                   *requestmetafilter.RequestMetaFilter                       `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	UpdateCompaniesRequest *updatecompaniesrequestfilter.UpdateCompaniesRequestFilter `protobuf:"bytes,2,opt,name=updateCompaniesRequest" json:"updateCompaniesRequest,omitempty"`
	And                    []*PassUpdateCompaniesRequestRequestFilter                 `protobuf:"bytes,3,rep,name=and" json:"and,omitempty"`
	Or                     []*PassUpdateCompaniesRequestRequestFilter                 `protobuf:"bytes,4,rep,name=or" json:"or,omitempty"`
	Not                    []*PassUpdateCompaniesRequestRequestFilter                 `protobuf:"bytes,5,rep,name=not" json:"not,omitempty"`
	Hash                   *string                                                    `protobuf:"bytes,6,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized       []byte                                                     `json:"-"`
}

func (m *PassUpdateCompaniesRequestRequestFilter) Reset() {
	*m = PassUpdateCompaniesRequestRequestFilter{}
}
func (m *PassUpdateCompaniesRequestRequestFilter) String() string { return proto.CompactTextString(m) }
func (*PassUpdateCompaniesRequestRequestFilter) ProtoMessage()    {}
func (*PassUpdateCompaniesRequestRequestFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0}
}

func (m *PassUpdateCompaniesRequestRequestFilter) GetMeta() *requestmetafilter.RequestMetaFilter {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *PassUpdateCompaniesRequestRequestFilter) GetUpdateCompaniesRequest() *updatecompaniesrequestfilter.UpdateCompaniesRequestFilter {
	if m != nil {
		return m.UpdateCompaniesRequest
	}
	return nil
}

func (m *PassUpdateCompaniesRequestRequestFilter) GetAnd() []*PassUpdateCompaniesRequestRequestFilter {
	if m != nil {
		return m.And
	}
	return nil
}

func (m *PassUpdateCompaniesRequestRequestFilter) GetOr() []*PassUpdateCompaniesRequestRequestFilter {
	if m != nil {
		return m.Or
	}
	return nil
}

func (m *PassUpdateCompaniesRequestRequestFilter) GetNot() []*PassUpdateCompaniesRequestRequestFilter {
	if m != nil {
		return m.Not
	}
	return nil
}

func (m *PassUpdateCompaniesRequestRequestFilter) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*PassUpdateCompaniesRequestRequestFilter)(nil), "passupdatecompaniesrequestrequestfilter.PassUpdateCompaniesRequestRequestFilter")
}

func init() {
	proto.RegisterFile("passupdatecompaniesrequestrequestfilter/passupdatecompaniesrequestrequestfilter_.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x3f, 0x4b, 0xc3, 0x40,
	0x14, 0xa7, 0x49, 0x14, 0xbc, 0x6e, 0x37, 0xc8, 0xd1, 0x29, 0x88, 0xd0, 0x20, 0x78, 0xc1, 0x4c,
	0xe2, 0x24, 0x0a, 0x6e, 0x42, 0x89, 0xd4, 0xc1, 0x45, 0x5f, 0x93, 0x33, 0x09, 0x34, 0x79, 0xe7,
	0xdd, 0xcb, 0xe0, 0x07, 0xf1, 0xfb, 0x4a, 0xd2, 0x73, 0x6a, 0x2c, 0xb7, 0x74, 0x7a, 0xf7, 0xe7,
	0xf7, 0xef, 0x3d, 0x78, 0xec, 0x55, 0x83, 0xb5, 0xbd, 0x2e, 0x81, 0x54, 0x81, 0xad, 0x86, 0xae,
	0x51, 0xd6, 0xa8, 0xaf, 0x5e, 0x59, 0x72, 0xe5, 0xb3, 0xd9, 0x92, 0x32, 0xa9, 0x27, 0xee, 0x5d,
	0x6a, 0x83, 0x84, 0x7c, 0xe9, 0x89, 0x5f, 0x5c, 0xb9, 0x6b, 0xab, 0x08, 0x9c, 0xd5, 0xde, 0x8b,
	0x13, 0x5d, 0xdc, 0x4f, 0x0b, 0x3a, 0xda, 0xa1, 0x4f, 0xa7, 0x70, 0xf1, 0x13, 0xb1, 0xe5, 0x0a,
	0xac, 0x5d, 0x8f, 0xd8, 0xc7, 0x3f, 0x6c, 0xbe, 0xc3, 0xba, 0xf2, 0x34, 0x52, 0xf8, 0x2d, 0x8b,
	0x86, 0x08, 0x62, 0x16, 0xcf, 0x92, 0x79, 0x76, 0x29, 0xf7, 0x62, 0x49, 0x87, 0x7f, 0x56, 0x04,
	0x3b, 0x4e, 0x3e, 0x32, 0xb8, 0x61, 0xe7, 0xfd, 0xa4, 0x81, 0x08, 0x46, 0xad, 0x3b, 0x79, 0x28,
	0xab, 0x9c, 0x0e, 0xe7, 0x1c, 0xfe, 0x51, 0xe6, 0x1b, 0x16, 0x42, 0x57, 0x8a, 0x30, 0x0e, 0x93,
	0x79, 0xb6, 0x92, 0x9e, 0xe3, 0x97, 0x9e, 0xc3, 0xc8, 0x07, 0x71, 0xfe, 0xc1, 0x02, 0x34, 0x22,
	0x3a, 0x92, 0x45, 0x80, 0x66, 0xe8, 0xa2, 0x43, 0x12, 0x27, 0xc7, 0xea, 0xa2, 0x43, 0xe2, 0x9c,
	0x45, 0x35, 0xd8, 0x5a, 0x9c, 0xc6, 0xb3, 0xe4, 0x2c, 0x1f, 0xcf, 0x0f, 0xeb, 0xb7, 0x97, 0xaa,
	0xa1, 0xba, 0xdf, 0xc8, 0x02, 0xdb, 0x34, 0xbb, 0xb1, 0xd4, 0x60, 0x5a, 0xe1, 0xb5, 0xde, 0xc2,
	0x77, 0x65, 0xb0, 0xef, 0xca, 0xb4, 0x32, 0xba, 0x48, 0x6d, 0x51, 0xab, 0x16, 0x7c, 0x97, 0xe1,
	0x37, 0x00, 0x00, 0xff, 0xff, 0x28, 0xda, 0x75, 0xb5, 0x5e, 0x03, 0x00, 0x00,
}
