// Code generated by protoc-gen-go. DO NOT EDIT.
// source: passupdatesocialaccountsrequestrequestfilter/passupdatesocialaccountsrequestrequestfilter_.proto

/*
Package passupdatesocialaccountsrequestrequestfilter is a generated protocol buffer package.

It is generated from these files:
	passupdatesocialaccountsrequestrequestfilter/passupdatesocialaccountsrequestrequestfilter_.proto

It has these top-level messages:
	PassUpdateSocialAccountsRequestRequestFilter
*/
package passupdatesocialaccountsrequestrequestfilter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import requestmetafilter "github.com/21stio/go-playground/grpc/schema/requestmetafilter"
import updatesocialaccountsrequestfilter "github.com/21stio/go-playground/grpc/schema/updatesocialaccountsrequestfilter"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PassUpdateSocialAccountsRequestRequestFilter struct {
	Meta                        *requestmetafilter.RequestMetaFilter                                 `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	UpdateSocialAccountsRequest *updatesocialaccountsrequestfilter.UpdateSocialAccountsRequestFilter `protobuf:"bytes,2,opt,name=updateSocialAccountsRequest" json:"updateSocialAccountsRequest,omitempty"`
	And                         []*PassUpdateSocialAccountsRequestRequestFilter                      `protobuf:"bytes,3,rep,name=and" json:"and,omitempty"`
	Or                          []*PassUpdateSocialAccountsRequestRequestFilter                      `protobuf:"bytes,4,rep,name=or" json:"or,omitempty"`
	Not                         []*PassUpdateSocialAccountsRequestRequestFilter                      `protobuf:"bytes,5,rep,name=not" json:"not,omitempty"`
	Hash                        *string                                                              `protobuf:"bytes,6,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized            []byte                                                               `json:"-"`
}

func (m *PassUpdateSocialAccountsRequestRequestFilter) Reset() {
	*m = PassUpdateSocialAccountsRequestRequestFilter{}
}
func (m *PassUpdateSocialAccountsRequestRequestFilter) String() string {
	return proto.CompactTextString(m)
}
func (*PassUpdateSocialAccountsRequestRequestFilter) ProtoMessage() {}
func (*PassUpdateSocialAccountsRequestRequestFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0}
}

func (m *PassUpdateSocialAccountsRequestRequestFilter) GetMeta() *requestmetafilter.RequestMetaFilter {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *PassUpdateSocialAccountsRequestRequestFilter) GetUpdateSocialAccountsRequest() *updatesocialaccountsrequestfilter.UpdateSocialAccountsRequestFilter {
	if m != nil {
		return m.UpdateSocialAccountsRequest
	}
	return nil
}

func (m *PassUpdateSocialAccountsRequestRequestFilter) GetAnd() []*PassUpdateSocialAccountsRequestRequestFilter {
	if m != nil {
		return m.And
	}
	return nil
}

func (m *PassUpdateSocialAccountsRequestRequestFilter) GetOr() []*PassUpdateSocialAccountsRequestRequestFilter {
	if m != nil {
		return m.Or
	}
	return nil
}

func (m *PassUpdateSocialAccountsRequestRequestFilter) GetNot() []*PassUpdateSocialAccountsRequestRequestFilter {
	if m != nil {
		return m.Not
	}
	return nil
}

func (m *PassUpdateSocialAccountsRequestRequestFilter) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*PassUpdateSocialAccountsRequestRequestFilter)(nil), "passupdatesocialaccountsrequestrequestfilter.PassUpdateSocialAccountsRequestRequestFilter")
}

func init() {
	proto.RegisterFile("passupdatesocialaccountsrequestrequestfilter/passupdatesocialaccountsrequestrequestfilter_.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xcf, 0x4a, 0xf4, 0x30,
	0x14, 0xc5, 0xe9, 0x9f, 0xef, 0x03, 0x33, 0xbb, 0xac, 0xc2, 0xb8, 0x29, 0xe2, 0xa2, 0xc8, 0x98,
	0x62, 0x57, 0x6e, 0x15, 0x71, 0x21, 0x08, 0x52, 0x11, 0xa4, 0x1b, 0x8d, 0x69, 0x6c, 0x2b, 0x6d,
	0x6f, 0x4d, 0x6e, 0x16, 0xbe, 0x80, 0x6f, 0xe7, 0x3b, 0x49, 0x33, 0xd9, 0x0d, 0x76, 0xe8, 0x62,
	0x56, 0x37, 0x09, 0xf7, 0x77, 0xce, 0xb9, 0x09, 0x21, 0xaf, 0xa3, 0x30, 0xc6, 0x8e, 0x95, 0x40,
	0x65, 0x40, 0xb6, 0xa2, 0x13, 0x52, 0x82, 0x1d, 0xd0, 0x68, 0xf5, 0x69, 0x95, 0x41, 0x5f, 0xde,
	0xdb, 0x0e, 0x95, 0xce, 0x96, 0x34, 0xbf, 0xf0, 0x51, 0x03, 0x02, 0xdd, 0x2c, 0x81, 0xd6, 0x67,
	0x7e, 0xdb, 0x2b, 0x14, 0xde, 0x74, 0xe7, 0xc4, 0x2b, 0xaf, 0xef, 0x66, 0x54, 0x3d, 0xbb, 0xb7,
	0xc3, 0x6b, 0x9d, 0xfc, 0xc4, 0x64, 0xf3, 0x20, 0x8c, 0x79, 0x72, 0xc0, 0xa3, 0x03, 0xae, 0x3c,
	0x50, 0x6c, 0x01, 0x5f, 0x6e, 0x1d, 0x47, 0x2f, 0x49, 0x3c, 0x25, 0x62, 0x41, 0x12, 0xa4, 0xab,
	0xfc, 0x94, 0xef, 0xa4, 0xe4, 0xbe, 0xff, 0x5e, 0xa1, 0xd8, 0x32, 0x85, 0x23, 0xe8, 0x77, 0x40,
	0x8e, 0xed, 0xdf, 0x36, 0x2c, 0x74, 0x8a, 0x37, 0x7c, 0x6f, 0x76, 0x3e, 0x13, 0xd6, 0x3b, 0xce,
	0x19, 0xd1, 0x8e, 0x44, 0x62, 0xa8, 0x58, 0x94, 0x44, 0xe9, 0x2a, 0x2f, 0xf9, 0x92, 0x77, 0xe2,
	0x4b, 0xee, 0xaa, 0x98, 0x6c, 0xe8, 0x07, 0x09, 0x41, 0xb3, 0xf8, 0xe0, 0x66, 0x21, 0xe8, 0x69,
	0xb2, 0x01, 0x90, 0xfd, 0x3b, 0xfc, 0x64, 0x03, 0x20, 0xa5, 0x24, 0x6e, 0x84, 0x69, 0xd8, 0xff,
	0x24, 0x48, 0x8f, 0x0a, 0xb7, 0xbe, 0x2e, 0xcb, 0xe7, 0xba, 0xc5, 0xc6, 0xbe, 0x71, 0x09, 0x7d,
	0x96, 0x5f, 0x18, 0x6c, 0x21, 0xab, 0xe1, 0x7c, 0xec, 0xc4, 0x57, 0xad, 0xc1, 0x0e, 0x55, 0x56,
	0xeb, 0x51, 0x66, 0x46, 0x36, 0xaa, 0x17, 0x8b, 0x3e, 0xd6, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xd7, 0x53, 0x19, 0x46, 0xb4, 0x03, 0x00, 0x00,
}
