// Code generated by protoc-gen-go. DO NOT EDIT.
// source: intfilter/intfilter_.proto

/*
Package intfilter is a generated protocol buffer package.

It is generated from these files:
	intfilter/intfilter_.proto

It has these top-level messages:
	IntFilter
*/
package intfilter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IntFilter struct {
	Set              *bool   `protobuf:"varint,1,opt,name=set" json:"set,omitempty"`
	Is               *int32  `protobuf:"varint,2,opt,name=is" json:"is,omitempty"`
	Not              *int32  `protobuf:"varint,3,opt,name=not" json:"not,omitempty"`
	Lt               *int32  `protobuf:"varint,4,opt,name=lt" json:"lt,omitempty"`
	Lte              *int32  `protobuf:"varint,5,opt,name=lte" json:"lte,omitempty"`
	Gt               *int32  `protobuf:"varint,6,opt,name=gt" json:"gt,omitempty"`
	Gte              *int32  `protobuf:"varint,7,opt,name=gte" json:"gte,omitempty"`
	In               []int32 `protobuf:"varint,8,rep,name=in" json:"in,omitempty"`
	NotIn            []int32 `protobuf:"varint,9,rep,name=notIn" json:"notIn,omitempty"`
	Hash             *string `protobuf:"bytes,10,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IntFilter) Reset()                    { *m = IntFilter{} }
func (m *IntFilter) String() string            { return proto.CompactTextString(m) }
func (*IntFilter) ProtoMessage()               {}
func (*IntFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IntFilter) GetSet() bool {
	if m != nil && m.Set != nil {
		return *m.Set
	}
	return false
}

func (m *IntFilter) GetIs() int32 {
	if m != nil && m.Is != nil {
		return *m.Is
	}
	return 0
}

func (m *IntFilter) GetNot() int32 {
	if m != nil && m.Not != nil {
		return *m.Not
	}
	return 0
}

func (m *IntFilter) GetLt() int32 {
	if m != nil && m.Lt != nil {
		return *m.Lt
	}
	return 0
}

func (m *IntFilter) GetLte() int32 {
	if m != nil && m.Lte != nil {
		return *m.Lte
	}
	return 0
}

func (m *IntFilter) GetGt() int32 {
	if m != nil && m.Gt != nil {
		return *m.Gt
	}
	return 0
}

func (m *IntFilter) GetGte() int32 {
	if m != nil && m.Gte != nil {
		return *m.Gte
	}
	return 0
}

func (m *IntFilter) GetIn() []int32 {
	if m != nil {
		return m.In
	}
	return nil
}

func (m *IntFilter) GetNotIn() []int32 {
	if m != nil {
		return m.NotIn
	}
	return nil
}

func (m *IntFilter) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*IntFilter)(nil), "intfilter.IntFilter")
}

func init() { proto.RegisterFile("intfilter/intfilter_.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xd0, 0xb1, 0x4b, 0xc4, 0x30,
	0x14, 0xc7, 0x71, 0xd2, 0x5e, 0xf5, 0x9a, 0x41, 0x24, 0x38, 0x3c, 0x9c, 0x8a, 0x53, 0x17, 0x2f,
	0x28, 0x88, 0xbb, 0x83, 0x70, 0x6b, 0x47, 0x17, 0xa9, 0x35, 0xbe, 0x06, 0x72, 0xef, 0x95, 0xe6,
	0xdd, 0xe0, 0x1f, 0xe7, 0xff, 0x26, 0x49, 0xa0, 0xb7, 0x7d, 0xdf, 0x8f, 0x0f, 0x04, 0xa2, 0xef,
	0x3d, 0xc9, 0x8f, 0x0f, 0xe2, 0x56, 0xbb, 0xd5, 0xe7, 0x61, 0x59, 0x59, 0xd8, 0xb4, 0xdb, 0xf2,
	0xf0, 0xa7, 0x74, 0x7b, 0x24, 0x79, 0xcf, 0x97, 0xb9, 0xd5, 0x75, 0x74, 0x02, 0xaa, 0x53, 0xfd,
	0x7e, 0x48, 0x69, 0x6e, 0x74, 0xe5, 0x23, 0x54, 0x9d, 0xea, 0x9b, 0xa1, 0xf2, 0x31, 0x09, 0x62,
	0x81, 0x3a, 0x0f, 0x29, 0x93, 0x08, 0x02, 0xbb, 0x22, 0x82, 0x24, 0x11, 0xc4, 0x41, 0x53, 0x44,
	0x10, 0x97, 0x04, 0x0a, 0x5c, 0x15, 0x81, 0x59, 0xa0, 0x38, 0xb8, 0x2e, 0x02, 0x8b, 0xf0, 0x04,
	0xfb, 0xae, 0xce, 0xaf, 0x90, 0xb9, 0xd3, 0x0d, 0xb1, 0x1c, 0x09, 0xda, 0x3c, 0x95, 0xc3, 0x18,
	0xbd, 0x9b, 0xc7, 0x38, 0x83, 0xee, 0x54, 0xdf, 0x0e, 0xb9, 0xdf, 0x5e, 0x3f, 0x5e, 0xd0, 0xcb,
	0x7c, 0xfe, 0x3a, 0x4c, 0x7c, 0xb2, 0xcf, 0x4f, 0x51, 0x3c, 0x5b, 0xe4, 0xc7, 0x25, 0x8c, 0xbf,
	0xb8, 0xf2, 0x99, 0xbe, 0x2d, 0xae, 0xcb, 0x64, 0xe3, 0x34, 0xbb, 0xd3, 0x78, 0xf9, 0x8a, 0xff,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x3e, 0xed, 0x39, 0x20, 0x01, 0x00, 0x00,
}
