// Code generated by protoc-gen-go. DO NOT EDIT.
// source: endpoint/endpoint_.proto

/*
Package endpoint is a generated protocol buffer package.

It is generated from these files:
	endpoint/endpoint_.proto

It has these top-level messages:
	Endpoint
*/
package endpoint

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import endpointkind "github.com/21stio/go-playground/grpc/schema/endpointkind"
import authenticatecredentialendpoint "github.com/21stio/go-playground/grpc/schema/authenticatecredentialendpoint"
import refreshtokenendpoint "github.com/21stio/go-playground/grpc/schema/refreshtokenendpoint"
import verifytokenendpoint "github.com/21stio/go-playground/grpc/schema/verifytokenendpoint"
import getcompaniesendpoint "github.com/21stio/go-playground/grpc/schema/getcompaniesendpoint"
import getcompanybyidendpoint "github.com/21stio/go-playground/grpc/schema/getcompanybyidendpoint"
import createcompaniesendpoint "github.com/21stio/go-playground/grpc/schema/createcompaniesendpoint"
import updatecompaniesendpoint "github.com/21stio/go-playground/grpc/schema/updatecompaniesendpoint"
import deletecompaniesendpoint "github.com/21stio/go-playground/grpc/schema/deletecompaniesendpoint"
import streamcompaniesendpoint "github.com/21stio/go-playground/grpc/schema/streamcompaniesendpoint"
import getjobsendpoint "github.com/21stio/go-playground/grpc/schema/getjobsendpoint"
import getjobbyidendpoint "github.com/21stio/go-playground/grpc/schema/getjobbyidendpoint"
import createjobsendpoint "github.com/21stio/go-playground/grpc/schema/createjobsendpoint"
import updatejobsendpoint "github.com/21stio/go-playground/grpc/schema/updatejobsendpoint"
import deletejobsendpoint "github.com/21stio/go-playground/grpc/schema/deletejobsendpoint"
import streamjobsendpoint "github.com/21stio/go-playground/grpc/schema/streamjobsendpoint"
import getjoblistbyidendpoint "github.com/21stio/go-playground/grpc/schema/getjoblistbyidendpoint"
import modifyjoblistendpoint "github.com/21stio/go-playground/grpc/schema/modifyjoblistendpoint"
import getlocationsendpoint "github.com/21stio/go-playground/grpc/schema/getlocationsendpoint"
import getlocationbyidendpoint "github.com/21stio/go-playground/grpc/schema/getlocationbyidendpoint"
import createlocationsendpoint "github.com/21stio/go-playground/grpc/schema/createlocationsendpoint"
import updatelocationsendpoint "github.com/21stio/go-playground/grpc/schema/updatelocationsendpoint"
import deletelocationsendpoint "github.com/21stio/go-playground/grpc/schema/deletelocationsendpoint"
import streamlocationsendpoint "github.com/21stio/go-playground/grpc/schema/streamlocationsendpoint"
import getproductsendpoint "github.com/21stio/go-playground/grpc/schema/getproductsendpoint"
import getproductbyidendpoint "github.com/21stio/go-playground/grpc/schema/getproductbyidendpoint"
import createproductsendpoint "github.com/21stio/go-playground/grpc/schema/createproductsendpoint"
import updateproductsendpoint "github.com/21stio/go-playground/grpc/schema/updateproductsendpoint"
import deleteproductsendpoint "github.com/21stio/go-playground/grpc/schema/deleteproductsendpoint"
import streamproductsendpoint "github.com/21stio/go-playground/grpc/schema/streamproductsendpoint"
import getproductlistbyidendpoint "github.com/21stio/go-playground/grpc/schema/getproductlistbyidendpoint"
import modifyproductlistendpoint "github.com/21stio/go-playground/grpc/schema/modifyproductlistendpoint"
import getsocialaccountsendpoint "github.com/21stio/go-playground/grpc/schema/getsocialaccountsendpoint"
import getsocialaccountbyidendpoint "github.com/21stio/go-playground/grpc/schema/getsocialaccountbyidendpoint"
import createsocialaccountsendpoint "github.com/21stio/go-playground/grpc/schema/createsocialaccountsendpoint"
import updatesocialaccountsendpoint "github.com/21stio/go-playground/grpc/schema/updatesocialaccountsendpoint"
import deletesocialaccountsendpoint "github.com/21stio/go-playground/grpc/schema/deletesocialaccountsendpoint"
import streamsocialaccountsendpoint "github.com/21stio/go-playground/grpc/schema/streamsocialaccountsendpoint"
import getsocialaccountlistbyidendpoint "github.com/21stio/go-playground/grpc/schema/getsocialaccountlistbyidendpoint"
import modifysocialaccountlistendpoint "github.com/21stio/go-playground/grpc/schema/modifysocialaccountlistendpoint"
import getpersonsendpoint "github.com/21stio/go-playground/grpc/schema/getpersonsendpoint"
import getpersonbyidendpoint "github.com/21stio/go-playground/grpc/schema/getpersonbyidendpoint"
import createpersonsendpoint "github.com/21stio/go-playground/grpc/schema/createpersonsendpoint"
import updatepersonsendpoint "github.com/21stio/go-playground/grpc/schema/updatepersonsendpoint"
import deletepersonsendpoint "github.com/21stio/go-playground/grpc/schema/deletepersonsendpoint"
import streampersonsendpoint "github.com/21stio/go-playground/grpc/schema/streampersonsendpoint"
import getpersonlistbyidendpoint "github.com/21stio/go-playground/grpc/schema/getpersonlistbyidendpoint"
import modifypersonlistendpoint "github.com/21stio/go-playground/grpc/schema/modifypersonlistendpoint"
import getpostsendpoint "github.com/21stio/go-playground/grpc/schema/getpostsendpoint"
import getpostbyidendpoint "github.com/21stio/go-playground/grpc/schema/getpostbyidendpoint"
import createpostsendpoint "github.com/21stio/go-playground/grpc/schema/createpostsendpoint"
import updatepostsendpoint "github.com/21stio/go-playground/grpc/schema/updatepostsendpoint"
import deletepostsendpoint "github.com/21stio/go-playground/grpc/schema/deletepostsendpoint"
import streampostsendpoint "github.com/21stio/go-playground/grpc/schema/streampostsendpoint"
import getpostlistbyidendpoint "github.com/21stio/go-playground/grpc/schema/getpostlistbyidendpoint"
import modifypostlistendpoint "github.com/21stio/go-playground/grpc/schema/modifypostlistendpoint"
import getfeedsendpoint "github.com/21stio/go-playground/grpc/schema/getfeedsendpoint"
import getfeedbyidendpoint "github.com/21stio/go-playground/grpc/schema/getfeedbyidendpoint"
import createfeedsendpoint "github.com/21stio/go-playground/grpc/schema/createfeedsendpoint"
import updatefeedsendpoint "github.com/21stio/go-playground/grpc/schema/updatefeedsendpoint"
import deletefeedsendpoint "github.com/21stio/go-playground/grpc/schema/deletefeedsendpoint"
import streamfeedsendpoint "github.com/21stio/go-playground/grpc/schema/streamfeedsendpoint"
import getspecdescriptionsendpoint "github.com/21stio/go-playground/grpc/schema/getspecdescriptionsendpoint"
import getspecdescriptionbyidendpoint "github.com/21stio/go-playground/grpc/schema/getspecdescriptionbyidendpoint"
import createspecdescriptionsendpoint "github.com/21stio/go-playground/grpc/schema/createspecdescriptionsendpoint"
import updatespecdescriptionsendpoint "github.com/21stio/go-playground/grpc/schema/updatespecdescriptionsendpoint"
import deletespecdescriptionsendpoint "github.com/21stio/go-playground/grpc/schema/deletespecdescriptionsendpoint"
import streamspecdescriptionsendpoint "github.com/21stio/go-playground/grpc/schema/streamspecdescriptionsendpoint"
import getwhateversendpoint "github.com/21stio/go-playground/grpc/schema/getwhateversendpoint"
import getwhateverbyidendpoint "github.com/21stio/go-playground/grpc/schema/getwhateverbyidendpoint"
import createwhateversendpoint "github.com/21stio/go-playground/grpc/schema/createwhateversendpoint"
import updatewhateversendpoint "github.com/21stio/go-playground/grpc/schema/updatewhateversendpoint"
import deletewhateversendpoint "github.com/21stio/go-playground/grpc/schema/deletewhateversendpoint"
import streamwhateversendpoint "github.com/21stio/go-playground/grpc/schema/streamwhateversendpoint"
import getwhateverlistbyidendpoint "github.com/21stio/go-playground/grpc/schema/getwhateverlistbyidendpoint"
import modifywhateverlistendpoint "github.com/21stio/go-playground/grpc/schema/modifywhateverlistendpoint"
import getservicesendpoint "github.com/21stio/go-playground/grpc/schema/getservicesendpoint"
import getservicebyidendpoint "github.com/21stio/go-playground/grpc/schema/getservicebyidendpoint"
import createservicesendpoint "github.com/21stio/go-playground/grpc/schema/createservicesendpoint"
import updateservicesendpoint "github.com/21stio/go-playground/grpc/schema/updateservicesendpoint"
import deleteservicesendpoint "github.com/21stio/go-playground/grpc/schema/deleteservicesendpoint"
import streamservicesendpoint "github.com/21stio/go-playground/grpc/schema/streamservicesendpoint"
import getservicelistbyidendpoint "github.com/21stio/go-playground/grpc/schema/getservicelistbyidendpoint"
import modifyservicelistendpoint "github.com/21stio/go-playground/grpc/schema/modifyservicelistendpoint"
import getsystemaccountsendpoint "github.com/21stio/go-playground/grpc/schema/getsystemaccountsendpoint"
import getsystemaccountbyidendpoint "github.com/21stio/go-playground/grpc/schema/getsystemaccountbyidendpoint"
import createsystemaccountsendpoint "github.com/21stio/go-playground/grpc/schema/createsystemaccountsendpoint"
import updatesystemaccountsendpoint "github.com/21stio/go-playground/grpc/schema/updatesystemaccountsendpoint"
import deletesystemaccountsendpoint "github.com/21stio/go-playground/grpc/schema/deletesystemaccountsendpoint"
import streamsystemaccountsendpoint "github.com/21stio/go-playground/grpc/schema/streamsystemaccountsendpoint"
import passurlendpoint "github.com/21stio/go-playground/grpc/schema/passurlendpoint"
import passvideoendpoint "github.com/21stio/go-playground/grpc/schema/passvideoendpoint"
import passcreatecompaniesrequestendpoint "github.com/21stio/go-playground/grpc/schema/passcreatecompaniesrequestendpoint"
import passupdatecompaniesrequestendpoint "github.com/21stio/go-playground/grpc/schema/passupdatecompaniesrequestendpoint"
import passdeletecompaniesrequestendpoint "github.com/21stio/go-playground/grpc/schema/passdeletecompaniesrequestendpoint"
import passcreatejobsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passcreatejobsrequestendpoint"
import passupdatejobsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passupdatejobsrequestendpoint"
import passdeletejobsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passdeletejobsrequestendpoint"
import passcreatelocationsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passcreatelocationsrequestendpoint"
import passupdatelocationsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passupdatelocationsrequestendpoint"
import passdeletelocationsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passdeletelocationsrequestendpoint"
import passcreateproductsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passcreateproductsrequestendpoint"
import passupdateproductsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passupdateproductsrequestendpoint"
import passdeleteproductsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passdeleteproductsrequestendpoint"
import passcreatesocialaccountsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passcreatesocialaccountsrequestendpoint"
import passupdatesocialaccountsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passupdatesocialaccountsrequestendpoint"
import passdeletesocialaccountsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passdeletesocialaccountsrequestendpoint"
import passcreatepersonsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passcreatepersonsrequestendpoint"
import passupdatepersonsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passupdatepersonsrequestendpoint"
import passdeletepersonsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passdeletepersonsrequestendpoint"
import passcreatepostsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passcreatepostsrequestendpoint"
import passupdatepostsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passupdatepostsrequestendpoint"
import passdeletepostsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passdeletepostsrequestendpoint"
import passcreatefeedsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passcreatefeedsrequestendpoint"
import passupdatefeedsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passupdatefeedsrequestendpoint"
import passdeletefeedsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passdeletefeedsrequestendpoint"
import passcreatespecdescriptionsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passcreatespecdescriptionsrequestendpoint"
import passupdatespecdescriptionsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passupdatespecdescriptionsrequestendpoint"
import passdeletespecdescriptionsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passdeletespecdescriptionsrequestendpoint"
import passcreatewhateversrequestendpoint "github.com/21stio/go-playground/grpc/schema/passcreatewhateversrequestendpoint"
import passupdatewhateversrequestendpoint "github.com/21stio/go-playground/grpc/schema/passupdatewhateversrequestendpoint"
import passdeletewhateversrequestendpoint "github.com/21stio/go-playground/grpc/schema/passdeletewhateversrequestendpoint"
import passcreateservicesrequestendpoint "github.com/21stio/go-playground/grpc/schema/passcreateservicesrequestendpoint"
import passupdateservicesrequestendpoint "github.com/21stio/go-playground/grpc/schema/passupdateservicesrequestendpoint"
import passdeleteservicesrequestendpoint "github.com/21stio/go-playground/grpc/schema/passdeleteservicesrequestendpoint"
import passcreatesystemaccountsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passcreatesystemaccountsrequestendpoint"
import passupdatesystemaccountsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passupdatesystemaccountsrequestendpoint"
import passdeletesystemaccountsrequestendpoint "github.com/21stio/go-playground/grpc/schema/passdeletesystemaccountsrequestendpoint"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Endpoint struct {
	Kind                                      *endpointkind.EndpointKind                                                           `protobuf:"varint,1,opt,name=kind,enum=endpointkind.EndpointKind" json:"kind,omitempty"`
	AuthenticateCredentialEndpoint            *authenticatecredentialendpoint.AuthenticateCredentialEndpoint                       `protobuf:"bytes,2,opt,name=authenticateCredentialEndpoint" json:"authenticateCredentialEndpoint,omitempty"`
	RefreshTokenEndpoint                      *refreshtokenendpoint.RefreshTokenEndpoint                                           `protobuf:"bytes,3,opt,name=refreshTokenEndpoint" json:"refreshTokenEndpoint,omitempty"`
	VerifyTokenEndpoint                       *verifytokenendpoint.VerifyTokenEndpoint                                             `protobuf:"bytes,4,opt,name=verifyTokenEndpoint" json:"verifyTokenEndpoint,omitempty"`
	GetCompaniesEndpoint                      *getcompaniesendpoint.GetCompaniesEndpoint                                           `protobuf:"bytes,5,opt,name=getCompaniesEndpoint" json:"getCompaniesEndpoint,omitempty"`
	GetCompanyByIdEndpoint                    *getcompanybyidendpoint.GetCompanyByIdEndpoint                                       `protobuf:"bytes,6,opt,name=getCompanyByIdEndpoint" json:"getCompanyByIdEndpoint,omitempty"`
	CreateCompaniesEndpoint                   *createcompaniesendpoint.CreateCompaniesEndpoint                                     `protobuf:"bytes,7,opt,name=createCompaniesEndpoint" json:"createCompaniesEndpoint,omitempty"`
	UpdateCompaniesEndpoint                   *updatecompaniesendpoint.UpdateCompaniesEndpoint                                     `protobuf:"bytes,8,opt,name=updateCompaniesEndpoint" json:"updateCompaniesEndpoint,omitempty"`
	DeleteCompaniesEndpoint                   *deletecompaniesendpoint.DeleteCompaniesEndpoint                                     `protobuf:"bytes,9,opt,name=deleteCompaniesEndpoint" json:"deleteCompaniesEndpoint,omitempty"`
	StreamCompaniesEndpoint                   *streamcompaniesendpoint.StreamCompaniesEndpoint                                     `protobuf:"bytes,10,opt,name=streamCompaniesEndpoint" json:"streamCompaniesEndpoint,omitempty"`
	GetJobsEndpoint                           *getjobsendpoint.GetJobsEndpoint                                                     `protobuf:"bytes,11,opt,name=getJobsEndpoint" json:"getJobsEndpoint,omitempty"`
	GetJobByIdEndpoint                        *getjobbyidendpoint.GetJobByIdEndpoint                                               `protobuf:"bytes,12,opt,name=getJobByIdEndpoint" json:"getJobByIdEndpoint,omitempty"`
	CreateJobsEndpoint                        *createjobsendpoint.CreateJobsEndpoint                                               `protobuf:"bytes,13,opt,name=createJobsEndpoint" json:"createJobsEndpoint,omitempty"`
	UpdateJobsEndpoint                        *updatejobsendpoint.UpdateJobsEndpoint                                               `protobuf:"bytes,14,opt,name=updateJobsEndpoint" json:"updateJobsEndpoint,omitempty"`
	DeleteJobsEndpoint                        *deletejobsendpoint.DeleteJobsEndpoint                                               `protobuf:"bytes,15,opt,name=deleteJobsEndpoint" json:"deleteJobsEndpoint,omitempty"`
	StreamJobsEndpoint                        *streamjobsendpoint.StreamJobsEndpoint                                               `protobuf:"bytes,16,opt,name=streamJobsEndpoint" json:"streamJobsEndpoint,omitempty"`
	GetJobListByIdEndpoint                    *getjoblistbyidendpoint.GetJobListByIdEndpoint                                       `protobuf:"bytes,17,opt,name=getJobListByIdEndpoint" json:"getJobListByIdEndpoint,omitempty"`
	ModifyJobListEndpoint                     *modifyjoblistendpoint.ModifyJobListEndpoint                                         `protobuf:"bytes,18,opt,name=modifyJobListEndpoint" json:"modifyJobListEndpoint,omitempty"`
	GetLocationsEndpoint                      *getlocationsendpoint.GetLocationsEndpoint                                           `protobuf:"bytes,19,opt,name=getLocationsEndpoint" json:"getLocationsEndpoint,omitempty"`
	GetLocationByIdEndpoint                   *getlocationbyidendpoint.GetLocationByIdEndpoint                                     `protobuf:"bytes,20,opt,name=getLocationByIdEndpoint" json:"getLocationByIdEndpoint,omitempty"`
	CreateLocationsEndpoint                   *createlocationsendpoint.CreateLocationsEndpoint                                     `protobuf:"bytes,21,opt,name=createLocationsEndpoint" json:"createLocationsEndpoint,omitempty"`
	UpdateLocationsEndpoint                   *updatelocationsendpoint.UpdateLocationsEndpoint                                     `protobuf:"bytes,22,opt,name=updateLocationsEndpoint" json:"updateLocationsEndpoint,omitempty"`
	DeleteLocationsEndpoint                   *deletelocationsendpoint.DeleteLocationsEndpoint                                     `protobuf:"bytes,23,opt,name=deleteLocationsEndpoint" json:"deleteLocationsEndpoint,omitempty"`
	StreamLocationsEndpoint                   *streamlocationsendpoint.StreamLocationsEndpoint                                     `protobuf:"bytes,24,opt,name=streamLocationsEndpoint" json:"streamLocationsEndpoint,omitempty"`
	GetProductsEndpoint                       *getproductsendpoint.GetProductsEndpoint                                             `protobuf:"bytes,25,opt,name=getProductsEndpoint" json:"getProductsEndpoint,omitempty"`
	GetProductByIdEndpoint                    *getproductbyidendpoint.GetProductByIdEndpoint                                       `protobuf:"bytes,26,opt,name=getProductByIdEndpoint" json:"getProductByIdEndpoint,omitempty"`
	CreateProductsEndpoint                    *createproductsendpoint.CreateProductsEndpoint                                       `protobuf:"bytes,27,opt,name=createProductsEndpoint" json:"createProductsEndpoint,omitempty"`
	UpdateProductsEndpoint                    *updateproductsendpoint.UpdateProductsEndpoint                                       `protobuf:"bytes,28,opt,name=updateProductsEndpoint" json:"updateProductsEndpoint,omitempty"`
	DeleteProductsEndpoint                    *deleteproductsendpoint.DeleteProductsEndpoint                                       `protobuf:"bytes,29,opt,name=deleteProductsEndpoint" json:"deleteProductsEndpoint,omitempty"`
	StreamProductsEndpoint                    *streamproductsendpoint.StreamProductsEndpoint                                       `protobuf:"bytes,30,opt,name=streamProductsEndpoint" json:"streamProductsEndpoint,omitempty"`
	GetProductListByIdEndpoint                *getproductlistbyidendpoint.GetProductListByIdEndpoint                               `protobuf:"bytes,31,opt,name=getProductListByIdEndpoint" json:"getProductListByIdEndpoint,omitempty"`
	ModifyProductListEndpoint                 *modifyproductlistendpoint.ModifyProductListEndpoint                                 `protobuf:"bytes,32,opt,name=modifyProductListEndpoint" json:"modifyProductListEndpoint,omitempty"`
	GetSocialAccountsEndpoint                 *getsocialaccountsendpoint.GetSocialAccountsEndpoint                                 `protobuf:"bytes,33,opt,name=getSocialAccountsEndpoint" json:"getSocialAccountsEndpoint,omitempty"`
	GetSocialAccountByIdEndpoint              *getsocialaccountbyidendpoint.GetSocialAccountByIdEndpoint                           `protobuf:"bytes,34,opt,name=getSocialAccountByIdEndpoint" json:"getSocialAccountByIdEndpoint,omitempty"`
	CreateSocialAccountsEndpoint              *createsocialaccountsendpoint.CreateSocialAccountsEndpoint                           `protobuf:"bytes,35,opt,name=createSocialAccountsEndpoint" json:"createSocialAccountsEndpoint,omitempty"`
	UpdateSocialAccountsEndpoint              *updatesocialaccountsendpoint.UpdateSocialAccountsEndpoint                           `protobuf:"bytes,36,opt,name=updateSocialAccountsEndpoint" json:"updateSocialAccountsEndpoint,omitempty"`
	DeleteSocialAccountsEndpoint              *deletesocialaccountsendpoint.DeleteSocialAccountsEndpoint                           `protobuf:"bytes,37,opt,name=deleteSocialAccountsEndpoint" json:"deleteSocialAccountsEndpoint,omitempty"`
	StreamSocialAccountsEndpoint              *streamsocialaccountsendpoint.StreamSocialAccountsEndpoint                           `protobuf:"bytes,38,opt,name=streamSocialAccountsEndpoint" json:"streamSocialAccountsEndpoint,omitempty"`
	GetSocialAccountListByIdEndpoint          *getsocialaccountlistbyidendpoint.GetSocialAccountListByIdEndpoint                   `protobuf:"bytes,39,opt,name=getSocialAccountListByIdEndpoint" json:"getSocialAccountListByIdEndpoint,omitempty"`
	ModifySocialAccountListEndpoint           *modifysocialaccountlistendpoint.ModifySocialAccountListEndpoint                     `protobuf:"bytes,40,opt,name=modifySocialAccountListEndpoint" json:"modifySocialAccountListEndpoint,omitempty"`
	GetPersonsEndpoint                        *getpersonsendpoint.GetPersonsEndpoint                                               `protobuf:"bytes,41,opt,name=getPersonsEndpoint" json:"getPersonsEndpoint,omitempty"`
	GetPersonByIdEndpoint                     *getpersonbyidendpoint.GetPersonByIdEndpoint                                         `protobuf:"bytes,42,opt,name=getPersonByIdEndpoint" json:"getPersonByIdEndpoint,omitempty"`
	CreatePersonsEndpoint                     *createpersonsendpoint.CreatePersonsEndpoint                                         `protobuf:"bytes,43,opt,name=createPersonsEndpoint" json:"createPersonsEndpoint,omitempty"`
	UpdatePersonsEndpoint                     *updatepersonsendpoint.UpdatePersonsEndpoint                                         `protobuf:"bytes,44,opt,name=updatePersonsEndpoint" json:"updatePersonsEndpoint,omitempty"`
	DeletePersonsEndpoint                     *deletepersonsendpoint.DeletePersonsEndpoint                                         `protobuf:"bytes,45,opt,name=deletePersonsEndpoint" json:"deletePersonsEndpoint,omitempty"`
	StreamPersonsEndpoint                     *streampersonsendpoint.StreamPersonsEndpoint                                         `protobuf:"bytes,46,opt,name=streamPersonsEndpoint" json:"streamPersonsEndpoint,omitempty"`
	GetPersonListByIdEndpoint                 *getpersonlistbyidendpoint.GetPersonListByIdEndpoint                                 `protobuf:"bytes,47,opt,name=getPersonListByIdEndpoint" json:"getPersonListByIdEndpoint,omitempty"`
	ModifyPersonListEndpoint                  *modifypersonlistendpoint.ModifyPersonListEndpoint                                   `protobuf:"bytes,48,opt,name=modifyPersonListEndpoint" json:"modifyPersonListEndpoint,omitempty"`
	GetPostsEndpoint                          *getpostsendpoint.GetPostsEndpoint                                                   `protobuf:"bytes,49,opt,name=getPostsEndpoint" json:"getPostsEndpoint,omitempty"`
	GetPostByIdEndpoint                       *getpostbyidendpoint.GetPostByIdEndpoint                                             `protobuf:"bytes,50,opt,name=getPostByIdEndpoint" json:"getPostByIdEndpoint,omitempty"`
	CreatePostsEndpoint                       *createpostsendpoint.CreatePostsEndpoint                                             `protobuf:"bytes,51,opt,name=createPostsEndpoint" json:"createPostsEndpoint,omitempty"`
	UpdatePostsEndpoint                       *updatepostsendpoint.UpdatePostsEndpoint                                             `protobuf:"bytes,52,opt,name=updatePostsEndpoint" json:"updatePostsEndpoint,omitempty"`
	DeletePostsEndpoint                       *deletepostsendpoint.DeletePostsEndpoint                                             `protobuf:"bytes,53,opt,name=deletePostsEndpoint" json:"deletePostsEndpoint,omitempty"`
	StreamPostsEndpoint                       *streampostsendpoint.StreamPostsEndpoint                                             `protobuf:"bytes,54,opt,name=streamPostsEndpoint" json:"streamPostsEndpoint,omitempty"`
	GetPostListByIdEndpoint                   *getpostlistbyidendpoint.GetPostListByIdEndpoint                                     `protobuf:"bytes,55,opt,name=getPostListByIdEndpoint" json:"getPostListByIdEndpoint,omitempty"`
	ModifyPostListEndpoint                    *modifypostlistendpoint.ModifyPostListEndpoint                                       `protobuf:"bytes,56,opt,name=modifyPostListEndpoint" json:"modifyPostListEndpoint,omitempty"`
	GetFeedsEndpoint                          *getfeedsendpoint.GetFeedsEndpoint                                                   `protobuf:"bytes,57,opt,name=getFeedsEndpoint" json:"getFeedsEndpoint,omitempty"`
	GetFeedByIdEndpoint                       *getfeedbyidendpoint.GetFeedByIdEndpoint                                             `protobuf:"bytes,58,opt,name=getFeedByIdEndpoint" json:"getFeedByIdEndpoint,omitempty"`
	CreateFeedsEndpoint                       *createfeedsendpoint.CreateFeedsEndpoint                                             `protobuf:"bytes,59,opt,name=createFeedsEndpoint" json:"createFeedsEndpoint,omitempty"`
	UpdateFeedsEndpoint                       *updatefeedsendpoint.UpdateFeedsEndpoint                                             `protobuf:"bytes,60,opt,name=updateFeedsEndpoint" json:"updateFeedsEndpoint,omitempty"`
	DeleteFeedsEndpoint                       *deletefeedsendpoint.DeleteFeedsEndpoint                                             `protobuf:"bytes,61,opt,name=deleteFeedsEndpoint" json:"deleteFeedsEndpoint,omitempty"`
	StreamFeedsEndpoint                       *streamfeedsendpoint.StreamFeedsEndpoint                                             `protobuf:"bytes,62,opt,name=streamFeedsEndpoint" json:"streamFeedsEndpoint,omitempty"`
	GetSpecDescriptionsEndpoint               *getspecdescriptionsendpoint.GetSpecDescriptionsEndpoint                             `protobuf:"bytes,63,opt,name=getSpecDescriptionsEndpoint" json:"getSpecDescriptionsEndpoint,omitempty"`
	GetSpecDescriptionByIdEndpoint            *getspecdescriptionbyidendpoint.GetSpecDescriptionByIdEndpoint                       `protobuf:"bytes,64,opt,name=getSpecDescriptionByIdEndpoint" json:"getSpecDescriptionByIdEndpoint,omitempty"`
	CreateSpecDescriptionsEndpoint            *createspecdescriptionsendpoint.CreateSpecDescriptionsEndpoint                       `protobuf:"bytes,65,opt,name=createSpecDescriptionsEndpoint" json:"createSpecDescriptionsEndpoint,omitempty"`
	UpdateSpecDescriptionsEndpoint            *updatespecdescriptionsendpoint.UpdateSpecDescriptionsEndpoint                       `protobuf:"bytes,66,opt,name=updateSpecDescriptionsEndpoint" json:"updateSpecDescriptionsEndpoint,omitempty"`
	DeleteSpecDescriptionsEndpoint            *deletespecdescriptionsendpoint.DeleteSpecDescriptionsEndpoint                       `protobuf:"bytes,67,opt,name=deleteSpecDescriptionsEndpoint" json:"deleteSpecDescriptionsEndpoint,omitempty"`
	StreamSpecDescriptionsEndpoint            *streamspecdescriptionsendpoint.StreamSpecDescriptionsEndpoint                       `protobuf:"bytes,68,opt,name=streamSpecDescriptionsEndpoint" json:"streamSpecDescriptionsEndpoint,omitempty"`
	GetWhateversEndpoint                      *getwhateversendpoint.GetWhateversEndpoint                                           `protobuf:"bytes,69,opt,name=getWhateversEndpoint" json:"getWhateversEndpoint,omitempty"`
	GetWhateverByIdEndpoint                   *getwhateverbyidendpoint.GetWhateverByIdEndpoint                                     `protobuf:"bytes,70,opt,name=getWhateverByIdEndpoint" json:"getWhateverByIdEndpoint,omitempty"`
	CreateWhateversEndpoint                   *createwhateversendpoint.CreateWhateversEndpoint                                     `protobuf:"bytes,71,opt,name=createWhateversEndpoint" json:"createWhateversEndpoint,omitempty"`
	UpdateWhateversEndpoint                   *updatewhateversendpoint.UpdateWhateversEndpoint                                     `protobuf:"bytes,72,opt,name=updateWhateversEndpoint" json:"updateWhateversEndpoint,omitempty"`
	DeleteWhateversEndpoint                   *deletewhateversendpoint.DeleteWhateversEndpoint                                     `protobuf:"bytes,73,opt,name=deleteWhateversEndpoint" json:"deleteWhateversEndpoint,omitempty"`
	StreamWhateversEndpoint                   *streamwhateversendpoint.StreamWhateversEndpoint                                     `protobuf:"bytes,74,opt,name=streamWhateversEndpoint" json:"streamWhateversEndpoint,omitempty"`
	GetWhateverListByIdEndpoint               *getwhateverlistbyidendpoint.GetWhateverListByIdEndpoint                             `protobuf:"bytes,75,opt,name=getWhateverListByIdEndpoint" json:"getWhateverListByIdEndpoint,omitempty"`
	ModifyWhateverListEndpoint                *modifywhateverlistendpoint.ModifyWhateverListEndpoint                               `protobuf:"bytes,76,opt,name=modifyWhateverListEndpoint" json:"modifyWhateverListEndpoint,omitempty"`
	GetServicesEndpoint                       *getservicesendpoint.GetServicesEndpoint                                             `protobuf:"bytes,77,opt,name=getServicesEndpoint" json:"getServicesEndpoint,omitempty"`
	GetServiceByIdEndpoint                    *getservicebyidendpoint.GetServiceByIdEndpoint                                       `protobuf:"bytes,78,opt,name=getServiceByIdEndpoint" json:"getServiceByIdEndpoint,omitempty"`
	CreateServicesEndpoint                    *createservicesendpoint.CreateServicesEndpoint                                       `protobuf:"bytes,79,opt,name=createServicesEndpoint" json:"createServicesEndpoint,omitempty"`
	UpdateServicesEndpoint                    *updateservicesendpoint.UpdateServicesEndpoint                                       `protobuf:"bytes,80,opt,name=updateServicesEndpoint" json:"updateServicesEndpoint,omitempty"`
	DeleteServicesEndpoint                    *deleteservicesendpoint.DeleteServicesEndpoint                                       `protobuf:"bytes,81,opt,name=deleteServicesEndpoint" json:"deleteServicesEndpoint,omitempty"`
	StreamServicesEndpoint                    *streamservicesendpoint.StreamServicesEndpoint                                       `protobuf:"bytes,82,opt,name=streamServicesEndpoint" json:"streamServicesEndpoint,omitempty"`
	GetServiceListByIdEndpoint                *getservicelistbyidendpoint.GetServiceListByIdEndpoint                               `protobuf:"bytes,83,opt,name=getServiceListByIdEndpoint" json:"getServiceListByIdEndpoint,omitempty"`
	ModifyServiceListEndpoint                 *modifyservicelistendpoint.ModifyServiceListEndpoint                                 `protobuf:"bytes,84,opt,name=modifyServiceListEndpoint" json:"modifyServiceListEndpoint,omitempty"`
	GetSystemAccountsEndpoint                 *getsystemaccountsendpoint.GetSystemAccountsEndpoint                                 `protobuf:"bytes,85,opt,name=getSystemAccountsEndpoint" json:"getSystemAccountsEndpoint,omitempty"`
	GetSystemAccountByIdEndpoint              *getsystemaccountbyidendpoint.GetSystemAccountByIdEndpoint                           `protobuf:"bytes,86,opt,name=getSystemAccountByIdEndpoint" json:"getSystemAccountByIdEndpoint,omitempty"`
	CreateSystemAccountsEndpoint              *createsystemaccountsendpoint.CreateSystemAccountsEndpoint                           `protobuf:"bytes,87,opt,name=createSystemAccountsEndpoint" json:"createSystemAccountsEndpoint,omitempty"`
	UpdateSystemAccountsEndpoint              *updatesystemaccountsendpoint.UpdateSystemAccountsEndpoint                           `protobuf:"bytes,88,opt,name=updateSystemAccountsEndpoint" json:"updateSystemAccountsEndpoint,omitempty"`
	DeleteSystemAccountsEndpoint              *deletesystemaccountsendpoint.DeleteSystemAccountsEndpoint                           `protobuf:"bytes,89,opt,name=deleteSystemAccountsEndpoint" json:"deleteSystemAccountsEndpoint,omitempty"`
	StreamSystemAccountsEndpoint              *streamsystemaccountsendpoint.StreamSystemAccountsEndpoint                           `protobuf:"bytes,90,opt,name=streamSystemAccountsEndpoint" json:"streamSystemAccountsEndpoint,omitempty"`
	PassUrlEndpoint                           *passurlendpoint.PassUrlEndpoint                                                     `protobuf:"bytes,91,opt,name=passUrlEndpoint" json:"passUrlEndpoint,omitempty"`
	PassVideoEndpoint                         *passvideoendpoint.PassVideoEndpoint                                                 `protobuf:"bytes,92,opt,name=passVideoEndpoint" json:"passVideoEndpoint,omitempty"`
	PassCreateCompaniesRequestEndpoint        *passcreatecompaniesrequestendpoint.PassCreateCompaniesRequestEndpoint               `protobuf:"bytes,93,opt,name=passCreateCompaniesRequestEndpoint" json:"passCreateCompaniesRequestEndpoint,omitempty"`
	PassUpdateCompaniesRequestEndpoint        *passupdatecompaniesrequestendpoint.PassUpdateCompaniesRequestEndpoint               `protobuf:"bytes,94,opt,name=passUpdateCompaniesRequestEndpoint" json:"passUpdateCompaniesRequestEndpoint,omitempty"`
	PassDeleteCompaniesRequestEndpoint        *passdeletecompaniesrequestendpoint.PassDeleteCompaniesRequestEndpoint               `protobuf:"bytes,95,opt,name=passDeleteCompaniesRequestEndpoint" json:"passDeleteCompaniesRequestEndpoint,omitempty"`
	PassCreateJobsRequestEndpoint             *passcreatejobsrequestendpoint.PassCreateJobsRequestEndpoint                         `protobuf:"bytes,96,opt,name=passCreateJobsRequestEndpoint" json:"passCreateJobsRequestEndpoint,omitempty"`
	PassUpdateJobsRequestEndpoint             *passupdatejobsrequestendpoint.PassUpdateJobsRequestEndpoint                         `protobuf:"bytes,97,opt,name=passUpdateJobsRequestEndpoint" json:"passUpdateJobsRequestEndpoint,omitempty"`
	PassDeleteJobsRequestEndpoint             *passdeletejobsrequestendpoint.PassDeleteJobsRequestEndpoint                         `protobuf:"bytes,98,opt,name=passDeleteJobsRequestEndpoint" json:"passDeleteJobsRequestEndpoint,omitempty"`
	PassCreateLocationsRequestEndpoint        *passcreatelocationsrequestendpoint.PassCreateLocationsRequestEndpoint               `protobuf:"bytes,99,opt,name=passCreateLocationsRequestEndpoint" json:"passCreateLocationsRequestEndpoint,omitempty"`
	PassUpdateLocationsRequestEndpoint        *passupdatelocationsrequestendpoint.PassUpdateLocationsRequestEndpoint               `protobuf:"bytes,100,opt,name=passUpdateLocationsRequestEndpoint" json:"passUpdateLocationsRequestEndpoint,omitempty"`
	PassDeleteLocationsRequestEndpoint        *passdeletelocationsrequestendpoint.PassDeleteLocationsRequestEndpoint               `protobuf:"bytes,101,opt,name=passDeleteLocationsRequestEndpoint" json:"passDeleteLocationsRequestEndpoint,omitempty"`
	PassCreateProductsRequestEndpoint         *passcreateproductsrequestendpoint.PassCreateProductsRequestEndpoint                 `protobuf:"bytes,102,opt,name=passCreateProductsRequestEndpoint" json:"passCreateProductsRequestEndpoint,omitempty"`
	PassUpdateProductsRequestEndpoint         *passupdateproductsrequestendpoint.PassUpdateProductsRequestEndpoint                 `protobuf:"bytes,103,opt,name=passUpdateProductsRequestEndpoint" json:"passUpdateProductsRequestEndpoint,omitempty"`
	PassDeleteProductsRequestEndpoint         *passdeleteproductsrequestendpoint.PassDeleteProductsRequestEndpoint                 `protobuf:"bytes,104,opt,name=passDeleteProductsRequestEndpoint" json:"passDeleteProductsRequestEndpoint,omitempty"`
	PassCreateSocialAccountsRequestEndpoint   *passcreatesocialaccountsrequestendpoint.PassCreateSocialAccountsRequestEndpoint     `protobuf:"bytes,105,opt,name=passCreateSocialAccountsRequestEndpoint" json:"passCreateSocialAccountsRequestEndpoint,omitempty"`
	PassUpdateSocialAccountsRequestEndpoint   *passupdatesocialaccountsrequestendpoint.PassUpdateSocialAccountsRequestEndpoint     `protobuf:"bytes,106,opt,name=passUpdateSocialAccountsRequestEndpoint" json:"passUpdateSocialAccountsRequestEndpoint,omitempty"`
	PassDeleteSocialAccountsRequestEndpoint   *passdeletesocialaccountsrequestendpoint.PassDeleteSocialAccountsRequestEndpoint     `protobuf:"bytes,107,opt,name=passDeleteSocialAccountsRequestEndpoint" json:"passDeleteSocialAccountsRequestEndpoint,omitempty"`
	PassCreatePersonsRequestEndpoint          *passcreatepersonsrequestendpoint.PassCreatePersonsRequestEndpoint                   `protobuf:"bytes,108,opt,name=passCreatePersonsRequestEndpoint" json:"passCreatePersonsRequestEndpoint,omitempty"`
	PassUpdatePersonsRequestEndpoint          *passupdatepersonsrequestendpoint.PassUpdatePersonsRequestEndpoint                   `protobuf:"bytes,109,opt,name=passUpdatePersonsRequestEndpoint" json:"passUpdatePersonsRequestEndpoint,omitempty"`
	PassDeletePersonsRequestEndpoint          *passdeletepersonsrequestendpoint.PassDeletePersonsRequestEndpoint                   `protobuf:"bytes,110,opt,name=passDeletePersonsRequestEndpoint" json:"passDeletePersonsRequestEndpoint,omitempty"`
	PassCreatePostsRequestEndpoint            *passcreatepostsrequestendpoint.PassCreatePostsRequestEndpoint                       `protobuf:"bytes,111,opt,name=passCreatePostsRequestEndpoint" json:"passCreatePostsRequestEndpoint,omitempty"`
	PassUpdatePostsRequestEndpoint            *passupdatepostsrequestendpoint.PassUpdatePostsRequestEndpoint                       `protobuf:"bytes,112,opt,name=passUpdatePostsRequestEndpoint" json:"passUpdatePostsRequestEndpoint,omitempty"`
	PassDeletePostsRequestEndpoint            *passdeletepostsrequestendpoint.PassDeletePostsRequestEndpoint                       `protobuf:"bytes,113,opt,name=passDeletePostsRequestEndpoint" json:"passDeletePostsRequestEndpoint,omitempty"`
	PassCreateFeedsRequestEndpoint            *passcreatefeedsrequestendpoint.PassCreateFeedsRequestEndpoint                       `protobuf:"bytes,114,opt,name=passCreateFeedsRequestEndpoint" json:"passCreateFeedsRequestEndpoint,omitempty"`
	PassUpdateFeedsRequestEndpoint            *passupdatefeedsrequestendpoint.PassUpdateFeedsRequestEndpoint                       `protobuf:"bytes,115,opt,name=passUpdateFeedsRequestEndpoint" json:"passUpdateFeedsRequestEndpoint,omitempty"`
	PassDeleteFeedsRequestEndpoint            *passdeletefeedsrequestendpoint.PassDeleteFeedsRequestEndpoint                       `protobuf:"bytes,116,opt,name=passDeleteFeedsRequestEndpoint" json:"passDeleteFeedsRequestEndpoint,omitempty"`
	PassCreateSpecDescriptionsRequestEndpoint *passcreatespecdescriptionsrequestendpoint.PassCreateSpecDescriptionsRequestEndpoint `protobuf:"bytes,117,opt,name=passCreateSpecDescriptionsRequestEndpoint" json:"passCreateSpecDescriptionsRequestEndpoint,omitempty"`
	PassUpdateSpecDescriptionsRequestEndpoint *passupdatespecdescriptionsrequestendpoint.PassUpdateSpecDescriptionsRequestEndpoint `protobuf:"bytes,118,opt,name=passUpdateSpecDescriptionsRequestEndpoint" json:"passUpdateSpecDescriptionsRequestEndpoint,omitempty"`
	PassDeleteSpecDescriptionsRequestEndpoint *passdeletespecdescriptionsrequestendpoint.PassDeleteSpecDescriptionsRequestEndpoint `protobuf:"bytes,119,opt,name=passDeleteSpecDescriptionsRequestEndpoint" json:"passDeleteSpecDescriptionsRequestEndpoint,omitempty"`
	PassCreateWhateversRequestEndpoint        *passcreatewhateversrequestendpoint.PassCreateWhateversRequestEndpoint               `protobuf:"bytes,120,opt,name=passCreateWhateversRequestEndpoint" json:"passCreateWhateversRequestEndpoint,omitempty"`
	PassUpdateWhateversRequestEndpoint        *passupdatewhateversrequestendpoint.PassUpdateWhateversRequestEndpoint               `protobuf:"bytes,121,opt,name=passUpdateWhateversRequestEndpoint" json:"passUpdateWhateversRequestEndpoint,omitempty"`
	PassDeleteWhateversRequestEndpoint        *passdeletewhateversrequestendpoint.PassDeleteWhateversRequestEndpoint               `protobuf:"bytes,122,opt,name=passDeleteWhateversRequestEndpoint" json:"passDeleteWhateversRequestEndpoint,omitempty"`
	PassCreateServicesRequestEndpoint         *passcreateservicesrequestendpoint.PassCreateServicesRequestEndpoint                 `protobuf:"bytes,123,opt,name=passCreateServicesRequestEndpoint" json:"passCreateServicesRequestEndpoint,omitempty"`
	PassUpdateServicesRequestEndpoint         *passupdateservicesrequestendpoint.PassUpdateServicesRequestEndpoint                 `protobuf:"bytes,124,opt,name=passUpdateServicesRequestEndpoint" json:"passUpdateServicesRequestEndpoint,omitempty"`
	PassDeleteServicesRequestEndpoint         *passdeleteservicesrequestendpoint.PassDeleteServicesRequestEndpoint                 `protobuf:"bytes,125,opt,name=passDeleteServicesRequestEndpoint" json:"passDeleteServicesRequestEndpoint,omitempty"`
	PassCreateSystemAccountsRequestEndpoint   *passcreatesystemaccountsrequestendpoint.PassCreateSystemAccountsRequestEndpoint     `protobuf:"bytes,126,opt,name=passCreateSystemAccountsRequestEndpoint" json:"passCreateSystemAccountsRequestEndpoint,omitempty"`
	PassUpdateSystemAccountsRequestEndpoint   *passupdatesystemaccountsrequestendpoint.PassUpdateSystemAccountsRequestEndpoint     `protobuf:"bytes,127,opt,name=passUpdateSystemAccountsRequestEndpoint" json:"passUpdateSystemAccountsRequestEndpoint,omitempty"`
	PassDeleteSystemAccountsRequestEndpoint   *passdeletesystemaccountsrequestendpoint.PassDeleteSystemAccountsRequestEndpoint     `protobuf:"bytes,128,opt,name=passDeleteSystemAccountsRequestEndpoint" json:"passDeleteSystemAccountsRequestEndpoint,omitempty"`
	Hash                                      *string                                                                              `protobuf:"bytes,129,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized                          []byte                                                                               `json:"-"`
}

func (m *Endpoint) Reset()                    { *m = Endpoint{} }
func (m *Endpoint) String() string            { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()               {}
func (*Endpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Endpoint) GetKind() endpointkind.EndpointKind {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return endpointkind.EndpointKind_ENDPOINT_AUTHENTICATE_CREDENTIAL_ENDPOINT
}

func (m *Endpoint) GetAuthenticateCredentialEndpoint() *authenticatecredentialendpoint.AuthenticateCredentialEndpoint {
	if m != nil {
		return m.AuthenticateCredentialEndpoint
	}
	return nil
}

func (m *Endpoint) GetRefreshTokenEndpoint() *refreshtokenendpoint.RefreshTokenEndpoint {
	if m != nil {
		return m.RefreshTokenEndpoint
	}
	return nil
}

func (m *Endpoint) GetVerifyTokenEndpoint() *verifytokenendpoint.VerifyTokenEndpoint {
	if m != nil {
		return m.VerifyTokenEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetCompaniesEndpoint() *getcompaniesendpoint.GetCompaniesEndpoint {
	if m != nil {
		return m.GetCompaniesEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetCompanyByIdEndpoint() *getcompanybyidendpoint.GetCompanyByIdEndpoint {
	if m != nil {
		return m.GetCompanyByIdEndpoint
	}
	return nil
}

func (m *Endpoint) GetCreateCompaniesEndpoint() *createcompaniesendpoint.CreateCompaniesEndpoint {
	if m != nil {
		return m.CreateCompaniesEndpoint
	}
	return nil
}

func (m *Endpoint) GetUpdateCompaniesEndpoint() *updatecompaniesendpoint.UpdateCompaniesEndpoint {
	if m != nil {
		return m.UpdateCompaniesEndpoint
	}
	return nil
}

func (m *Endpoint) GetDeleteCompaniesEndpoint() *deletecompaniesendpoint.DeleteCompaniesEndpoint {
	if m != nil {
		return m.DeleteCompaniesEndpoint
	}
	return nil
}

func (m *Endpoint) GetStreamCompaniesEndpoint() *streamcompaniesendpoint.StreamCompaniesEndpoint {
	if m != nil {
		return m.StreamCompaniesEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetJobsEndpoint() *getjobsendpoint.GetJobsEndpoint {
	if m != nil {
		return m.GetJobsEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetJobByIdEndpoint() *getjobbyidendpoint.GetJobByIdEndpoint {
	if m != nil {
		return m.GetJobByIdEndpoint
	}
	return nil
}

func (m *Endpoint) GetCreateJobsEndpoint() *createjobsendpoint.CreateJobsEndpoint {
	if m != nil {
		return m.CreateJobsEndpoint
	}
	return nil
}

func (m *Endpoint) GetUpdateJobsEndpoint() *updatejobsendpoint.UpdateJobsEndpoint {
	if m != nil {
		return m.UpdateJobsEndpoint
	}
	return nil
}

func (m *Endpoint) GetDeleteJobsEndpoint() *deletejobsendpoint.DeleteJobsEndpoint {
	if m != nil {
		return m.DeleteJobsEndpoint
	}
	return nil
}

func (m *Endpoint) GetStreamJobsEndpoint() *streamjobsendpoint.StreamJobsEndpoint {
	if m != nil {
		return m.StreamJobsEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetJobListByIdEndpoint() *getjoblistbyidendpoint.GetJobListByIdEndpoint {
	if m != nil {
		return m.GetJobListByIdEndpoint
	}
	return nil
}

func (m *Endpoint) GetModifyJobListEndpoint() *modifyjoblistendpoint.ModifyJobListEndpoint {
	if m != nil {
		return m.ModifyJobListEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetLocationsEndpoint() *getlocationsendpoint.GetLocationsEndpoint {
	if m != nil {
		return m.GetLocationsEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetLocationByIdEndpoint() *getlocationbyidendpoint.GetLocationByIdEndpoint {
	if m != nil {
		return m.GetLocationByIdEndpoint
	}
	return nil
}

func (m *Endpoint) GetCreateLocationsEndpoint() *createlocationsendpoint.CreateLocationsEndpoint {
	if m != nil {
		return m.CreateLocationsEndpoint
	}
	return nil
}

func (m *Endpoint) GetUpdateLocationsEndpoint() *updatelocationsendpoint.UpdateLocationsEndpoint {
	if m != nil {
		return m.UpdateLocationsEndpoint
	}
	return nil
}

func (m *Endpoint) GetDeleteLocationsEndpoint() *deletelocationsendpoint.DeleteLocationsEndpoint {
	if m != nil {
		return m.DeleteLocationsEndpoint
	}
	return nil
}

func (m *Endpoint) GetStreamLocationsEndpoint() *streamlocationsendpoint.StreamLocationsEndpoint {
	if m != nil {
		return m.StreamLocationsEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetProductsEndpoint() *getproductsendpoint.GetProductsEndpoint {
	if m != nil {
		return m.GetProductsEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetProductByIdEndpoint() *getproductbyidendpoint.GetProductByIdEndpoint {
	if m != nil {
		return m.GetProductByIdEndpoint
	}
	return nil
}

func (m *Endpoint) GetCreateProductsEndpoint() *createproductsendpoint.CreateProductsEndpoint {
	if m != nil {
		return m.CreateProductsEndpoint
	}
	return nil
}

func (m *Endpoint) GetUpdateProductsEndpoint() *updateproductsendpoint.UpdateProductsEndpoint {
	if m != nil {
		return m.UpdateProductsEndpoint
	}
	return nil
}

func (m *Endpoint) GetDeleteProductsEndpoint() *deleteproductsendpoint.DeleteProductsEndpoint {
	if m != nil {
		return m.DeleteProductsEndpoint
	}
	return nil
}

func (m *Endpoint) GetStreamProductsEndpoint() *streamproductsendpoint.StreamProductsEndpoint {
	if m != nil {
		return m.StreamProductsEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetProductListByIdEndpoint() *getproductlistbyidendpoint.GetProductListByIdEndpoint {
	if m != nil {
		return m.GetProductListByIdEndpoint
	}
	return nil
}

func (m *Endpoint) GetModifyProductListEndpoint() *modifyproductlistendpoint.ModifyProductListEndpoint {
	if m != nil {
		return m.ModifyProductListEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetSocialAccountsEndpoint() *getsocialaccountsendpoint.GetSocialAccountsEndpoint {
	if m != nil {
		return m.GetSocialAccountsEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetSocialAccountByIdEndpoint() *getsocialaccountbyidendpoint.GetSocialAccountByIdEndpoint {
	if m != nil {
		return m.GetSocialAccountByIdEndpoint
	}
	return nil
}

func (m *Endpoint) GetCreateSocialAccountsEndpoint() *createsocialaccountsendpoint.CreateSocialAccountsEndpoint {
	if m != nil {
		return m.CreateSocialAccountsEndpoint
	}
	return nil
}

func (m *Endpoint) GetUpdateSocialAccountsEndpoint() *updatesocialaccountsendpoint.UpdateSocialAccountsEndpoint {
	if m != nil {
		return m.UpdateSocialAccountsEndpoint
	}
	return nil
}

func (m *Endpoint) GetDeleteSocialAccountsEndpoint() *deletesocialaccountsendpoint.DeleteSocialAccountsEndpoint {
	if m != nil {
		return m.DeleteSocialAccountsEndpoint
	}
	return nil
}

func (m *Endpoint) GetStreamSocialAccountsEndpoint() *streamsocialaccountsendpoint.StreamSocialAccountsEndpoint {
	if m != nil {
		return m.StreamSocialAccountsEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetSocialAccountListByIdEndpoint() *getsocialaccountlistbyidendpoint.GetSocialAccountListByIdEndpoint {
	if m != nil {
		return m.GetSocialAccountListByIdEndpoint
	}
	return nil
}

func (m *Endpoint) GetModifySocialAccountListEndpoint() *modifysocialaccountlistendpoint.ModifySocialAccountListEndpoint {
	if m != nil {
		return m.ModifySocialAccountListEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetPersonsEndpoint() *getpersonsendpoint.GetPersonsEndpoint {
	if m != nil {
		return m.GetPersonsEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetPersonByIdEndpoint() *getpersonbyidendpoint.GetPersonByIdEndpoint {
	if m != nil {
		return m.GetPersonByIdEndpoint
	}
	return nil
}

func (m *Endpoint) GetCreatePersonsEndpoint() *createpersonsendpoint.CreatePersonsEndpoint {
	if m != nil {
		return m.CreatePersonsEndpoint
	}
	return nil
}

func (m *Endpoint) GetUpdatePersonsEndpoint() *updatepersonsendpoint.UpdatePersonsEndpoint {
	if m != nil {
		return m.UpdatePersonsEndpoint
	}
	return nil
}

func (m *Endpoint) GetDeletePersonsEndpoint() *deletepersonsendpoint.DeletePersonsEndpoint {
	if m != nil {
		return m.DeletePersonsEndpoint
	}
	return nil
}

func (m *Endpoint) GetStreamPersonsEndpoint() *streampersonsendpoint.StreamPersonsEndpoint {
	if m != nil {
		return m.StreamPersonsEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetPersonListByIdEndpoint() *getpersonlistbyidendpoint.GetPersonListByIdEndpoint {
	if m != nil {
		return m.GetPersonListByIdEndpoint
	}
	return nil
}

func (m *Endpoint) GetModifyPersonListEndpoint() *modifypersonlistendpoint.ModifyPersonListEndpoint {
	if m != nil {
		return m.ModifyPersonListEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetPostsEndpoint() *getpostsendpoint.GetPostsEndpoint {
	if m != nil {
		return m.GetPostsEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetPostByIdEndpoint() *getpostbyidendpoint.GetPostByIdEndpoint {
	if m != nil {
		return m.GetPostByIdEndpoint
	}
	return nil
}

func (m *Endpoint) GetCreatePostsEndpoint() *createpostsendpoint.CreatePostsEndpoint {
	if m != nil {
		return m.CreatePostsEndpoint
	}
	return nil
}

func (m *Endpoint) GetUpdatePostsEndpoint() *updatepostsendpoint.UpdatePostsEndpoint {
	if m != nil {
		return m.UpdatePostsEndpoint
	}
	return nil
}

func (m *Endpoint) GetDeletePostsEndpoint() *deletepostsendpoint.DeletePostsEndpoint {
	if m != nil {
		return m.DeletePostsEndpoint
	}
	return nil
}

func (m *Endpoint) GetStreamPostsEndpoint() *streampostsendpoint.StreamPostsEndpoint {
	if m != nil {
		return m.StreamPostsEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetPostListByIdEndpoint() *getpostlistbyidendpoint.GetPostListByIdEndpoint {
	if m != nil {
		return m.GetPostListByIdEndpoint
	}
	return nil
}

func (m *Endpoint) GetModifyPostListEndpoint() *modifypostlistendpoint.ModifyPostListEndpoint {
	if m != nil {
		return m.ModifyPostListEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetFeedsEndpoint() *getfeedsendpoint.GetFeedsEndpoint {
	if m != nil {
		return m.GetFeedsEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetFeedByIdEndpoint() *getfeedbyidendpoint.GetFeedByIdEndpoint {
	if m != nil {
		return m.GetFeedByIdEndpoint
	}
	return nil
}

func (m *Endpoint) GetCreateFeedsEndpoint() *createfeedsendpoint.CreateFeedsEndpoint {
	if m != nil {
		return m.CreateFeedsEndpoint
	}
	return nil
}

func (m *Endpoint) GetUpdateFeedsEndpoint() *updatefeedsendpoint.UpdateFeedsEndpoint {
	if m != nil {
		return m.UpdateFeedsEndpoint
	}
	return nil
}

func (m *Endpoint) GetDeleteFeedsEndpoint() *deletefeedsendpoint.DeleteFeedsEndpoint {
	if m != nil {
		return m.DeleteFeedsEndpoint
	}
	return nil
}

func (m *Endpoint) GetStreamFeedsEndpoint() *streamfeedsendpoint.StreamFeedsEndpoint {
	if m != nil {
		return m.StreamFeedsEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetSpecDescriptionsEndpoint() *getspecdescriptionsendpoint.GetSpecDescriptionsEndpoint {
	if m != nil {
		return m.GetSpecDescriptionsEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetSpecDescriptionByIdEndpoint() *getspecdescriptionbyidendpoint.GetSpecDescriptionByIdEndpoint {
	if m != nil {
		return m.GetSpecDescriptionByIdEndpoint
	}
	return nil
}

func (m *Endpoint) GetCreateSpecDescriptionsEndpoint() *createspecdescriptionsendpoint.CreateSpecDescriptionsEndpoint {
	if m != nil {
		return m.CreateSpecDescriptionsEndpoint
	}
	return nil
}

func (m *Endpoint) GetUpdateSpecDescriptionsEndpoint() *updatespecdescriptionsendpoint.UpdateSpecDescriptionsEndpoint {
	if m != nil {
		return m.UpdateSpecDescriptionsEndpoint
	}
	return nil
}

func (m *Endpoint) GetDeleteSpecDescriptionsEndpoint() *deletespecdescriptionsendpoint.DeleteSpecDescriptionsEndpoint {
	if m != nil {
		return m.DeleteSpecDescriptionsEndpoint
	}
	return nil
}

func (m *Endpoint) GetStreamSpecDescriptionsEndpoint() *streamspecdescriptionsendpoint.StreamSpecDescriptionsEndpoint {
	if m != nil {
		return m.StreamSpecDescriptionsEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetWhateversEndpoint() *getwhateversendpoint.GetWhateversEndpoint {
	if m != nil {
		return m.GetWhateversEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetWhateverByIdEndpoint() *getwhateverbyidendpoint.GetWhateverByIdEndpoint {
	if m != nil {
		return m.GetWhateverByIdEndpoint
	}
	return nil
}

func (m *Endpoint) GetCreateWhateversEndpoint() *createwhateversendpoint.CreateWhateversEndpoint {
	if m != nil {
		return m.CreateWhateversEndpoint
	}
	return nil
}

func (m *Endpoint) GetUpdateWhateversEndpoint() *updatewhateversendpoint.UpdateWhateversEndpoint {
	if m != nil {
		return m.UpdateWhateversEndpoint
	}
	return nil
}

func (m *Endpoint) GetDeleteWhateversEndpoint() *deletewhateversendpoint.DeleteWhateversEndpoint {
	if m != nil {
		return m.DeleteWhateversEndpoint
	}
	return nil
}

func (m *Endpoint) GetStreamWhateversEndpoint() *streamwhateversendpoint.StreamWhateversEndpoint {
	if m != nil {
		return m.StreamWhateversEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetWhateverListByIdEndpoint() *getwhateverlistbyidendpoint.GetWhateverListByIdEndpoint {
	if m != nil {
		return m.GetWhateverListByIdEndpoint
	}
	return nil
}

func (m *Endpoint) GetModifyWhateverListEndpoint() *modifywhateverlistendpoint.ModifyWhateverListEndpoint {
	if m != nil {
		return m.ModifyWhateverListEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetServicesEndpoint() *getservicesendpoint.GetServicesEndpoint {
	if m != nil {
		return m.GetServicesEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetServiceByIdEndpoint() *getservicebyidendpoint.GetServiceByIdEndpoint {
	if m != nil {
		return m.GetServiceByIdEndpoint
	}
	return nil
}

func (m *Endpoint) GetCreateServicesEndpoint() *createservicesendpoint.CreateServicesEndpoint {
	if m != nil {
		return m.CreateServicesEndpoint
	}
	return nil
}

func (m *Endpoint) GetUpdateServicesEndpoint() *updateservicesendpoint.UpdateServicesEndpoint {
	if m != nil {
		return m.UpdateServicesEndpoint
	}
	return nil
}

func (m *Endpoint) GetDeleteServicesEndpoint() *deleteservicesendpoint.DeleteServicesEndpoint {
	if m != nil {
		return m.DeleteServicesEndpoint
	}
	return nil
}

func (m *Endpoint) GetStreamServicesEndpoint() *streamservicesendpoint.StreamServicesEndpoint {
	if m != nil {
		return m.StreamServicesEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetServiceListByIdEndpoint() *getservicelistbyidendpoint.GetServiceListByIdEndpoint {
	if m != nil {
		return m.GetServiceListByIdEndpoint
	}
	return nil
}

func (m *Endpoint) GetModifyServiceListEndpoint() *modifyservicelistendpoint.ModifyServiceListEndpoint {
	if m != nil {
		return m.ModifyServiceListEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetSystemAccountsEndpoint() *getsystemaccountsendpoint.GetSystemAccountsEndpoint {
	if m != nil {
		return m.GetSystemAccountsEndpoint
	}
	return nil
}

func (m *Endpoint) GetGetSystemAccountByIdEndpoint() *getsystemaccountbyidendpoint.GetSystemAccountByIdEndpoint {
	if m != nil {
		return m.GetSystemAccountByIdEndpoint
	}
	return nil
}

func (m *Endpoint) GetCreateSystemAccountsEndpoint() *createsystemaccountsendpoint.CreateSystemAccountsEndpoint {
	if m != nil {
		return m.CreateSystemAccountsEndpoint
	}
	return nil
}

func (m *Endpoint) GetUpdateSystemAccountsEndpoint() *updatesystemaccountsendpoint.UpdateSystemAccountsEndpoint {
	if m != nil {
		return m.UpdateSystemAccountsEndpoint
	}
	return nil
}

func (m *Endpoint) GetDeleteSystemAccountsEndpoint() *deletesystemaccountsendpoint.DeleteSystemAccountsEndpoint {
	if m != nil {
		return m.DeleteSystemAccountsEndpoint
	}
	return nil
}

func (m *Endpoint) GetStreamSystemAccountsEndpoint() *streamsystemaccountsendpoint.StreamSystemAccountsEndpoint {
	if m != nil {
		return m.StreamSystemAccountsEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassUrlEndpoint() *passurlendpoint.PassUrlEndpoint {
	if m != nil {
		return m.PassUrlEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassVideoEndpoint() *passvideoendpoint.PassVideoEndpoint {
	if m != nil {
		return m.PassVideoEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassCreateCompaniesRequestEndpoint() *passcreatecompaniesrequestendpoint.PassCreateCompaniesRequestEndpoint {
	if m != nil {
		return m.PassCreateCompaniesRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassUpdateCompaniesRequestEndpoint() *passupdatecompaniesrequestendpoint.PassUpdateCompaniesRequestEndpoint {
	if m != nil {
		return m.PassUpdateCompaniesRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassDeleteCompaniesRequestEndpoint() *passdeletecompaniesrequestendpoint.PassDeleteCompaniesRequestEndpoint {
	if m != nil {
		return m.PassDeleteCompaniesRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassCreateJobsRequestEndpoint() *passcreatejobsrequestendpoint.PassCreateJobsRequestEndpoint {
	if m != nil {
		return m.PassCreateJobsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassUpdateJobsRequestEndpoint() *passupdatejobsrequestendpoint.PassUpdateJobsRequestEndpoint {
	if m != nil {
		return m.PassUpdateJobsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassDeleteJobsRequestEndpoint() *passdeletejobsrequestendpoint.PassDeleteJobsRequestEndpoint {
	if m != nil {
		return m.PassDeleteJobsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassCreateLocationsRequestEndpoint() *passcreatelocationsrequestendpoint.PassCreateLocationsRequestEndpoint {
	if m != nil {
		return m.PassCreateLocationsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassUpdateLocationsRequestEndpoint() *passupdatelocationsrequestendpoint.PassUpdateLocationsRequestEndpoint {
	if m != nil {
		return m.PassUpdateLocationsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassDeleteLocationsRequestEndpoint() *passdeletelocationsrequestendpoint.PassDeleteLocationsRequestEndpoint {
	if m != nil {
		return m.PassDeleteLocationsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassCreateProductsRequestEndpoint() *passcreateproductsrequestendpoint.PassCreateProductsRequestEndpoint {
	if m != nil {
		return m.PassCreateProductsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassUpdateProductsRequestEndpoint() *passupdateproductsrequestendpoint.PassUpdateProductsRequestEndpoint {
	if m != nil {
		return m.PassUpdateProductsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassDeleteProductsRequestEndpoint() *passdeleteproductsrequestendpoint.PassDeleteProductsRequestEndpoint {
	if m != nil {
		return m.PassDeleteProductsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassCreateSocialAccountsRequestEndpoint() *passcreatesocialaccountsrequestendpoint.PassCreateSocialAccountsRequestEndpoint {
	if m != nil {
		return m.PassCreateSocialAccountsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassUpdateSocialAccountsRequestEndpoint() *passupdatesocialaccountsrequestendpoint.PassUpdateSocialAccountsRequestEndpoint {
	if m != nil {
		return m.PassUpdateSocialAccountsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassDeleteSocialAccountsRequestEndpoint() *passdeletesocialaccountsrequestendpoint.PassDeleteSocialAccountsRequestEndpoint {
	if m != nil {
		return m.PassDeleteSocialAccountsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassCreatePersonsRequestEndpoint() *passcreatepersonsrequestendpoint.PassCreatePersonsRequestEndpoint {
	if m != nil {
		return m.PassCreatePersonsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassUpdatePersonsRequestEndpoint() *passupdatepersonsrequestendpoint.PassUpdatePersonsRequestEndpoint {
	if m != nil {
		return m.PassUpdatePersonsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassDeletePersonsRequestEndpoint() *passdeletepersonsrequestendpoint.PassDeletePersonsRequestEndpoint {
	if m != nil {
		return m.PassDeletePersonsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassCreatePostsRequestEndpoint() *passcreatepostsrequestendpoint.PassCreatePostsRequestEndpoint {
	if m != nil {
		return m.PassCreatePostsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassUpdatePostsRequestEndpoint() *passupdatepostsrequestendpoint.PassUpdatePostsRequestEndpoint {
	if m != nil {
		return m.PassUpdatePostsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassDeletePostsRequestEndpoint() *passdeletepostsrequestendpoint.PassDeletePostsRequestEndpoint {
	if m != nil {
		return m.PassDeletePostsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassCreateFeedsRequestEndpoint() *passcreatefeedsrequestendpoint.PassCreateFeedsRequestEndpoint {
	if m != nil {
		return m.PassCreateFeedsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassUpdateFeedsRequestEndpoint() *passupdatefeedsrequestendpoint.PassUpdateFeedsRequestEndpoint {
	if m != nil {
		return m.PassUpdateFeedsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassDeleteFeedsRequestEndpoint() *passdeletefeedsrequestendpoint.PassDeleteFeedsRequestEndpoint {
	if m != nil {
		return m.PassDeleteFeedsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassCreateSpecDescriptionsRequestEndpoint() *passcreatespecdescriptionsrequestendpoint.PassCreateSpecDescriptionsRequestEndpoint {
	if m != nil {
		return m.PassCreateSpecDescriptionsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassUpdateSpecDescriptionsRequestEndpoint() *passupdatespecdescriptionsrequestendpoint.PassUpdateSpecDescriptionsRequestEndpoint {
	if m != nil {
		return m.PassUpdateSpecDescriptionsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassDeleteSpecDescriptionsRequestEndpoint() *passdeletespecdescriptionsrequestendpoint.PassDeleteSpecDescriptionsRequestEndpoint {
	if m != nil {
		return m.PassDeleteSpecDescriptionsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassCreateWhateversRequestEndpoint() *passcreatewhateversrequestendpoint.PassCreateWhateversRequestEndpoint {
	if m != nil {
		return m.PassCreateWhateversRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassUpdateWhateversRequestEndpoint() *passupdatewhateversrequestendpoint.PassUpdateWhateversRequestEndpoint {
	if m != nil {
		return m.PassUpdateWhateversRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassDeleteWhateversRequestEndpoint() *passdeletewhateversrequestendpoint.PassDeleteWhateversRequestEndpoint {
	if m != nil {
		return m.PassDeleteWhateversRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassCreateServicesRequestEndpoint() *passcreateservicesrequestendpoint.PassCreateServicesRequestEndpoint {
	if m != nil {
		return m.PassCreateServicesRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassUpdateServicesRequestEndpoint() *passupdateservicesrequestendpoint.PassUpdateServicesRequestEndpoint {
	if m != nil {
		return m.PassUpdateServicesRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassDeleteServicesRequestEndpoint() *passdeleteservicesrequestendpoint.PassDeleteServicesRequestEndpoint {
	if m != nil {
		return m.PassDeleteServicesRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassCreateSystemAccountsRequestEndpoint() *passcreatesystemaccountsrequestendpoint.PassCreateSystemAccountsRequestEndpoint {
	if m != nil {
		return m.PassCreateSystemAccountsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassUpdateSystemAccountsRequestEndpoint() *passupdatesystemaccountsrequestendpoint.PassUpdateSystemAccountsRequestEndpoint {
	if m != nil {
		return m.PassUpdateSystemAccountsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetPassDeleteSystemAccountsRequestEndpoint() *passdeletesystemaccountsrequestendpoint.PassDeleteSystemAccountsRequestEndpoint {
	if m != nil {
		return m.PassDeleteSystemAccountsRequestEndpoint
	}
	return nil
}

func (m *Endpoint) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*Endpoint)(nil), "endpoint.Endpoint")
}

func init() { proto.RegisterFile("endpoint/endpoint_.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 3714 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x5c, 0xcb, 0x9f, 0x1c, 0x55,
	0x15, 0xfe, 0x8d, 0xa2, 0x42, 0xa1, 0x3c, 0x8a, 0x57, 0x08, 0xaf, 0x10, 0x11, 0x02, 0x42, 0x05,
	0x62, 0x8c, 0x88, 0x88, 0x90, 0x19, 0x02, 0x0c, 0x01, 0xe3, 0x1d, 0x26, 0x68, 0x54, 0xb0, 0xa7,
	0xbb, 0xd2, 0xd3, 0xc9, 0x4c, 0x57, 0xd3, 0xdd, 0x33, 0x38, 0xa8, 0xf8, 0x58, 0xb8, 0x70, 0xe1,
	0xc2, 0x85, 0x7f, 0x84, 0xee, 0xfc, 0xeb, 0x5c, 0xfa, 0xbb, 0x55, 0xe7, 0x3e, 0xce, 0xb3, 0xca,
	0xdd, 0xf4, 0xb9, 0xe7, 0x7c, 0xdf, 0x77, 0x5f, 0x75, 0x1f, 0x75, 0x6a, 0x8a, 0x53, 0xf5, 0x7c,
	0xb2, 0x68, 0x66, 0xf3, 0xf5, 0xf9, 0xf0, 0xc7, 0xa7, 0xd5, 0x62, 0xd9, 0xac, 0x9b, 0xf2, 0xce,
	0x60, 0x38, 0x7d, 0x26, 0xfc, 0x75, 0x7b, 0x36, 0x9f, 0x9c, 0xcf, 0x7f, 0x80, 0xef, 0xe9, 0xad,
	0xd1, 0xd1, 0x7a, 0xbf, 0x9e, 0xaf, 0x67, 0xe3, 0xd1, 0xba, 0x1e, 0x2f, 0xeb, 0x89, 0xff, 0x7b,
	0x74, 0x10, 0xb1, 0xed, 0xe2, 0x80, 0xf2, 0xf2, 0xb2, 0xbe, 0xb9, 0xac, 0x57, 0xfb, 0xeb, 0xe6,
	0x76, 0x3d, 0x8f, 0xb1, 0x92, 0x31, 0x44, 0x54, 0xc7, 0xf5, 0x72, 0x76, 0xf3, 0x04, 0x07, 0x08,
	0xb6, 0xc8, 0x30, 0xad, 0xd7, 0xe3, 0xe6, 0x70, 0x31, 0x9a, 0xcf, 0xea, 0x55, 0x0c, 0x90, 0x8c,
	0x21, 0xe2, 0x62, 0x2c, 0x3c, 0xd9, 0x3b, 0x99, 0x4d, 0x78, 0x0c, 0x32, 0x87, 0xa8, 0x4b, 0xe3,
	0x65, 0xed, 0xab, 0xca, 0xa8, 0x14, 0x7b, 0x8c, 0x3b, 0x5a, 0x4c, 0xc4, 0x38, 0xc5, 0x1e, 0xe3,
	0x26, 0xf5, 0x41, 0x2d, 0xc5, 0x29, 0xf6, 0x18, 0xb7, 0x5a, 0x2f, 0xeb, 0xd1, 0x21, 0x8f, 0x53,
	0xec, 0x21, 0xee, 0xd9, 0x69, 0xbd, 0xbe, 0xd5, 0xec, 0xa1, 0x26, 0xcc, 0x7f, 0x07, 0xbf, 0x17,
	0x3b, 0x3b, 0x6d, 0x39, 0x62, 0x8a, 0xde, 0x5d, 0xeb, 0x20, 0x60, 0x6e, 0x8a, 0xde, 0x5d, 0x9b,
	0x20, 0x6f, 0x6e, 0x8a, 0xde, 0x5d, 0x4b, 0x20, 0x6f, 0x6e, 0x8a, 0xde, 0x5d, 0xfd, 0x91, 0x37,
	0x37, 0xe5, 0x63, 0xe4, 0x56, 0xb3, 0x77, 0x30, 0x5b, 0xad, 0x85, 0x9a, 0x52, 0x73, 0x88, 0xba,
	0x70, 0xd8, 0x4c, 0x66, 0x37, 0x4f, 0xc0, 0x23, 0x06, 0x89, 0xd6, 0x7c, 0xfc, 0x1e, 0x34, 0xe3,
	0xd1, 0x7a, 0xd6, 0xcc, 0x51, 0xe3, 0x33, 0x63, 0xec, 0xe1, 0xac, 0x90, 0x8a, 0x93, 0xec, 0x64,
	0x04, 0x73, 0x32, 0xc5, 0x4e, 0x46, 0x30, 0x8f, 0x53, 0xec, 0x64, 0x04, 0xf3, 0x38, 0xc5, 0x4e,
	0x46, 0x30, 0x8f, 0x53, 0xec, 0xf1, 0xc9, 0x31, 0xad, 0xd7, 0x8b, 0x65, 0x33, 0x39, 0x1a, 0xaf,
	0x51, 0x43, 0x52, 0x5b, 0xde, 0xc7, 0x50, 0x46, 0x9b, 0x51, 0x30, 0xc7, 0xa8, 0xae, 0xb5, 0x18,
	0x91, 0x6c, 0x8e, 0x51, 0x5d, 0x5b, 0xb1, 0x28, 0xd9, 0x1c, 0xa3, 0xba, 0x96, 0x62, 0x51, 0xb2,
	0x39, 0x46, 0x75, 0xed, 0xc4, 0xa2, 0x64, 0x73, 0x88, 0x7a, 0x3d, 0x55, 0x5b, 0x1a, 0xf5, 0x4a,
	0x51, 0x88, 0x7e, 0xad, 0x1b, 0xe3, 0x99, 0x17, 0x19, 0xfd, 0x42, 0x49, 0x8c, 0x9d, 0xd6, 0xeb,
	0x55, 0x33, 0x9e, 0x8d, 0x0e, 0x46, 0xe3, 0x71, 0x73, 0x34, 0xc7, 0xbd, 0x27, 0x97, 0x84, 0xd8,
	0x37, 0xa9, 0x07, 0xd5, 0xad, 0x16, 0x46, 0x84, 0xae, 0xe3, 0x14, 0x01, 0x56, 0x61, 0x44, 0xe8,
	0x3a, 0x51, 0x41, 0xb0, 0x0a, 0x23, 0x42, 0xd7, 0xa1, 0x0a, 0x82, 0x55, 0x18, 0x11, 0xba, 0xce,
	0x55, 0x10, 0xac, 0xc2, 0x80, 0xf0, 0x2e, 0x6d, 0x2c, 0x69, 0x14, 0x98, 0x0e, 0x01, 0xe9, 0x4a,
	0xd7, 0xe3, 0xcc, 0x97, 0x8c, 0x08, 0xb5, 0x3c, 0x5f, 0x69, 0x16, 0xf5, 0x72, 0x45, 0x9e, 0x8b,
	0xc4, 0x14, 0x9f, 0xbd, 0xb1, 0x88, 0x0d, 0x5d, 0x66, 0x8d, 0x31, 0x30, 0x69, 0x09, 0x89, 0x68,
	0x8d, 0x31, 0x30, 0x65, 0x49, 0x8c, 0x68, 0x8d, 0x31, 0x30, 0x61, 0x49, 0x8c, 0x68, 0x8d, 0x31,
	0x30, 0x5d, 0x49, 0x8c, 0x68, 0xcd, 0x67, 0x52, 0x57, 0x24, 0x4e, 0x61, 0xb1, 0x24, 0xc4, 0xbe,
	0x0a, 0xf3, 0x34, 0x3a, 0xd1, 0x09, 0xcc, 0x0a, 0x42, 0xe4, 0x39, 0x8f, 0xdd, 0xac, 0xc8, 0x43,
	0x37, 0x37, 0xa0, 0x27, 0x74, 0x23, 0x28, 0x6b, 0x64, 0x4d, 0x15, 0xf4, 0x04, 0x02, 0x17, 0x6c,
	0xd1, 0x1f, 0x7a, 0x01, 0xf9, 0x0b, 0xb6, 0xe8, 0x0f, 0x3d, 0x80, 0xfc, 0x05, 0x5b, 0xf4, 0x87,
	0xd6, 0x47, 0xfe, 0x82, 0x2d, 0x5f, 0xa9, 0x7d, 0x81, 0xd8, 0x1b, 0x82, 0x3d, 0x3e, 0xc1, 0xa1,
	0xc9, 0xc1, 0x85, 0xf6, 0x04, 0x31, 0xe7, 0xfd, 0x70, 0xb3, 0xae, 0x27, 0xa8, 0x1f, 0x90, 0x21,
	0xef, 0x07, 0x5f, 0x40, 0x35, 0x51, 0x1b, 0xe9, 0x07, 0x0c, 0x2e, 0xd8, 0x48, 0x3f, 0x60, 0x7f,
	0xc1, 0x46, 0xfa, 0x01, 0xfb, 0x0b, 0x36, 0xd2, 0x0f, 0xd8, 0x5f, 0xb0, 0x05, 0xff, 0x37, 0xfc,
	0xa3, 0x6b, 0x51, 0x8f, 0x27, 0xf5, 0x6a, 0xbc, 0x9c, 0x2d, 0xd8, 0x56, 0x4b, 0x2b, 0x8b, 0x67,
	0x21, 0xee, 0xc3, 0x9e, 0x8c, 0x7a, 0x71, 0x44, 0x81, 0xc5, 0x44, 0x13, 0x62, 0x17, 0x47, 0x14,
	0x58, 0x50, 0x34, 0x14, 0xbb, 0x38, 0xa2, 0xc0, 0xa2, 0xa2, 0xa1, 0xd8, 0xc5, 0x11, 0x05, 0x16,
	0x16, 0x0d, 0xc5, 0x2e, 0xce, 0x77, 0xc0, 0x9f, 0xef, 0x8f, 0xd6, 0xf5, 0x71, 0xbd, 0x44, 0xdd,
	0xc2, 0x8c, 0xf9, 0xbc, 0x0a, 0x85, 0xb4, 0x23, 0x24, 0x3b, 0xd9, 0x01, 0x73, 0x32, 0xc5, 0x4e,
	0x76, 0xc0, 0x3c, 0x4e, 0xb1, 0x93, 0x1d, 0x30, 0x8f, 0x53, 0xec, 0x64, 0x07, 0xcc, 0xe3, 0x14,
	0x7b, 0x3e, 0xce, 0x43, 0xa1, 0xf4, 0xcc, 0xd1, 0xca, 0xe2, 0x1e, 0xb0, 0x7b, 0xc0, 0xe4, 0x6e,
	0xe4, 0xd9, 0x23, 0x15, 0xe5, 0x4f, 0x95, 0x55, 0xbd, 0x3c, 0x9e, 0x8d, 0xf1, 0x41, 0x9c, 0xda,
	0xf2, 0xfd, 0x37, 0x94, 0xb1, 0xd9, 0xc4, 0xcd, 0x64, 0xff, 0xcd, 0x88, 0x64, 0x33, 0xd9, 0x7f,
	0xb3, 0x28, 0xd9, 0x4c, 0xf6, 0xdf, 0x2c, 0x4a, 0x36, 0x93, 0xfd, 0x37, 0x8b, 0x92, 0xcd, 0xf9,
	0xfe, 0x1b, 0xca, 0xc4, 0x9d, 0x97, 0x5c, 0x44, 0xf6, 0xdf, 0x99, 0x17, 0xdd, 0x6d, 0xf1, 0x12,
	0xb4, 0xff, 0x3e, 0x59, 0xad, 0xeb, 0x43, 0x71, 0xff, 0x2d, 0x96, 0xa0, 0xfd, 0x77, 0xee, 0xc1,
	0x74, 0x6b, 0x85, 0x74, 0xff, 0x2d, 0x0b, 0xb0, 0x0a, 0xe9, 0xfe, 0x5b, 0x46, 0xb0, 0x0a, 0xe9,
	0xfe, 0x5b, 0x46, 0xb0, 0x0a, 0xe9, 0xfe, 0x5b, 0x46, 0xb0, 0x0a, 0xe3, 0xfd, 0xcb, 0x62, 0xb4,
	0x5a, 0x1d, 0x2d, 0xd3, 0x05, 0x1b, 0xf9, 0x1d, 0xfc, 0x5e, 0xf0, 0xf6, 0xe3, 0xd9, 0xa4, 0x6e,
	0x90, 0x27, 0xb2, 0x04, 0xdf, 0xab, 0xbe, 0x84, 0xdc, 0x4f, 0x2d, 0xeb, 0xcf, 0x8e, 0xea, 0x6c,
	0x78, 0xf4, 0xbb, 0x20, 0x34, 0x72, 0x6b, 0x25, 0xa1, 0xd9, 0x2e, 0x08, 0x8d, 0xdc, 0x65, 0x49,
	0x68, 0xb6, 0x4b, 0x40, 0xbb, 0x9c, 0xaa, 0x71, 0xab, 0xd9, 0x33, 0x2a, 0x29, 0x94, 0x22, 0x8c,
	0x74, 0xdd, 0xa4, 0x57, 0xad, 0x0f, 0x23, 0x5d, 0x42, 0xe9, 0x15, 0x32, 0x30, 0xb2, 0x5e, 0x8b,
	0x77, 0x1d, 0x7a, 0x85, 0x34, 0x17, 0xa1, 0xd7, 0x4c, 0x34, 0xdb, 0x45, 0xe8, 0x35, 0x13, 0xcd,
	0x76, 0x09, 0x68, 0xdb, 0xa9, 0x1a, 0xe1, 0x5a, 0x42, 0xaf, 0xa8, 0xe2, 0x81, 0xb0, 0xf0, 0x75,
	0x8a, 0x5e, 0xcd, 0x21, 0x58, 0xf8, 0x92, 0x45, 0xaf, 0x64, 0x0f, 0xd6, 0xf5, 0x54, 0x03, 0x7c,
	0x00, 0xd7, 0x6b, 0x6a, 0xfa, 0x21, 0x5c, 0xe9, 0x72, 0x41, 0xaf, 0xf5, 0x70, 0x5c, 0xe9, 0xca,
	0x41, 0x6f, 0x81, 0x41, 0xb8, 0xef, 0x66, 0x3d, 0xd9, 0x9d, 0x5e, 0x8d, 0xae, 0x16, 0x1d, 0x10,
	0x12, 0x3a, 0x6f, 0x1b, 0x1d, 0xdd, 0x8f, 0x84, 0x4e, 0xe1, 0x46, 0x37, 0x9b, 0x48, 0x5b, 0x99,
	0x78, 0x7f, 0x12, 0x34, 0xea, 0x26, 0x14, 0x23, 0x94, 0xec, 0xbc, 0x6a, 0xd4, 0xab, 0x0f, 0x25,
	0x3b, 0xc5, 0x1a, 0x75, 0xea, 0x43, 0xc9, 0xce, 0x78, 0x7a, 0x8d, 0xa4, 0x62, 0xa1, 0x46, 0x2a,
	0x8a, 0x5e, 0x2c, 0xd4, 0x48, 0x45, 0xd1, 0x8b, 0x03, 0xca, 0x8d, 0x6c, 0x86, 0x91, 0x23, 0x89,
	0x31, 0x17, 0x6d, 0x4f, 0x84, 0x2d, 0x1f, 0xbd, 0x8c, 0xf9, 0xf8, 0x7f, 0x60, 0xcb, 0x07, 0x32,
	0x63, 0x4e, 0x0e, 0xc3, 0xce, 0xd6, 0x9a, 0x78, 0xaa, 0xd0, 0x1b, 0x43, 0x73, 0x11, 0xd6, 0x1a,
	0x13, 0xcd, 0x76, 0x11, 0xd6, 0x1a, 0x13, 0xcd, 0x76, 0x11, 0xd6, 0x9a, 0xb0, 0x05, 0x37, 0x7a,
	0x5d, 0xf6, 0x10, 0xd6, 0x1a, 0x0b, 0xcb, 0xf4, 0x10, 0xd6, 0x1a, 0x0b, 0xcb, 0xf4, 0x90, 0xd6,
	0x1a, 0xb4, 0xd9, 0x34, 0x6a, 0x6a, 0xf9, 0x49, 0x6b, 0x4d, 0x2f, 0xee, 0x00, 0x3f, 0x69, 0xad,
	0xe9, 0xc5, 0x1d, 0xe0, 0x07, 0xb8, 0x67, 0xff, 0xfb, 0x79, 0x71, 0xe7, 0xdb, 0x60, 0x2b, 0xab,
	0xe2, 0x8e, 0xdb, 0xb3, 0xf9, 0xe4, 0xd4, 0xc6, 0x99, 0x8d, 0x73, 0xf7, 0x5c, 0x38, 0x5d, 0xe5,
	0x2f, 0xbb, 0xab, 0xe0, 0xf5, 0xfe, 0x6c, 0x3e, 0x71, 0xad, 0x5f, 0xf9, 0xd7, 0x8d, 0xe2, 0xc9,
	0xfc, 0xe5, 0xf6, 0x66, 0x7c, 0xb9, 0x1d, 0x9c, 0x4f, 0x7d, 0xe5, 0xcc, 0xc6, 0xb9, 0xbb, 0x2f,
	0xbc, 0x51, 0xd9, 0xef, 0xc0, 0xab, 0xb7, 0x4c, 0x14, 0xd7, 0xc3, 0x52, 0x7e, 0x52, 0x3c, 0x08,
	0x2f, 0xca, 0x3f, 0x6a, 0x6e, 0xd7, 0xf3, 0xc8, 0xfe, 0xd5, 0x96, 0xfd, 0x85, 0x4a, 0x7a, 0x8b,
	0x5e, 0x39, 0x21, 0xc2, 0x89, 0x38, 0xe5, 0x8d, 0xe2, 0x81, 0xee, 0xbd, 0x3a, 0x86, 0xbf, 0xa3,
	0x85, 0x3f, 0x27, 0xbd, 0x87, 0xaf, 0xae, 0x73, 0x7f, 0x27, 0x81, 0x78, 0xed, 0xd3, 0x7a, 0xbd,
	0x19, 0x76, 0xed, 0x11, 0xfc, 0x6b, 0xa0, 0x5d, 0x7a, 0x3f, 0x5f, 0xbd, 0x23, 0x44, 0x38, 0x11,
	0xa7, 0xbc, 0x59, 0x3c, 0x1c, 0xed, 0x27, 0x97, 0x4f, 0xde, 0x9b, 0x44, 0x86, 0xaf, 0xb7, 0x0c,
	0x55, 0x25, 0xbf, 0xcd, 0x4f, 0x1c, 0x28, 0xca, 0x29, 0x68, 0xe5, 0xad, 0xe2, 0x91, 0x6e, 0x9e,
	0xf0, 0xaa, 0x7c, 0xa3, 0x25, 0x7a, 0xb9, 0x52, 0xde, 0xff, 0x57, 0x9b, 0x72, 0x9c, 0xd3, 0x00,
	0x3d, 0x57, 0x37, 0x77, 0x38, 0xd7, 0x9d, 0xc0, 0xa5, 0xe4, 0x0c, 0x54, 0xbb, 0x72, 0x9c, 0xd3,
	0x00, 0x3d, 0x57, 0x37, 0x9f, 0x38, 0xd7, 0x5d, 0xc0, 0xa5, 0xe4, 0x19, 0x54, 0x5b, 0x72, 0x9c,
	0xd3, 0x00, 0x3d, 0x57, 0x77, 0x00, 0xe6, 0x5c, 0x05, 0x70, 0x29, 0xb9, 0x09, 0xd5, 0x8e, 0x1c,
	0xe7, 0x34, 0xc0, 0x72, 0xbb, 0xb8, 0x77, 0x5a, 0xaf, 0xb7, 0x9b, 0xbd, 0xc4, 0x71, 0x77, 0xcb,
	0x71, 0xa6, 0x22, 0xf9, 0x0c, 0x7e, 0x24, 0xe4, 0x7e, 0x8e, 0x06, 0x96, 0xd7, 0x8b, 0xb2, 0x33,
	0xa1, 0xf1, 0xf5, 0xcd, 0x16, 0xee, 0xd9, 0x8a, 0xe7, 0x3c, 0x00, 0x22, 0x1a, 0x57, 0x02, 0x82,
	0xc7, 0xed, 0x86, 0x00, 0x92, 0xf9, 0x2d, 0xc0, 0xe5, 0xd9, 0x11, 0x30, 0x92, 0x90, 0x58, 0x01,
	0xc1, 0xe3, 0x76, 0xdd, 0x8d, 0x70, 0xef, 0x01, 0x5c, 0x9e, 0x47, 0x01, 0xa3, 0x06, 0xe3, 0x72,
	0x04, 0x8f, 0xdb, 0x75, 0x2d, 0xc2, 0xbd, 0x17, 0x70, 0x79, 0xc6, 0x05, 0x8c, 0x10, 0x8c, 0xcb,
	0x11, 0x3c, 0x6e, 0xd7, 0x8d, 0x08, 0xf7, 0x3e, 0xc0, 0xe5, 0xb9, 0x19, 0x30, 0x1a, 0x30, 0x2e,
	0x47, 0x80, 0x67, 0xc3, 0x76, 0xb3, 0x77, 0x75, 0xb6, 0x5a, 0xa3, 0xbe, 0xbb, 0x3f, 0x3d, 0x1b,
	0x84, 0x2c, 0x0e, 0xe8, 0x3f, 0x1a, 0xe5, 0x14, 0xb4, 0x72, 0xaf, 0x78, 0xa8, 0xbb, 0x5b, 0x83,
	0xc2, 0x48, 0x53, 0xb6, 0x34, 0x2f, 0x56, 0x62, 0xde, 0x47, 0xf5, 0x81, 0x14, 0xe3, 0x64, 0x28,
	0x78, 0x8e, 0x5e, 0x0d, 0xe7, 0xe8, 0x48, 0xf1, 0x40, 0x7a, 0x8e, 0xb2, 0x7c, 0x08, 0x5f, 0x0f,
	0x16, 0xe1, 0x44, 0x1c, 0x3f, 0x37, 0x33, 0x3b, 0x6a, 0xac, 0x07, 0x61, 0x6e, 0x2a, 0x59, 0x25,
	0x39, 0x0b, 0x6a, 0x2e, 0x0d, 0x30, 0x3d, 0x4b, 0x79, 0x75, 0x1e, 0x42, 0xcf, 0x52, 0x5e, 0xa3,
	0x4d, 0x39, 0xce, 0x69, 0x80, 0xe9, 0x59, 0xca, 0xb9, 0x1e, 0x46, 0xcf, 0x52, 0xce, 0xb5, 0x2b,
	0xc7, 0x39, 0x0d, 0x30, 0x3d, 0x4b, 0x39, 0xd7, 0x23, 0xe8, 0x59, 0xca, 0xb9, 0xb6, 0xe4, 0x38,
	0xa7, 0x01, 0xa6, 0x67, 0x29, 0xe7, 0x3a, 0x85, 0x9e, 0xa5, 0x9c, 0x6b, 0x47, 0x8e, 0x73, 0x1a,
	0xa0, 0xdf, 0x1f, 0x4c, 0xeb, 0xf5, 0x35, 0xb8, 0xde, 0x88, 0x3c, 0x8f, 0xc2, 0xfe, 0x40, 0xc8,
	0xac, 0xf1, 0x63, 0x82, 0xfa, 0x3b, 0x09, 0x04, 0xe6, 0x28, 0x98, 0xd1, 0xb0, 0x3b, 0x9d, 0xe6,
	0xa8, 0x90, 0x85, 0x93, 0x31, 0xb0, 0x39, 0x2a, 0xd8, 0x3d, 0x4f, 0x37, 0x44, 0x58, 0x35, 0x1e,
	0x03, 0x1e, 0x39, 0x6f, 0x07, 0x46, 0x1c, 0xab, 0x8c, 0x82, 0xe6, 0x79, 0xba, 0xe1, 0xc1, 0x78,
	0x1e, 0x07, 0x1e, 0x39, 0xd3, 0x07, 0x46, 0x1b, 0xe7, 0x91, 0xd1, 0x3c, 0x4f, 0x37, 0x34, 0x18,
	0xcf, 0x13, 0xc0, 0x23, 0xe7, 0x06, 0xc1, 0x48, 0xe3, 0x3c, 0x32, 0x9a, 0xe7, 0xe9, 0x86, 0x05,
	0xe3, 0x79, 0x12, 0x78, 0xe4, 0x6c, 0x22, 0x18, 0x65, 0x9c, 0x47, 0x46, 0x2b, 0x8f, 0x8b, 0xd3,
	0xa9, 0xe7, 0xd8, 0xf3, 0xfa, 0xa9, 0x96, 0xeb, 0x52, 0xa5, 0xe7, 0x1f, 0x65, 0xe3, 0x81, 0x3d,
	0xb7, 0x0d, 0xe4, 0x72, 0x59, 0x3c, 0xda, 0x3d, 0x70, 0x33, 0x87, 0x48, 0x7b, 0xa6, 0xa5, 0xbd,
	0x58, 0xa9, 0x99, 0x4b, 0xf0, 0x0c, 0x17, 0x62, 0x9d, 0x0e, 0xeb, 0x39, 0xa7, 0xf5, 0x7a, 0xa7,
	0xbd, 0x2c, 0x7b, 0x0b, 0x0e, 0x30, 0x91, 0xf3, 0x69, 0xe0, 0x54, 0x33, 0x9e, 0x7c, 0x4d, 0xe5,
	0x58, 0xa7, 0xc3, 0x96, 0x5f, 0x16, 0x8f, 0xd3, 0x42, 0xd4, 0xc2, 0x67, 0x5b, 0xda, 0xd7, 0x2a,
	0x2b, 0x53, 0x8a, 0x31, 0xa3, 0x56, 0x36, 0xf1, 0x3d, 0x7f, 0x37, 0x63, 0x94, 0x6a, 0x7f, 0x1b,
	0xf8, 0xad, 0x3c, 0x2b, 0x98, 0x8b, 0x4a, 0xe5, 0x4d, 0x7c, 0xcf, 0xdf, 0xcd, 0x24, 0x85, 0xff,
	0x19, 0xe0, 0xb7, 0xb2, 0xb4, 0x60, 0x8e, 0x6a, 0xfc, 0x16, 0xbe, 0xe7, 0xef, 0x66, 0x98, 0xc2,
	0xff, 0x1d, 0xe0, 0xb7, 0x72, 0xbc, 0x60, 0xee, 0x6a, 0xfc, 0x16, 0xbe, 0xe7, 0xef, 0x66, 0x9e,
	0xc2, 0xff, 0x2c, 0xf0, 0x5b, 0x19, 0x62, 0x30, 0xa7, 0x35, 0x7e, 0x0b, 0xbf, 0xfc, 0xfb, 0x46,
	0x71, 0x86, 0x0e, 0x10, 0x36, 0xcd, 0x9f, 0x6b, 0x45, 0x5c, 0xae, 0xfa, 0x12, 0xcc, 0xd8, 0x40,
	0x64, 0x53, 0xbe, 0x97, 0xab, 0xfc, 0xdb, 0x46, 0xf1, 0x54, 0x37, 0x45, 0x99, 0x5f, 0xd4, 0x73,
	0xae, 0xd5, 0xf3, 0x66, 0xd5, 0x93, 0xa7, 0x06, 0x4f, 0x01, 0x15, 0xc7, 0xf5, 0x11, 0xc1, 0x09,
	0xe3, 0x5a, 0x77, 0xb3, 0x1c, 0xe9, 0x9f, 0x4f, 0x27, 0x0c, 0x92, 0xe7, 0xd5, 0x3e, 0xed, 0xb0,
	0xb7, 0x13, 0x10, 0xfc, 0xce, 0x34, 0x5a, 0x51, 0x4b, 0xbf, 0x00, 0x3b, 0x53, 0x31, 0x2b, 0x2e,
	0xa1, 0xa3, 0x36, 0x95, 0xa1, 0x3c, 0x07, 0xac, 0x85, 0x44, 0xfe, 0x77, 0x81, 0x43, 0xcc, 0xa2,
	0x0b, 0xeb, 0x2a, 0xa9, 0x84, 0x0c, 0xe5, 0x39, 0x60, 0x1d, 0x24, 0x1c, 0x2f, 0x02, 0x87, 0x98,
	0x75, 0x17, 0xd6, 0x54, 0xca, 0x21, 0x42, 0x79, 0x0e, 0x58, 0x03, 0x09, 0xc7, 0x4b, 0xc0, 0x21,
	0x66, 0xe9, 0x85, 0xf5, 0x94, 0x72, 0x88, 0x50, 0x9e, 0x03, 0xd6, 0x3f, 0xc2, 0x51, 0x01, 0x87,
	0x98, 0xd5, 0x17, 0xd6, 0x52, 0xca, 0x21, 0x42, 0xc1, 0xea, 0xd2, 0x59, 0xd9, 0x0c, 0x3b, 0x9f,
	0x56, 0x17, 0x39, 0x0b, 0x30, 0xf5, 0x3d, 0x9b, 0x53, 0x3a, 0x6c, 0x39, 0x2f, 0x4e, 0xc1, 0x72,
	0x17, 0xcb, 0x23, 0xe5, 0xcb, 0x2d, 0xe5, 0x85, 0x4a, 0xcb, 0x1e, 0x0c, 0x6b, 0x28, 0x8b, 0x74,
	0x2a, 0x66, 0xf9, 0x61, 0x71, 0x9f, 0x17, 0xd3, 0xac, 0xb2, 0x27, 0xd8, 0x2b, 0x2d, 0xcf, 0xd9,
	0x8a, 0xe6, 0x1c, 0xb6, 0x35, 0xca, 0x3d, 0x1d, 0x8b, 0x0d, 0x3b, 0xdc, 0x86, 0xb4, 0xd6, 0x85,
	0x6c, 0x87, 0xdb, 0x08, 0xed, 0x44, 0xfc, 0x9d, 0x04, 0xe2, 0xb1, 0x61, 0x50, 0x23, 0xb9, 0xdf,
	0x03, 0x6c, 0x21, 0x8b, 0x31, 0xcc, 0x0d, 0x24, 0x5a, 0x02, 0xf1, 0xd8, 0x30, 0x98, 0x11, 0xf6,
	0x45, 0xc0, 0x16, 0x32, 0x1e, 0xc3, 0x9c, 0xc0, 0xd8, 0x02, 0x88, 0xc7, 0x86, 0x41, 0x8c, 0xb0,
	0xbf, 0x0f, 0xd8, 0x42, 0x76, 0x64, 0x98, 0x0b, 0x18, 0x5b, 0x00, 0xf1, 0xd8, 0x30, 0x78, 0x11,
	0xf6, 0x25, 0xc0, 0x16, 0x32, 0x29, 0xc3, 0x1c, 0xc0, 0xd8, 0x02, 0x08, 0x9c, 0x64, 0xbd, 0x8d,
	0x8d, 0xfe, 0x1f, 0xa4, 0x93, 0xac, 0x94, 0x75, 0x19, 0xfa, 0x94, 0x8d, 0x7c, 0x0d, 0xd0, 0xef,
	0x8e, 0x61, 0x8c, 0x42, 0x69, 0xa4, 0x7a, 0x15, 0x76, 0xc7, 0x72, 0xa6, 0x66, 0x18, 0xf3, 0x24,
	0xca, 0x29, 0x68, 0x30, 0xde, 0xaf, 0xd4, 0xf5, 0x24, 0x35, 0xd6, 0x0f, 0xd3, 0x78, 0x47, 0xb9,
	0x8e, 0xbe, 0x16, 0xc8, 0xd3, 0xb1, 0x58, 0x18, 0xef, 0xde, 0x86, 0xda, 0xe7, 0xb5, 0x34, 0xde,
	0x69, 0x06, 0x68, 0x40, 0x65, 0xe3, 0x9d, 0x1a, 0xd3, 0x78, 0xc7, 0x72, 0x7f, 0x84, 0xc6, 0x3b,
	0x56, 0xbc, 0xc9, 0xfd, 0x9d, 0x04, 0x92, 0xc6, 0x3b, 0xc6, 0x7e, 0x1d, 0x8d, 0x77, 0x8c, 0xbd,
	0xcb, 0xfd, 0x9d, 0x04, 0x92, 0xc6, 0x3b, 0xc6, 0xfe, 0x31, 0x1a, 0xef, 0x18, 0x7b, 0x8b, 0xfb,
	0x3b, 0x09, 0x24, 0x8d, 0x77, 0x8c, 0xfd, 0x06, 0x1a, 0xef, 0x18, 0x7b, 0x87, 0xfb, 0x3b, 0x09,
	0xa4, 0xfc, 0xa2, 0x78, 0xcc, 0x6f, 0x76, 0x16, 0xf5, 0x78, 0x2b, 0x7b, 0xcd, 0x17, 0x39, 0x7e,
	0xd2, 0x72, 0xbc, 0x5a, 0x19, 0xd9, 0xad, 0xed, 0x76, 0x4a, 0x89, 0x77, 0x16, 0x78, 0xfb, 0x8a,
	0x84, 0x97, 0xa3, 0x31, 0xf5, 0x26, 0xbc, 0x22, 0xb1, 0x53, 0x63, 0x05, 0x09, 0x68, 0xa4, 0xf5,
	0xb0, 0xb4, 0x42, 0x60, 0xff, 0xaf, 0x35, 0xc4, 0x5b, 0x20, 0xc4, 0xce, 0xae, 0x0d, 0x67, 0x0c,
	0xad, 0x39, 0x7a, 0x58, 0x5a, 0x21, 0x70, 0x10, 0xd0, 0x84, 0x5c, 0x06, 0x21, 0x76, 0x82, 0x6e,
	0x38, 0x6c, 0xa8, 0x42, 0x6c, 0x96, 0x56, 0x08, 0x9c, 0x08, 0x34, 0x21, 0x9b, 0x20, 0xc4, 0xce,
	0xf1, 0x0d, 0xa7, 0x0e, 0x55, 0x88, 0xcd, 0xd2, 0x0a, 0x81, 0xa3, 0x81, 0x26, 0x64, 0x0b, 0x84,
	0xd8, 0x69, 0xc2, 0xe1, 0xf8, 0xa1, 0x0a, 0xb1, 0x59, 0xe0, 0x0a, 0xf5, 0xe3, 0xf0, 0x7a, 0x38,
	0xb2, 0xbf, 0x9d, 0xae, 0x50, 0x59, 0x42, 0xad, 0x1f, 0x97, 0x2c, 0xc2, 0x89, 0x38, 0xb0, 0xf0,
	0x04, 0x3b, 0x9a, 0x04, 0x57, 0xd2, 0xc2, 0x23, 0xa5, 0x25, 0xe7, 0x2c, 0x6c, 0xe1, 0x91, 0x0a,
	0xd2, 0x15, 0x2a, 0xaf, 0xce, 0x3b, 0xe8, 0x0a, 0x95, 0xd7, 0x68, 0x53, 0x8e, 0x73, 0x1a, 0x60,
	0xba, 0x42, 0xe5, 0x5c, 0xef, 0xa2, 0x2b, 0x54, 0xce, 0xb5, 0x2b, 0xc7, 0x39, 0x0d, 0x30, 0x5d,
	0xa1, 0x72, 0xae, 0xf7, 0xd0, 0x15, 0x2a, 0xe7, 0xda, 0x92, 0xe3, 0x9c, 0x06, 0x98, 0xae, 0x50,
	0x39, 0xd7, 0x36, 0xba, 0x42, 0xe5, 0x5c, 0x3b, 0x72, 0x9c, 0xd3, 0x00, 0xe1, 0x21, 0x1d, 0xec,
	0x6c, 0x63, 0xf2, 0x7e, 0x7a, 0x48, 0x6b, 0xa9, 0xd9, 0xf9, 0x18, 0x61, 0x1b, 0x14, 0x0b, 0xbc,
	0x3c, 0x2e, 0x4e, 0x77, 0xdb, 0x8a, 0xdc, 0x23, 0x52, 0x5f, 0x85, 0xab, 0x35, 0x3d, 0xad, 0x1b,
	0x36, 0x2b, 0x52, 0xb4, 0x33, 0x90, 0x61, 0x93, 0xb1, 0x03, 0x99, 0x0a, 0x91, 0xf0, 0x83, 0xb4,
	0xc9, 0xa0, 0x29, 0xd0, 0xed, 0x2a, 0x40, 0xfc, 0x9d, 0x04, 0x02, 0xd7, 0xc6, 0x60, 0x46, 0x4d,
	0xf9, 0x61, 0xba, 0x36, 0x16, 0x92, 0xc7, 0x33, 0x06, 0x76, 0x6d, 0x2c, 0xd8, 0xd3, 0xb5, 0x31,
	0xab, 0xc6, 0x4f, 0xd1, 0xb5, 0x31, 0xab, 0xc9, 0xa6, 0x18, 0xe5, 0x14, 0xb4, 0x74, 0x6d, 0xcc,
	0x78, 0xae, 0xa1, 0x6b, 0x63, 0xc6, 0xb3, 0x2b, 0x46, 0x39, 0x05, 0x2d, 0x5d, 0x1b, 0x33, 0x9e,
	0x9f, 0xa1, 0x6b, 0x63, 0xc6, 0xb3, 0x25, 0x46, 0x39, 0x05, 0x2d, 0x5d, 0x1b, 0x33, 0x1e, 0x87,
	0xae, 0x8d, 0x19, 0xcf, 0x8e, 0x18, 0xe5, 0x14, 0x34, 0xb8, 0x36, 0x06, 0x33, 0x9b, 0x56, 0x3b,
	0xe9, 0xda, 0x58, 0x49, 0x9b, 0xcf, 0xc6, 0x83, 0x78, 0x6d, 0xac, 0x94, 0xa5, 0x6b, 0xe3, 0xcc,
	0x21, 0xd2, 0x7e, 0x84, 0xae, 0x8d, 0x85, 0x84, 0xfb, 0x70, 0x61, 0xc4, 0x63, 0x9d, 0x0e, 0x1b,
	0xae, 0x8d, 0xdb, 0xbc, 0x17, 0x76, 0x7f, 0xb7, 0x9b, 0x5d, 0x1b, 0x8b, 0xe9, 0xe5, 0x6d, 0x4d,
	0xc5, 0x58, 0xa7, 0xc3, 0x86, 0x6b, 0xe3, 0xbc, 0x10, 0xb5, 0xf0, 0xf5, 0xec, 0xda, 0x58, 0x4b,
	0xf0, 0x67, 0xcc, 0xfc, 0xda, 0x58, 0x2b, 0xcd, 0xae, 0x8d, 0xe5, 0x6a, 0x7f, 0x8c, 0xaf, 0x8d,
	0xe5, 0x9a, 0x6f, 0x1a, 0x08, 0xce, 0xc4, 0xcf, 0xae, 0x8d, 0x65, 0xfe, 0x9f, 0xe3, 0x6b, 0x63,
	0x99, 0x7f, 0xd7, 0x40, 0x70, 0x26, 0x7e, 0x76, 0x6d, 0x2c, 0xf3, 0xff, 0x02, 0x5f, 0x1b, 0xcb,
	0xfc, 0x5b, 0x06, 0x82, 0x33, 0xf1, 0xb3, 0x6b, 0x63, 0x99, 0xff, 0x06, 0xbe, 0x36, 0x96, 0xf9,
	0x77, 0x0c, 0x04, 0x67, 0xe2, 0x97, 0xdb, 0xc5, 0xbd, 0x8b, 0xd1, 0x6a, 0xb5, 0xbb, 0x4c, 0x39,
	0x57, 0xbf, 0x84, 0x34, 0x0e, 0xf2, 0x59, 0x44, 0x75, 0x0d, 0xfb, 0x39, 0x1a, 0x58, 0xba, 0xe2,
	0x7e, 0x6f, 0xba, 0x3e, 0x9b, 0xd4, 0x4d, 0x44, 0xfb, 0x55, 0x8b, 0xf6, 0x4c, 0xc5, 0x3e, 0x9d,
	0x68, 0xf1, 0x90, 0xaf, 0xe3, 0xe1, 0xe5, 0x3f, 0x37, 0x8a, 0xb3, 0xde, 0x4a, 0x72, 0x7c, 0x5c,
	0x97, 0x8e, 0x16, 0x59, 0x7e, 0xdd, 0xb2, 0x5c, 0xa9, 0xfa, 0xbf, 0xb1, 0x68, 0x69, 0x6d, 0x34,
	0x37, 0x80, 0x31, 0x0a, 0x23, 0x09, 0x41, 0x54, 0xd8, 0x27, 0x99, 0x30, 0xfb, 0x73, 0x8d, 0xae,
	0x7d, 0x4d, 0x34, 0x37, 0x80, 0x31, 0x0a, 0x23, 0xd9, 0x43, 0x54, 0xd8, 0xa7, 0x99, 0x30, 0xfb,
	0xcb, 0x8f, 0x56, 0x98, 0x8d, 0xe6, 0x06, 0x30, 0x96, 0x7f, 0xd9, 0x28, 0x9e, 0x48, 0x0d, 0xbb,
	0xdd, 0xec, 0x31, 0x4d, 0xbf, 0x69, 0x35, 0xbd, 0x5e, 0x99, 0x1f, 0x91, 0x64, 0x1d, 0x28, 0x60,
	0x38, 0x9b, 0x22, 0x8a, 0x48, 0x19, 0x39, 0x54, 0xc4, 0x28, 0x13, 0xa1, 0x7e, 0x85, 0x92, 0x75,
	0x96, 0x2a, 0x42, 0x2d, 0x8e, 0x22, 0x52, 0xfa, 0x0e, 0x15, 0xb1, 0x97, 0x89, 0x50, 0x3f, 0x63,
	0xc9, 0x3a, 0x46, 0x15, 0xa1, 0x16, 0x93, 0x99, 0x15, 0x93, 0x12, 0xa8, 0x92, 0x31, 0x9b, 0x59,
	0xda, 0xb7, 0x26, 0x59, 0xc7, 0x68, 0x68, 0x6e, 0x00, 0x23, 0x99, 0x59, 0xaa, 0xb0, 0x09, 0x9b,
	0x59, 0xa6, 0x30, 0x1b, 0xcd, 0x0d, 0x60, 0x24, 0x33, 0x4b, 0x15, 0x56, 0xb3, 0x99, 0x65, 0x0a,
	0xb3, 0xd1, 0xdc, 0x00, 0xc6, 0xf2, 0x1f, 0x1b, 0xc5, 0xd3, 0xa9, 0x61, 0xc3, 0xab, 0x7f, 0xaa,
	0xeb, 0x66, 0xab, 0x6b, 0xab, 0xea, 0xfd, 0xd0, 0x27, 0xeb, 0x48, 0x05, 0xcb, 0xf5, 0xd3, 0x45,
	0x51, 0x38, 0xef, 0x82, 0x8a, 0x9a, 0x66, 0xa2, 0xcc, 0x2f, 0x86, 0xb2, 0x4e, 0x34, 0x45, 0x99,
	0x2e, 0x51, 0x14, 0x4e, 0xd2, 0xa0, 0xa2, 0xf6, 0x33, 0x51, 0xe6, 0xa7, 0x47, 0x59, 0x07, 0x9a,
	0xa2, 0x4c, 0x97, 0xf2, 0x5f, 0x1b, 0xc5, 0x73, 0xa9, 0x3d, 0xf1, 0xfb, 0x5d, 0x2a, 0x6d, 0xd6,
	0x4a, 0xbb, 0x56, 0x0d, 0xfc, 0x86, 0x29, 0xeb, 0x4a, 0x13, 0xd7, 0x0d, 0x15, 0x10, 0xc5, 0x4a,
	0xaf, 0xea, 0xa9, 0xd8, 0x5b, 0x99, 0xd8, 0x01, 0x1f, 0x46, 0x65, 0x5d, 0x3c, 0x40, 0xec, 0x00,
	0xc7, 0x28, 0x56, 0x7a, 0xaf, 0x4f, 0xc5, 0xde, 0xce, 0xc4, 0x0e, 0xf8, 0xda, 0x2a, 0xeb, 0xfa,
	0x01, 0x62, 0x07, 0x38, 0xb6, 0x6f, 0xf0, 0xb3, 0x69, 0xd5, 0xbd, 0x75, 0xa4, 0x2a, 0x0f, 0xe0,
	0x0d, 0x7e, 0xdf, 0x27, 0x5c, 0xf9, 0x1c, 0x16, 0x91, 0x5c, 0x2f, 0x57, 0x14, 0x84, 0xde, 0xf2,
	0x52, 0x41, 0x87, 0x99, 0x20, 0xeb, 0x4b, 0xb0, 0x7c, 0xfe, 0x1a, 0x82, 0x2c, 0x8f, 0x28, 0x08,
	0xbd, 0x12, 0xa6, 0x82, 0xe6, 0x99, 0x20, 0xeb, 0x83, 0xb2, 0x7c, 0xee, 0x1a, 0x82, 0x2c, 0x8f,
	0xf6, 0xea, 0x35, 0x6b, 0xc6, 0x66, 0xc5, 0x87, 0x55, 0x03, 0x57, 0xaf, 0xf6, 0x77, 0x69, 0x79,
	0x77, 0x09, 0x28, 0xae, 0x87, 0x25, 0x0a, 0xc9, 0x5e, 0x3e, 0x52, 0x21, 0x8b, 0x4c, 0x88, 0xfe,
	0x69, 0x5b, 0xde, 0x4d, 0xaa, 0x10, 0xbd, 0x3c, 0x0a, 0xc9, 0xde, 0x54, 0x52, 0x21, 0x9f, 0x65,
	0x42, 0xf4, 0xaf, 0xe3, 0xf2, 0xee, 0x51, 0x85, 0xe8, 0xe5, 0xa4, 0x6b, 0xda, 0x37, 0x3a, 0x54,
	0xc8, 0x92, 0x75, 0x8d, 0xf4, 0x51, 0x5b, 0xd6, 0x35, 0x12, 0x8a, 0xeb, 0x61, 0x21, 0x5d, 0x23,
	0x0a, 0x59, 0xb1, 0xae, 0x51, 0x85, 0xe8, 0x28, 0xae, 0x87, 0x85, 0x74, 0x8d, 0x28, 0x64, 0xcd,
	0xba, 0x46, 0x15, 0xa2, 0xa3, 0xb8, 0x1e, 0x96, 0xf2, 0x3f, 0x1b, 0xc5, 0xf3, 0xd9, 0x72, 0x43,
	0x5e, 0x27, 0x50, 0x4d, 0x47, 0xad, 0xa6, 0x8f, 0xaa, 0xc1, 0x5f, 0x0a, 0xe6, 0x6b, 0x9e, 0x8d,
	0xed, 0x86, 0xcb, 0x88, 0xa2, 0xe5, 0xb7, 0x46, 0x54, 0xf4, 0x71, 0x26, 0x7a, 0xd0, 0x27, 0x88,
	0xf9, 0xda, 0x37, 0x44, 0xf4, 0x20, 0xd7, 0x28, 0x5a, 0x7e, 0xc3, 0x44, 0x45, 0x7f, 0x9e, 0x89,
	0x1e, 0xf4, 0x6d, 0x63, 0xbe, 0x06, 0x0e, 0x11, 0x3d, 0xc8, 0x95, 0x1c, 0x4c, 0xe2, 0x55, 0x3f,
	0x55, 0xfb, 0x5b, 0x76, 0x30, 0xd1, 0x3e, 0x4c, 0xcc, 0x06, 0x84, 0x86, 0xe6, 0x06, 0x30, 0x92,
	0x83, 0x89, 0x2a, 0xec, 0x84, 0x1d, 0x4c, 0x4c, 0x61, 0x36, 0x9a, 0x1b, 0xc0, 0x48, 0x0e, 0x26,
	0xaa, 0xb0, 0x2f, 0xd8, 0xc1, 0xc4, 0x14, 0x66, 0xa3, 0xb9, 0x01, 0x8c, 0xe4, 0x60, 0x12, 0x2e,
	0x97, 0xa9, 0xae, 0xdf, 0xb1, 0x83, 0x89, 0xf2, 0xf5, 0x65, 0x3e, 0xb3, 0x65, 0x2c, 0xd7, 0x4f,
	0x47, 0x0e, 0x26, 0x9a, 0xa8, 0xdf, 0xb3, 0x83, 0x89, 0x25, 0xca, 0xc4, 0x72, 0xfd, 0x74, 0xe4,
	0x60, 0xa2, 0x89, 0xfa, 0x03, 0x3b, 0x98, 0x58, 0xa2, 0x4c, 0x2c, 0xd7, 0x4f, 0x47, 0x0f, 0x26,
	0xe8, 0x06, 0x91, 0x4a, 0xfb, 0x92, 0x1f, 0x4c, 0xac, 0x0f, 0x48, 0xf3, 0xae, 0xb4, 0x70, 0xdd,
	0x50, 0x01, 0xf4, 0x60, 0x62, 0x8a, 0xfd, 0x23, 0x3f, 0x98, 0xf4, 0x8a, 0x1d, 0x80, 0xeb, 0x86,
	0x0a, 0x28, 0xff, 0x8d, 0x0f, 0x26, 0xa6, 0xd8, 0x3f, 0x6d, 0xf0, 0x93, 0x49, 0xaf, 0xda, 0x01,
	0xc0, 0x6e, 0xa8, 0x82, 0xf2, 0x81, 0xe2, 0x8e, 0xfd, 0xd1, 0x6a, 0xff, 0xd4, 0x9f, 0xbd, 0x92,
	0xbb, 0x5c, 0xfb, 0xe3, 0xf2, 0xa5, 0x1b, 0x17, 0xa7, 0xb3, 0xf5, 0xfe, 0xd1, 0x5e, 0x35, 0x6e,
	0x0e, 0xcf, 0x5f, 0x78, 0x65, 0xb5, 0x9e, 0x35, 0xe7, 0xa7, 0xcd, 0x4b, 0x8b, 0x83, 0xd1, 0xc9,
	0x74, 0xd9, 0x1c, 0xcd, 0x27, 0xe7, 0xa7, 0xcb, 0xc5, 0xf8, 0xfc, 0x6a, 0xbc, 0x5f, 0x1f, 0x8e,
	0xe2, 0x7f, 0xbe, 0xfe, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x31, 0x33, 0x54, 0x35, 0x5b,
	0x00, 0x00,
}
