// Code generated by protoc-gen-go. DO NOT EDIT.
// source: passdeletecompaniesrequestrequestfilter/passdeletecompaniesrequestrequestfilter_.proto

/*
Package passdeletecompaniesrequestrequestfilter is a generated protocol buffer package.

It is generated from these files:
	passdeletecompaniesrequestrequestfilter/passdeletecompaniesrequestrequestfilter_.proto

It has these top-level messages:
	PassDeleteCompaniesRequestRequestFilter
*/
package passdeletecompaniesrequestrequestfilter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import requestmetafilter "github.com/21stio/go-playground/grpc/schema/requestmetafilter"
import deletecompaniesrequestfilter "github.com/21stio/go-playground/grpc/schema/deletecompaniesrequestfilter"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PassDeleteCompaniesRequestRequestFilter struct {
	Meta                   *requestmetafilter.RequestMetaFilter                       `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	DeleteCompaniesRequest *deletecompaniesrequestfilter.DeleteCompaniesRequestFilter `protobuf:"bytes,2,opt,name=deleteCompaniesRequest" json:"deleteCompaniesRequest,omitempty"`
	And                    []*PassDeleteCompaniesRequestRequestFilter                 `protobuf:"bytes,3,rep,name=and" json:"and,omitempty"`
	Or                     []*PassDeleteCompaniesRequestRequestFilter                 `protobuf:"bytes,4,rep,name=or" json:"or,omitempty"`
	Not                    []*PassDeleteCompaniesRequestRequestFilter                 `protobuf:"bytes,5,rep,name=not" json:"not,omitempty"`
	Hash                   *string                                                    `protobuf:"bytes,6,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized       []byte                                                     `json:"-"`
}

func (m *PassDeleteCompaniesRequestRequestFilter) Reset() {
	*m = PassDeleteCompaniesRequestRequestFilter{}
}
func (m *PassDeleteCompaniesRequestRequestFilter) String() string { return proto.CompactTextString(m) }
func (*PassDeleteCompaniesRequestRequestFilter) ProtoMessage()    {}
func (*PassDeleteCompaniesRequestRequestFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0}
}

func (m *PassDeleteCompaniesRequestRequestFilter) GetMeta() *requestmetafilter.RequestMetaFilter {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *PassDeleteCompaniesRequestRequestFilter) GetDeleteCompaniesRequest() *deletecompaniesrequestfilter.DeleteCompaniesRequestFilter {
	if m != nil {
		return m.DeleteCompaniesRequest
	}
	return nil
}

func (m *PassDeleteCompaniesRequestRequestFilter) GetAnd() []*PassDeleteCompaniesRequestRequestFilter {
	if m != nil {
		return m.And
	}
	return nil
}

func (m *PassDeleteCompaniesRequestRequestFilter) GetOr() []*PassDeleteCompaniesRequestRequestFilter {
	if m != nil {
		return m.Or
	}
	return nil
}

func (m *PassDeleteCompaniesRequestRequestFilter) GetNot() []*PassDeleteCompaniesRequestRequestFilter {
	if m != nil {
		return m.Not
	}
	return nil
}

func (m *PassDeleteCompaniesRequestRequestFilter) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*PassDeleteCompaniesRequestRequestFilter)(nil), "passdeletecompaniesrequestrequestfilter.PassDeleteCompaniesRequestRequestFilter")
}

func init() {
	proto.RegisterFile("passdeletecompaniesrequestrequestfilter/passdeletecompaniesrequestrequestfilter_.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x3b, 0x4b, 0xc4, 0x40,
	0x10, 0x26, 0x0f, 0x05, 0xf7, 0xba, 0x2d, 0x64, 0xb9, 0x2a, 0x88, 0x70, 0x41, 0x70, 0x83, 0xa9,
	0xc4, 0x4a, 0x54, 0xec, 0x84, 0x23, 0xa2, 0x85, 0x8d, 0xee, 0x25, 0x63, 0x12, 0x48, 0x32, 0x71,
	0x77, 0x52, 0xf8, 0x43, 0xfc, 0xbf, 0x92, 0xdc, 0x5a, 0x5d, 0x3c, 0xb6, 0xb9, 0x6a, 0xf6, 0xf1,
	0xbd, 0x66, 0x60, 0xd8, 0x6b, 0xaf, 0x8c, 0x29, 0xa0, 0x01, 0x82, 0x1c, 0xdb, 0x5e, 0x75, 0x35,
	0x18, 0x0d, 0x5f, 0x03, 0x18, 0xb2, 0xe5, 0xb3, 0x6e, 0x08, 0x74, 0xe2, 0x88, 0x7b, 0x97, 0xbd,
	0x46, 0x42, 0xbe, 0x72, 0xc4, 0x2f, 0x2f, 0xec, 0xb5, 0x05, 0x52, 0xd6, 0x6a, 0xe7, 0xc5, 0x8a,
	0x2e, 0x6f, 0xe7, 0x05, 0x2d, 0x6d, 0xdf, 0xa7, 0x55, 0x38, 0xfb, 0x09, 0xd9, 0x6a, 0xad, 0x8c,
	0x79, 0x98, 0xb0, 0xf7, 0x7f, 0xd8, 0x6c, 0x8b, 0xb5, 0xe5, 0x71, 0xa2, 0xf0, 0x6b, 0x16, 0x8e,
	0x11, 0x84, 0x17, 0x79, 0xf1, 0x22, 0x3d, 0x97, 0x3b, 0xb1, 0xa4, 0xc5, 0x3f, 0x01, 0xa9, 0x2d,
	0x27, 0x9b, 0x18, 0x5c, 0xb3, 0xd3, 0x62, 0xd6, 0x40, 0xf8, 0x93, 0xd6, 0x8d, 0xdc, 0x97, 0x55,
	0xce, 0x87, 0xb3, 0x0e, 0xff, 0x28, 0xf3, 0x0d, 0x0b, 0x54, 0x57, 0x88, 0x20, 0x0a, 0xe2, 0x45,
	0xba, 0x96, 0x8e, 0xe3, 0x97, 0x8e, 0xc3, 0xc8, 0x46, 0x71, 0xfe, 0xc1, 0x7c, 0xd4, 0x22, 0x3c,
	0x90, 0x85, 0x8f, 0x7a, 0xec, 0xa2, 0x43, 0x12, 0x47, 0x87, 0xea, 0xa2, 0x43, 0xe2, 0x9c, 0x85,
	0x95, 0x32, 0x95, 0x38, 0x8e, 0xbc, 0xf8, 0x24, 0x9b, 0xce, 0x77, 0x2f, 0x6f, 0xcf, 0x65, 0x4d,
	0xd5, 0xb0, 0x91, 0x39, 0xb6, 0x49, 0x7a, 0x65, 0xa8, 0xc6, 0xa4, 0xc4, 0xcb, 0xbe, 0x51, 0xdf,
	0xa5, 0xc6, 0xa1, 0x2b, 0x92, 0x52, 0xf7, 0x79, 0x62, 0xf2, 0x0a, 0x5a, 0xe5, 0xba, 0x0c, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x31, 0x57, 0x78, 0x5e, 0x03, 0x00, 0x00,
}
