// Code generated by protoc-gen-go. DO NOT EDIT.
// source: timestampkindfilter/timestampkindfilter_.proto

/*
Package timestampkindfilter is a generated protocol buffer package.

It is generated from these files:
	timestampkindfilter/timestampkindfilter_.proto

It has these top-level messages:
	TimestampKindFilter
*/
package timestampkindfilter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestampkind "github.com/21stio/go-playground/grpc/schema/timestampkind"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TimestampKindFilter struct {
	Is               *timestampkind.TimestampKind  `protobuf:"varint,1,opt,name=is,enum=timestampkind.TimestampKind" json:"is,omitempty"`
	Not              *timestampkind.TimestampKind  `protobuf:"varint,2,opt,name=not,enum=timestampkind.TimestampKind" json:"not,omitempty"`
	In               []timestampkind.TimestampKind `protobuf:"varint,3,rep,name=in,enum=timestampkind.TimestampKind" json:"in,omitempty"`
	NotIn            []timestampkind.TimestampKind `protobuf:"varint,4,rep,name=notIn,enum=timestampkind.TimestampKind" json:"notIn,omitempty"`
	Hash             *string                       `protobuf:"bytes,5,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *TimestampKindFilter) Reset()                    { *m = TimestampKindFilter{} }
func (m *TimestampKindFilter) String() string            { return proto.CompactTextString(m) }
func (*TimestampKindFilter) ProtoMessage()               {}
func (*TimestampKindFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TimestampKindFilter) GetIs() timestampkind.TimestampKind {
	if m != nil && m.Is != nil {
		return *m.Is
	}
	return timestampkind.TimestampKind_UNIX
}

func (m *TimestampKindFilter) GetNot() timestampkind.TimestampKind {
	if m != nil && m.Not != nil {
		return *m.Not
	}
	return timestampkind.TimestampKind_UNIX
}

func (m *TimestampKindFilter) GetIn() []timestampkind.TimestampKind {
	if m != nil {
		return m.In
	}
	return nil
}

func (m *TimestampKindFilter) GetNotIn() []timestampkind.TimestampKind {
	if m != nil {
		return m.NotIn
	}
	return nil
}

func (m *TimestampKindFilter) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*TimestampKindFilter)(nil), "timestampkindfilter.TimestampKindFilter")
}

func init() { proto.RegisterFile("timestampkindfilter/timestampkindfilter_.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2b, 0xc9, 0xcc, 0x4d,
	0x2d, 0x2e, 0x49, 0xcc, 0x2d, 0xc8, 0xce, 0xcc, 0x4b, 0x49, 0xcb, 0xcc, 0x29, 0x49, 0x2d, 0xd2,
	0xc7, 0x22, 0x16, 0xaf, 0x57, 0x50, 0x94, 0x5f, 0x92, 0x2f, 0x24, 0x8c, 0x45, 0x4e, 0x4a, 0x09,
	0x45, 0x10, 0x55, 0x3b, 0x54, 0xa3, 0xd2, 0x4b, 0x46, 0x2e, 0xe1, 0x10, 0x98, 0x84, 0x77, 0x66,
	0x5e, 0x8a, 0x1b, 0x58, 0xaf, 0x90, 0x0e, 0x17, 0x53, 0x66, 0xb1, 0x04, 0xa3, 0x02, 0xa3, 0x06,
	0x9f, 0x91, 0x0c, 0xaa, 0x6b, 0xf4, 0x50, 0xd4, 0x07, 0x31, 0x65, 0x16, 0x0b, 0xe9, 0x71, 0x31,
	0xe7, 0xe5, 0x97, 0x48, 0x30, 0x11, 0xa1, 0x1c, 0xa4, 0x10, 0x6c, 0x7a, 0x9e, 0x04, 0xb3, 0x02,
	0x33, 0x11, 0xa6, 0xe7, 0x09, 0x19, 0x71, 0xb1, 0xe6, 0xe5, 0x97, 0x78, 0xe6, 0x49, 0xb0, 0x10,
	0xa1, 0x01, 0xa2, 0x54, 0x48, 0x88, 0x8b, 0x25, 0x23, 0xb1, 0x38, 0x43, 0x82, 0x55, 0x81, 0x51,
	0x83, 0x33, 0x08, 0xcc, 0x76, 0x72, 0x8c, 0xb2, 0x4f, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b,
	0xce, 0xcf, 0xd5, 0x37, 0x32, 0x2c, 0x2e, 0xc9, 0xcc, 0xd7, 0x4f, 0xcf, 0xd7, 0x2d, 0xc8, 0x49,
	0xac, 0x4c, 0x2f, 0xca, 0x2f, 0xcd, 0x4b, 0xd1, 0x4f, 0x2f, 0x2a, 0x48, 0xd6, 0x2f, 0x4e, 0xce,
	0x48, 0xcd, 0x4d, 0xc4, 0x16, 0xdc, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x34, 0x4b, 0xd6, 0xae,
	0x98, 0x01, 0x00, 0x00,
}
