// Code generated by protoc-gen-go. DO NOT EDIT.
// source: servicefilter/servicefilter_.proto

/*
Package servicefilter is a generated protocol buffer package.

It is generated from these files:
	servicefilter/servicefilter_.proto

It has these top-level messages:
	ServiceFilter
	TypeMetaFilter
*/
package servicefilter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import stringfilter "github.com/21stio/go-playground/grpc/schema/stringfilter"
import endpointfilter "github.com/21stio/go-playground/grpc/schema/endpointfilter"
import serviceportsfilter "github.com/21stio/go-playground/grpc/schema/serviceportsfilter"
import idfilter "github.com/21stio/go-playground/grpc/schema/idfilter"
import floatfilter "github.com/21stio/go-playground/grpc/schema/floatfilter"
import ratingfilter "github.com/21stio/go-playground/grpc/schema/ratingfilter"
import durationvaluefilter "github.com/21stio/go-playground/grpc/schema/durationvaluefilter"
import timestampfilter "github.com/21stio/go-playground/grpc/schema/timestampfilter"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServiceFilter struct {
	Name             *stringfilter.StringFilter             `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Host             *stringfilter.StringFilter             `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	EndpointsSome    *endpointfilter.EndpointFilter         `protobuf:"bytes,3,opt,name=endpointsSome" json:"endpointsSome,omitempty"`
	EndpointsEvery   *endpointfilter.EndpointFilter         `protobuf:"bytes,4,opt,name=endpointsEvery" json:"endpointsEvery,omitempty"`
	EndpointsNone    *endpointfilter.EndpointFilter         `protobuf:"bytes,5,opt,name=endpointsNone" json:"endpointsNone,omitempty"`
	Ports            *serviceportsfilter.ServicePortsFilter `protobuf:"bytes,6,opt,name=ports" json:"ports,omitempty"`
	IdsSome          *idfilter.IdFilter                     `protobuf:"bytes,7,opt,name=idsSome" json:"idsSome,omitempty"`
	IdsEvery         *idfilter.IdFilter                     `protobuf:"bytes,8,opt,name=idsEvery" json:"idsEvery,omitempty"`
	IdsNone          *idfilter.IdFilter                     `protobuf:"bytes,9,opt,name=idsNone" json:"idsNone,omitempty"`
	Meta             *TypeMetaFilter                        `protobuf:"bytes,10,opt,name=meta" json:"meta,omitempty"`
	And              []*ServiceFilter                       `protobuf:"bytes,11,rep,name=and" json:"and,omitempty"`
	Or               []*ServiceFilter                       `protobuf:"bytes,12,rep,name=or" json:"or,omitempty"`
	Not              []*ServiceFilter                       `protobuf:"bytes,13,rep,name=not" json:"not,omitempty"`
	Hash             *string                                `protobuf:"bytes,14,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte                                 `json:"-"`
}

func (m *ServiceFilter) Reset()                    { *m = ServiceFilter{} }
func (m *ServiceFilter) String() string            { return proto.CompactTextString(m) }
func (*ServiceFilter) ProtoMessage()               {}
func (*ServiceFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ServiceFilter) GetName() *stringfilter.StringFilter {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ServiceFilter) GetHost() *stringfilter.StringFilter {
	if m != nil {
		return m.Host
	}
	return nil
}

func (m *ServiceFilter) GetEndpointsSome() *endpointfilter.EndpointFilter {
	if m != nil {
		return m.EndpointsSome
	}
	return nil
}

func (m *ServiceFilter) GetEndpointsEvery() *endpointfilter.EndpointFilter {
	if m != nil {
		return m.EndpointsEvery
	}
	return nil
}

func (m *ServiceFilter) GetEndpointsNone() *endpointfilter.EndpointFilter {
	if m != nil {
		return m.EndpointsNone
	}
	return nil
}

func (m *ServiceFilter) GetPorts() *serviceportsfilter.ServicePortsFilter {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *ServiceFilter) GetIdsSome() *idfilter.IdFilter {
	if m != nil {
		return m.IdsSome
	}
	return nil
}

func (m *ServiceFilter) GetIdsEvery() *idfilter.IdFilter {
	if m != nil {
		return m.IdsEvery
	}
	return nil
}

func (m *ServiceFilter) GetIdsNone() *idfilter.IdFilter {
	if m != nil {
		return m.IdsNone
	}
	return nil
}

func (m *ServiceFilter) GetMeta() *TypeMetaFilter {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ServiceFilter) GetAnd() []*ServiceFilter {
	if m != nil {
		return m.And
	}
	return nil
}

func (m *ServiceFilter) GetOr() []*ServiceFilter {
	if m != nil {
		return m.Or
	}
	return nil
}

func (m *ServiceFilter) GetNot() []*ServiceFilter {
	if m != nil {
		return m.Not
	}
	return nil
}

func (m *ServiceFilter) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

type TypeMetaFilter struct {
	Service          *ServiceFilter                           `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	Relevance        *floatfilter.FloatFilter                 `protobuf:"bytes,2,opt,name=relevance" json:"relevance,omitempty"`
	Rating           *ratingfilter.RatingFilter               `protobuf:"bytes,3,opt,name=rating" json:"rating,omitempty"`
	Age              *durationvaluefilter.DurationValueFilter `protobuf:"bytes,4,opt,name=age" json:"age,omitempty"`
	CreatedAt        *timestampfilter.TimestampFilter         `protobuf:"bytes,5,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt        *timestampfilter.TimestampFilter         `protobuf:"bytes,6,opt,name=updatedAt" json:"updatedAt,omitempty"`
	And              []*TypeMetaFilter                        `protobuf:"bytes,7,rep,name=and" json:"and,omitempty"`
	Or               []*TypeMetaFilter                        `protobuf:"bytes,8,rep,name=or" json:"or,omitempty"`
	Not              []*TypeMetaFilter                        `protobuf:"bytes,9,rep,name=not" json:"not,omitempty"`
	Hash             *string                                  `protobuf:"bytes,10,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte                                   `json:"-"`
}

func (m *TypeMetaFilter) Reset()                    { *m = TypeMetaFilter{} }
func (m *TypeMetaFilter) String() string            { return proto.CompactTextString(m) }
func (*TypeMetaFilter) ProtoMessage()               {}
func (*TypeMetaFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TypeMetaFilter) GetService() *ServiceFilter {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *TypeMetaFilter) GetRelevance() *floatfilter.FloatFilter {
	if m != nil {
		return m.Relevance
	}
	return nil
}

func (m *TypeMetaFilter) GetRating() *ratingfilter.RatingFilter {
	if m != nil {
		return m.Rating
	}
	return nil
}

func (m *TypeMetaFilter) GetAge() *durationvaluefilter.DurationValueFilter {
	if m != nil {
		return m.Age
	}
	return nil
}

func (m *TypeMetaFilter) GetCreatedAt() *timestampfilter.TimestampFilter {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *TypeMetaFilter) GetUpdatedAt() *timestampfilter.TimestampFilter {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *TypeMetaFilter) GetAnd() []*TypeMetaFilter {
	if m != nil {
		return m.And
	}
	return nil
}

func (m *TypeMetaFilter) GetOr() []*TypeMetaFilter {
	if m != nil {
		return m.Or
	}
	return nil
}

func (m *TypeMetaFilter) GetNot() []*TypeMetaFilter {
	if m != nil {
		return m.Not
	}
	return nil
}

func (m *TypeMetaFilter) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*ServiceFilter)(nil), "servicefilter.ServiceFilter")
	proto.RegisterType((*TypeMetaFilter)(nil), "servicefilter.TypeMetaFilter")
}

func init() { proto.RegisterFile("servicefilter/servicefilter_.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 593 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0x4d, 0x8b, 0xdb, 0x3c,
	0x10, 0xc7, 0xc9, 0x7b, 0xa2, 0x3c, 0xc9, 0x41, 0x27, 0x11, 0x9e, 0x2e, 0x26, 0x94, 0x25, 0x87,
	0xec, 0x98, 0xcd, 0x61, 0xa1, 0x2f, 0x14, 0x5a, 0x76, 0x03, 0x3d, 0xb4, 0x94, 0x64, 0xe9, 0xa1,
	0x97, 0xa2, 0xda, 0x5a, 0xc7, 0x10, 0x5b, 0x46, 0x56, 0x02, 0xf9, 0x20, 0xfd, 0x82, 0xfd, 0x24,
	0x45, 0xf2, 0x28, 0xb1, 0xd3, 0xed, 0xae, 0x7b, 0xd3, 0x8c, 0x7e, 0xff, 0xc9, 0x68, 0xf4, 0x97,
	0x43, 0xa6, 0xb9, 0x50, 0xfb, 0x38, 0x10, 0x0f, 0xf1, 0x56, 0x0b, 0xe5, 0x57, 0xa2, 0xef, 0x90,
	0x29, 0xa9, 0x25, 0x1d, 0x55, 0xb2, 0x13, 0x2f, 0xd7, 0x2a, 0x4e, 0x23, 0xa7, 0x28, 0x05, 0x28,
	0x98, 0xbc, 0x14, 0x69, 0x98, 0xc9, 0x38, 0xd5, 0xc8, 0x54, 0x43, 0x47, 0xcd, 0xb1, 0x6c, 0x26,
	0x95, 0xce, 0xab, 0xbf, 0x5f, 0x4a, 0x39, 0x9a, 0xc5, 0x21, 0x32, 0x6e, 0xe1, 0x76, 0x2e, 0x1e,
	0xb6, 0x92, 0xbb, 0x9f, 0x2a, 0xad, 0xdd, 0xbe, 0xa7, 0xb8, 0x3e, 0xf5, 0x5b, 0x0e, 0x1c, 0x01,
	0xe1, 0xce, 0xa4, 0x65, 0xba, 0xe7, 0xdb, 0x9d, 0x1b, 0xc5, 0x23, 0x39, 0xc7, 0x5f, 0xea, 0x38,
	0x11, 0xb9, 0xe6, 0x49, 0x86, 0xec, 0x59, 0x8c, 0xdc, 0xf4, 0x57, 0x87, 0x8c, 0xd6, 0xc5, 0x89,
	0x96, 0x76, 0x83, 0x02, 0x69, 0xa7, 0x3c, 0x11, 0xac, 0xe1, 0x35, 0x66, 0xc3, 0xc5, 0x04, 0xca,
	0xd3, 0x83, 0xb5, 0x0d, 0x0a, 0x72, 0x65, 0x39, 0xc3, 0x6f, 0x64, 0xae, 0x59, 0xf3, 0x79, 0xde,
	0x70, 0xf4, 0x96, 0x8c, 0xdc, 0xb0, 0xf3, 0xb5, 0x4c, 0x04, 0x6b, 0x59, 0xe1, 0x05, 0x54, 0xaf,
	0x00, 0xee, 0x30, 0x44, 0x71, 0x55, 0x44, 0x97, 0x64, 0x7c, 0x4c, 0xdc, 0xed, 0x85, 0x3a, 0xb0,
	0x76, 0xad, 0x32, 0x67, 0xaa, 0x4a, 0x37, 0x9f, 0x65, 0x2a, 0x58, 0xe7, 0x1f, 0xbb, 0x31, 0x22,
	0xfa, 0x96, 0x74, 0xac, 0x1f, 0x58, 0xd7, 0xaa, 0x2f, 0xe1, 0x4f, 0x93, 0x00, 0x4e, 0xf9, 0x8b,
	0x49, 0x61, 0x95, 0x42, 0x44, 0xe7, 0xa4, 0x17, 0x87, 0xc5, 0x2c, 0x7a, 0x56, 0x4f, 0xc1, 0x19,
	0x08, 0x3e, 0x86, 0xc8, 0x3a, 0x84, 0x02, 0xe9, 0xc7, 0x21, 0x9e, 0xb9, 0xff, 0x57, 0xfc, 0xc8,
	0x60, 0x75, 0x7b, 0xb6, 0xc1, 0x93, 0xd5, 0xed, 0x49, 0xae, 0x49, 0x3b, 0x11, 0x9a, 0x33, 0x62,
	0xd1, 0x17, 0x50, 0x79, 0x57, 0x70, 0x7f, 0xc8, 0xc4, 0x27, 0xa1, 0xb9, 0xbb, 0x50, 0x83, 0x52,
	0x20, 0x2d, 0x9e, 0x86, 0x6c, 0xe8, 0xb5, 0x66, 0xc3, 0xc5, 0xff, 0x67, 0x8a, 0x8a, 0xb7, 0x56,
	0x06, 0xa4, 0x73, 0xd2, 0x94, 0x8a, 0xfd, 0x57, 0x03, 0x6f, 0x4a, 0x63, 0xc7, 0x56, 0x2a, 0x35,
	0x1b, 0xd5, 0xa9, 0x9e, 0x4a, 0x4d, 0x29, 0x69, 0x6f, 0x78, 0xbe, 0x61, 0x63, 0xaf, 0x31, 0x1b,
	0xac, 0xec, 0x7a, 0xfa, 0xb3, 0x4d, 0xc6, 0xd5, 0xd6, 0xe9, 0x0d, 0xe9, 0x61, 0x29, 0x34, 0xfa,
	0xd3, 0xa5, 0x1d, 0x4c, 0x6f, 0xc8, 0x40, 0x89, 0xad, 0xd8, 0xf3, 0x34, 0x10, 0x68, 0x79, 0x06,
	0xa5, 0x17, 0x0d, 0x4b, 0xb3, 0x46, 0xd5, 0x09, 0xa5, 0x0b, 0xd2, 0x2d, 0x9e, 0x35, 0xda, 0x7d,
	0x02, 0xe5, 0x57, 0x0e, 0x2b, 0x1b, 0xa0, 0x0c, 0x49, 0xfa, 0x9a, 0xb4, 0x78, 0x24, 0xd0, 0xd8,
	0xb3, 0xc7, 0xbe, 0x00, 0x70, 0x8b, 0xb9, 0xaf, 0x26, 0x77, 0x1c, 0x72, 0x24, 0xe8, 0x3b, 0x32,
	0x08, 0x94, 0xe0, 0x5a, 0x84, 0xef, 0x35, 0x7a, 0xda, 0x83, 0xb3, 0x6f, 0x00, 0xdc, 0xbb, 0xd8,
	0xf5, 0x7b, 0x94, 0x18, 0xfd, 0x2e, 0x0b, 0x51, 0xdf, 0xad, 0xab, 0x3f, 0x4a, 0xa8, 0x5f, 0x98,
	0xa2, 0x67, 0xaf, 0xed, 0x19, 0x1b, 0x59, 0x57, 0x5c, 0x59, 0x57, 0xf4, 0xeb, 0xf0, 0xc6, 0x16,
	0x7e, 0x61, 0x8b, 0x41, 0xad, 0xfa, 0x65, 0x5f, 0x90, 0x93, 0x2f, 0x3e, 0xbc, 0xf9, 0xf6, 0x2a,
	0x8a, 0xf5, 0x66, 0xf7, 0x03, 0x02, 0x99, 0xf8, 0x8b, 0xeb, 0x5c, 0xc7, 0xd2, 0x8f, 0xe4, 0x55,
	0xb6, 0xe5, 0x87, 0x48, 0xc9, 0x5d, 0x1a, 0xfa, 0x91, 0xca, 0x02, 0x3f, 0x0f, 0x36, 0x22, 0xe1,
	0xd5, 0x7f, 0x9e, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x23, 0x51, 0xb7, 0x16, 0x97, 0x06, 0x00,
	0x00,
}
