// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feedsort/feedsort_.proto

/*
Package feedsort is a generated protocol buffer package.

It is generated from these files:
	feedsort/feedsort_.proto

It has these top-level messages:
	SocialAccountSort
	FeedSort
*/
package feedsort

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import infosort "github.com/21stio/go-playground/grpc/schema/infosort"
import sortkind "github.com/21stio/go-playground/grpc/schema/sortkind"
import servicesort "github.com/21stio/go-playground/grpc/schema/servicesort"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SocialAccountSort struct {
	Info             *infosort.InfoSort        `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	FollowersCount   *sortkind.SortKind        `protobuf:"varint,2,opt,name=followersCount,enum=sortkind.SortKind" json:"followersCount,omitempty"`
	FollowingCount   *sortkind.SortKind        `protobuf:"varint,3,opt,name=followingCount,enum=sortkind.SortKind" json:"followingCount,omitempty"`
	FriendsCount     *sortkind.SortKind        `protobuf:"varint,4,opt,name=friendsCount,enum=sortkind.SortKind" json:"friendsCount,omitempty"`
	Feed             *FeedSort                 `protobuf:"bytes,5,opt,name=feed" json:"feed,omitempty"`
	Meta             *servicesort.TypeMetaSort `protobuf:"bytes,6,opt,name=meta" json:"meta,omitempty"`
	Hash             *string                   `protobuf:"bytes,7,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *SocialAccountSort) Reset()                    { *m = SocialAccountSort{} }
func (m *SocialAccountSort) String() string            { return proto.CompactTextString(m) }
func (*SocialAccountSort) ProtoMessage()               {}
func (*SocialAccountSort) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SocialAccountSort) GetInfo() *infosort.InfoSort {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *SocialAccountSort) GetFollowersCount() sortkind.SortKind {
	if m != nil && m.FollowersCount != nil {
		return *m.FollowersCount
	}
	return sortkind.SortKind_ASC
}

func (m *SocialAccountSort) GetFollowingCount() sortkind.SortKind {
	if m != nil && m.FollowingCount != nil {
		return *m.FollowingCount
	}
	return sortkind.SortKind_ASC
}

func (m *SocialAccountSort) GetFriendsCount() sortkind.SortKind {
	if m != nil && m.FriendsCount != nil {
		return *m.FriendsCount
	}
	return sortkind.SortKind_ASC
}

func (m *SocialAccountSort) GetFeed() *FeedSort {
	if m != nil {
		return m.Feed
	}
	return nil
}

func (m *SocialAccountSort) GetMeta() *servicesort.TypeMetaSort {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *SocialAccountSort) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

type FeedSort struct {
	Info             *infosort.InfoSort        `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	CreatedBy        *SocialAccountSort        `protobuf:"bytes,2,opt,name=createdBy" json:"createdBy,omitempty"`
	Count            *sortkind.SortKind        `protobuf:"varint,3,opt,name=count,enum=sortkind.SortKind" json:"count,omitempty"`
	Meta             *servicesort.TypeMetaSort `protobuf:"bytes,4,opt,name=meta" json:"meta,omitempty"`
	Hash             *string                   `protobuf:"bytes,5,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *FeedSort) Reset()                    { *m = FeedSort{} }
func (m *FeedSort) String() string            { return proto.CompactTextString(m) }
func (*FeedSort) ProtoMessage()               {}
func (*FeedSort) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FeedSort) GetInfo() *infosort.InfoSort {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *FeedSort) GetCreatedBy() *SocialAccountSort {
	if m != nil {
		return m.CreatedBy
	}
	return nil
}

func (m *FeedSort) GetCount() sortkind.SortKind {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return sortkind.SortKind_ASC
}

func (m *FeedSort) GetMeta() *servicesort.TypeMetaSort {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *FeedSort) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*SocialAccountSort)(nil), "feedsort.SocialAccountSort")
	proto.RegisterType((*FeedSort)(nil), "feedsort.FeedSort")
}

func init() { proto.RegisterFile("feedsort/feedsort_.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4b, 0xfb, 0x30,
	0x18, 0xc6, 0xe9, 0xfe, 0xdd, 0xdf, 0x2d, 0x93, 0x81, 0x39, 0xc5, 0x09, 0x32, 0x76, 0x90, 0x5e,
	0x96, 0x62, 0x91, 0x81, 0xde, 0x9c, 0x20, 0x88, 0x78, 0xe9, 0x3c, 0x79, 0x91, 0x9a, 0xa6, 0x6d,
	0xb0, 0xcb, 0x5b, 0xd2, 0x4c, 0xd9, 0x17, 0xf5, 0xe0, 0xa7, 0x91, 0xb4, 0xcd, 0x3a, 0x15, 0x99,
	0xde, 0x9e, 0xe6, 0xfd, 0x3d, 0x7d, 0xf3, 0x3c, 0x2d, 0x22, 0x09, 0xe7, 0x71, 0x09, 0x4a, 0xfb,
	0x56, 0x3c, 0xd2, 0x42, 0x81, 0x06, 0xdc, 0xb3, 0x07, 0x23, 0x22, 0x64, 0x02, 0x15, 0x63, 0x45,
	0xc3, 0x8c, 0x88, 0x79, 0x78, 0x16, 0x32, 0xf6, 0xad, 0xb0, 0x93, 0xe3, 0x92, 0xab, 0x17, 0xc1,
	0x78, 0x65, 0xdb, 0xd2, 0xcd, 0x7c, 0xf2, 0xd6, 0x41, 0x07, 0x0b, 0x60, 0x22, 0xca, 0x2f, 0x19,
	0x83, 0x95, 0xd4, 0x0b, 0x50, 0x1a, 0x9f, 0x20, 0xd7, 0xac, 0x20, 0xce, 0xd8, 0xf1, 0x06, 0x01,
	0xa6, 0x76, 0x1f, 0xbd, 0x91, 0x09, 0x18, 0x22, 0xac, 0xe6, 0xf8, 0x02, 0x0d, 0x13, 0xc8, 0x73,
	0x78, 0xe5, 0xaa, 0xbc, 0x32, 0x6e, 0xd2, 0x19, 0x3b, 0xde, 0x30, 0xc0, 0xd4, 0xde, 0x83, 0x1a,
	0xfa, 0x56, 0xc8, 0x38, 0xfc, 0x42, 0xb6, 0x5e, 0x21, 0xd3, 0xda, 0xfb, 0x6f, 0x97, 0xd7, 0x92,
	0x78, 0x86, 0xf6, 0x13, 0x25, 0xb8, 0x8c, 0x9b, 0xad, 0xee, 0x8f, 0xce, 0x4f, 0x9c, 0xc9, 0x65,
	0xda, 0x24, 0xdd, 0x26, 0x97, 0xad, 0x96, 0x5e, 0x73, 0x1e, 0xd7, 0xb9, 0xcc, 0x11, 0x9e, 0x22,
	0x77, 0xc9, 0x75, 0x44, 0xfe, 0x57, 0xdc, 0x21, 0xdd, 0x2a, 0x8e, 0xde, 0xaf, 0x0b, 0x7e, 0xc7,
	0x75, 0x54, 0xe3, 0x06, 0xc3, 0x18, 0xb9, 0x59, 0x54, 0x66, 0x64, 0x6f, 0xec, 0x78, 0xfd, 0xb0,
	0xd2, 0x93, 0x77, 0x07, 0xf5, 0xec, 0x5b, 0x7f, 0xdd, 0xe7, 0x39, 0xea, 0x33, 0xc5, 0x23, 0xcd,
	0xe3, 0xf9, 0xba, 0xaa, 0x72, 0x10, 0x1c, 0xb5, 0x97, 0xfc, 0xf6, 0x9d, 0xc2, 0x96, 0xc6, 0x1e,
	0xea, 0xb2, 0x1d, 0x2d, 0xd6, 0xc0, 0x26, 0x9c, 0xfb, 0xb7, 0x70, 0xdd, 0x36, 0xdc, 0x7c, 0xf6,
	0x70, 0x96, 0x0a, 0x9d, 0xad, 0x9e, 0x28, 0x83, 0xa5, 0x1f, 0x9c, 0x96, 0x5a, 0x80, 0x9f, 0xc2,
	0xb4, 0xc8, 0xa3, 0x75, 0xaa, 0x60, 0x25, 0x63, 0x3f, 0x55, 0x05, 0xf3, 0x4b, 0x96, 0xf1, 0x65,
	0xb4, 0xf9, 0xa5, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x17, 0xef, 0xc0, 0x69, 0xe6, 0x02, 0x00,
	0x00,
}
