// Code generated by protoc-gen-go. DO NOT EDIT.
// source: whateverunionselect/whateverunionselect_.proto

/*
Package whateverunionselect is a generated protocol buffer package.

It is generated from these files:
	whateverunionselect/whateverunionselect_.proto

It has these top-level messages:
	WhateverUnionSelect
*/
package whateverunionselect

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WhateverUnionSelect struct {
	SelectAll        *bool   `protobuf:"varint,1,opt,name=selectAll" json:"selectAll,omitempty"`
	Kind             *bool   `protobuf:"varint,2,opt,name=kind" json:"kind,omitempty"`
	StringField      *bool   `protobuf:"varint,3,opt,name=stringField" json:"stringField,omitempty"`
	IntField         *bool   `protobuf:"varint,4,opt,name=intField" json:"intField,omitempty"`
	FloatField       *bool   `protobuf:"varint,5,opt,name=floatField" json:"floatField,omitempty"`
	BoolField        *bool   `protobuf:"varint,6,opt,name=boolField" json:"boolField,omitempty"`
	SelectHash       *bool   `protobuf:"varint,7,opt,name=selectHash" json:"selectHash,omitempty"`
	Hash             *string `protobuf:"bytes,8,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WhateverUnionSelect) Reset()                    { *m = WhateverUnionSelect{} }
func (m *WhateverUnionSelect) String() string            { return proto.CompactTextString(m) }
func (*WhateverUnionSelect) ProtoMessage()               {}
func (*WhateverUnionSelect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *WhateverUnionSelect) GetSelectAll() bool {
	if m != nil && m.SelectAll != nil {
		return *m.SelectAll
	}
	return false
}

func (m *WhateverUnionSelect) GetKind() bool {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return false
}

func (m *WhateverUnionSelect) GetStringField() bool {
	if m != nil && m.StringField != nil {
		return *m.StringField
	}
	return false
}

func (m *WhateverUnionSelect) GetIntField() bool {
	if m != nil && m.IntField != nil {
		return *m.IntField
	}
	return false
}

func (m *WhateverUnionSelect) GetFloatField() bool {
	if m != nil && m.FloatField != nil {
		return *m.FloatField
	}
	return false
}

func (m *WhateverUnionSelect) GetBoolField() bool {
	if m != nil && m.BoolField != nil {
		return *m.BoolField
	}
	return false
}

func (m *WhateverUnionSelect) GetSelectHash() bool {
	if m != nil && m.SelectHash != nil {
		return *m.SelectHash
	}
	return false
}

func (m *WhateverUnionSelect) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*WhateverUnionSelect)(nil), "whateverunionselect.WhateverUnionSelect")
}

func init() { proto.RegisterFile("whateverunionselect/whateverunionselect_.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x31, 0x4b, 0x03, 0x31,
	0x14, 0x80, 0x39, 0xad, 0x7a, 0x7d, 0x6e, 0xe9, 0x12, 0x44, 0xe4, 0x70, 0xea, 0xe2, 0x05, 0xfd,
	0x03, 0x52, 0x07, 0x71, 0xae, 0x88, 0xe0, 0x22, 0x69, 0x2e, 0x26, 0xc1, 0x34, 0xef, 0x48, 0x72,
	0x8a, 0xbf, 0xdc, 0xb5, 0x24, 0x29, 0xed, 0x0d, 0xb7, 0xbd, 0x7c, 0x5f, 0x1e, 0x7c, 0x3c, 0x68,
	0x7f, 0x35, 0x8f, 0xf2, 0x47, 0xfa, 0xc1, 0x19, 0x74, 0x41, 0x5a, 0x29, 0x22, 0x9b, 0x60, 0x9f,
	0x6d, 0xef, 0x31, 0x22, 0x59, 0x4c, 0xb8, 0xdb, 0xff, 0x0a, 0x16, 0xef, 0x7b, 0xfe, 0x96, 0xf8,
	0x6b, 0xe6, 0xe4, 0x1a, 0xe6, 0xe5, 0xc7, 0xca, 0x5a, 0x5a, 0x35, 0xd5, 0xb2, 0x5e, 0x1f, 0x01,
	0x21, 0x30, 0xfb, 0x36, 0xae, 0xa3, 0x27, 0x59, 0xe4, 0x99, 0x34, 0x70, 0x19, 0xa2, 0x37, 0x4e,
	0x3d, 0x1b, 0x69, 0x3b, 0x7a, 0x9a, 0xd5, 0x18, 0x91, 0x2b, 0xa8, 0x8d, 0x8b, 0x45, 0xcf, 0xb2,
	0x3e, 0xbc, 0xc9, 0x0d, 0xc0, 0x97, 0x45, 0xbe, 0xb7, 0x67, 0xd9, 0x8e, 0x48, 0xea, 0xd9, 0x20,
	0xda, 0xa2, 0xcf, 0x4b, 0xcf, 0x01, 0xa4, 0xed, 0x12, 0xf7, 0xc2, 0x83, 0xa6, 0x17, 0x65, 0xfb,
	0x48, 0x52, 0xaf, 0x4e, 0xa6, 0x6e, 0xaa, 0xe5, 0x7c, 0x9d, 0xe7, 0xa7, 0xd5, 0xc7, 0xa3, 0x32,
	0x51, 0x0f, 0x9b, 0x56, 0xe0, 0x96, 0x3d, 0xdc, 0x87, 0x68, 0x90, 0x29, 0xbc, 0xeb, 0x2d, 0xff,
	0x53, 0x1e, 0x07, 0xd7, 0x31, 0xe5, 0x7b, 0xc1, 0x82, 0xd0, 0x72, 0xcb, 0xa7, 0x0e, 0xbb, 0x0b,
	0x00, 0x00, 0xff, 0xff, 0x21, 0x39, 0x34, 0xd7, 0x82, 0x01, 0x00, 0x00,
}
