// Code generated by protoc-gen-go. DO NOT EDIT.
// source: whateverunionsselect/whateverunionsselect_.proto

/*
Package whateverunionsselect is a generated protocol buffer package.

It is generated from these files:
	whateverunionsselect/whateverunionsselect_.proto

It has these top-level messages:
	WhateverUnionsSelect
*/
package whateverunionsselect

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import whateverunionfilter "github.com/21stio/go-playground/grpc/schema/whateverunionfilter"
import whateverunionsort "github.com/21stio/go-playground/grpc/schema/whateverunionsort"
import page "github.com/21stio/go-playground/grpc/schema/page"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WhateverUnionsSelect struct {
	Filter           *whateverunionfilter.WhateverUnionFilter `protobuf:"bytes,1,opt,name=filter" json:"filter,omitempty"`
	Sort             *whateverunionsort.WhateverUnionSort     `protobuf:"bytes,2,opt,name=sort" json:"sort,omitempty"`
	Page             *page.Page                               `protobuf:"bytes,3,opt,name=page" json:"page,omitempty"`
	SelectAll        *bool                                    `protobuf:"varint,4,opt,name=selectAll" json:"selectAll,omitempty"`
	Kind             *bool                                    `protobuf:"varint,5,opt,name=kind" json:"kind,omitempty"`
	StringField      *bool                                    `protobuf:"varint,6,opt,name=stringField" json:"stringField,omitempty"`
	IntField         *bool                                    `protobuf:"varint,7,opt,name=intField" json:"intField,omitempty"`
	FloatField       *bool                                    `protobuf:"varint,8,opt,name=floatField" json:"floatField,omitempty"`
	BoolField        *bool                                    `protobuf:"varint,9,opt,name=boolField" json:"boolField,omitempty"`
	SelectHash       *bool                                    `protobuf:"varint,10,opt,name=selectHash" json:"selectHash,omitempty"`
	Hash             *string                                  `protobuf:"bytes,11,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte                                   `json:"-"`
}

func (m *WhateverUnionsSelect) Reset()                    { *m = WhateverUnionsSelect{} }
func (m *WhateverUnionsSelect) String() string            { return proto.CompactTextString(m) }
func (*WhateverUnionsSelect) ProtoMessage()               {}
func (*WhateverUnionsSelect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *WhateverUnionsSelect) GetFilter() *whateverunionfilter.WhateverUnionFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *WhateverUnionsSelect) GetSort() *whateverunionsort.WhateverUnionSort {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *WhateverUnionsSelect) GetPage() *page.Page {
	if m != nil {
		return m.Page
	}
	return nil
}

func (m *WhateverUnionsSelect) GetSelectAll() bool {
	if m != nil && m.SelectAll != nil {
		return *m.SelectAll
	}
	return false
}

func (m *WhateverUnionsSelect) GetKind() bool {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return false
}

func (m *WhateverUnionsSelect) GetStringField() bool {
	if m != nil && m.StringField != nil {
		return *m.StringField
	}
	return false
}

func (m *WhateverUnionsSelect) GetIntField() bool {
	if m != nil && m.IntField != nil {
		return *m.IntField
	}
	return false
}

func (m *WhateverUnionsSelect) GetFloatField() bool {
	if m != nil && m.FloatField != nil {
		return *m.FloatField
	}
	return false
}

func (m *WhateverUnionsSelect) GetBoolField() bool {
	if m != nil && m.BoolField != nil {
		return *m.BoolField
	}
	return false
}

func (m *WhateverUnionsSelect) GetSelectHash() bool {
	if m != nil && m.SelectHash != nil {
		return *m.SelectHash
	}
	return false
}

func (m *WhateverUnionsSelect) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*WhateverUnionsSelect)(nil), "whateverunionsselect.WhateverUnionsSelect")
}

func init() { proto.RegisterFile("whateverunionsselect/whateverunionsselect_.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x86, 0xa9, 0xab, 0x73, 0xcb, 0x2e, 0x12, 0x76, 0x28, 0x45, 0x46, 0x11, 0x0f, 0x45, 0x30,
	0xd1, 0x9d, 0x3c, 0xce, 0x1d, 0x86, 0x47, 0xe9, 0x10, 0xc1, 0x8b, 0x64, 0x5d, 0x96, 0x06, 0xb3,
	0xa6, 0xa4, 0x99, 0xe2, 0xff, 0xf0, 0x07, 0x4b, 0xbe, 0xd4, 0x6d, 0xd5, 0x5e, 0x4a, 0xf2, 0x3c,
	0x79, 0xf3, 0xbd, 0x94, 0xa0, 0xdb, 0xcf, 0x82, 0x59, 0xfe, 0xc1, 0xcd, 0xae, 0x94, 0xba, 0xac,
	0x6b, 0xae, 0x78, 0x6e, 0x69, 0x17, 0x7c, 0x23, 0x95, 0xd1, 0x56, 0xe3, 0x71, 0x97, 0x8c, 0x49,
	0x8b, 0x6e, 0xa4, 0xb2, 0xdc, 0xd0, 0x0e, 0xd6, 0xdc, 0x12, 0x5f, 0xb7, 0x6f, 0xd1, 0xe6, 0xef,
	0x50, 0x6d, 0x7e, 0x27, 0xc6, 0xe7, 0x15, 0x13, 0x9c, 0xba, 0x4f, 0x43, 0x2e, 0xbf, 0x7b, 0x68,
	0xfc, 0xd2, 0x1c, 0x7f, 0x86, 0xe3, 0x4b, 0xa8, 0x81, 0x67, 0xa8, 0xef, 0xe7, 0x44, 0x41, 0x12,
	0xa4, 0xa3, 0x69, 0xda, 0xd5, 0x8b, 0xb4, 0xa2, 0x0b, 0x60, 0x59, 0x93, 0xc3, 0xf7, 0x28, 0x74,
	0xb3, 0xa3, 0x13, 0xc8, 0x5f, 0x91, 0x7f, 0xad, 0xda, 0xe9, 0xa5, 0x36, 0x36, 0x83, 0x04, 0x9e,
	0xa0, 0xd0, 0x75, 0x8c, 0x7a, 0x90, 0x44, 0xc4, 0x6d, 0xc8, 0x13, 0x13, 0x3c, 0x03, 0x8e, 0x2f,
	0xd0, 0xd0, 0xff, 0xac, 0x07, 0xa5, 0xa2, 0x30, 0x09, 0xd2, 0x41, 0x76, 0x00, 0x18, 0xa3, 0xf0,
	0x5d, 0x96, 0xeb, 0xe8, 0x14, 0x04, 0xac, 0x71, 0x82, 0x46, 0xb5, 0x35, 0xb2, 0x14, 0x0b, 0xc9,
	0xd5, 0x3a, 0xea, 0x83, 0x3a, 0x46, 0x38, 0x46, 0x03, 0x59, 0x5a, 0xaf, 0xcf, 0x40, 0xef, 0xf7,
	0x78, 0x82, 0xd0, 0x46, 0x69, 0xd6, 0xd8, 0x01, 0xd8, 0x23, 0xe2, 0xfa, 0xac, 0xb4, 0x56, 0x5e,
	0x0f, 0x7d, 0x9f, 0x3d, 0x70, 0x69, 0x5f, 0xee, 0x91, 0xd5, 0x45, 0x84, 0x7c, 0xfa, 0x40, 0x5c,
	0xdf, 0xc2, 0x99, 0x51, 0x12, 0xa4, 0xc3, 0x0c, 0xd6, 0xf3, 0xf9, 0xeb, 0x4c, 0x48, 0x5b, 0xec,
	0x56, 0x24, 0xd7, 0x5b, 0x3a, 0xbd, 0xab, 0xad, 0xd4, 0x54, 0xe8, 0x9b, 0x4a, 0xb1, 0x2f, 0x61,
	0xf4, 0xae, 0x5c, 0x53, 0x61, 0xaa, 0x9c, 0xd6, 0x79, 0xc1, 0xb7, 0xac, 0xf3, 0x95, 0xfd, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x39, 0x7e, 0x5f, 0xc9, 0x91, 0x02, 0x00, 0x00,
}
