// Code generated by protoc-gen-go. DO NOT EDIT.
// source: personskindfilter/personskindfilter_.proto

/*
Package personskindfilter is a generated protocol buffer package.

It is generated from these files:
	personskindfilter/personskindfilter_.proto

It has these top-level messages:
	PersonsKindFilter
*/
package personskindfilter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import personskind "github.com/21stio/go-playground/grpc/schema/personskind"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PersonsKindFilter struct {
	Is               *personskind.PersonsKind  `protobuf:"varint,1,opt,name=is,enum=personskind.PersonsKind" json:"is,omitempty"`
	Not              *personskind.PersonsKind  `protobuf:"varint,2,opt,name=not,enum=personskind.PersonsKind" json:"not,omitempty"`
	In               []personskind.PersonsKind `protobuf:"varint,3,rep,name=in,enum=personskind.PersonsKind" json:"in,omitempty"`
	NotIn            []personskind.PersonsKind `protobuf:"varint,4,rep,name=notIn,enum=personskind.PersonsKind" json:"notIn,omitempty"`
	Hash             *string                   `protobuf:"bytes,5,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *PersonsKindFilter) Reset()                    { *m = PersonsKindFilter{} }
func (m *PersonsKindFilter) String() string            { return proto.CompactTextString(m) }
func (*PersonsKindFilter) ProtoMessage()               {}
func (*PersonsKindFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PersonsKindFilter) GetIs() personskind.PersonsKind {
	if m != nil && m.Is != nil {
		return *m.Is
	}
	return personskind.PersonsKind_COMPANY_EMPLOYEES
}

func (m *PersonsKindFilter) GetNot() personskind.PersonsKind {
	if m != nil && m.Not != nil {
		return *m.Not
	}
	return personskind.PersonsKind_COMPANY_EMPLOYEES
}

func (m *PersonsKindFilter) GetIn() []personskind.PersonsKind {
	if m != nil {
		return m.In
	}
	return nil
}

func (m *PersonsKindFilter) GetNotIn() []personskind.PersonsKind {
	if m != nil {
		return m.NotIn
	}
	return nil
}

func (m *PersonsKindFilter) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*PersonsKindFilter)(nil), "personskindfilter.PersonsKindFilter")
}

func init() { proto.RegisterFile("personskindfilter/personskindfilter_.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2a, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0x2b, 0xce, 0xce, 0xcc, 0x4b, 0x49, 0xcb, 0xcc, 0x29, 0x49, 0x2d, 0xd2, 0xc7, 0x10,
	0x89, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xc4, 0x90, 0x91, 0x92, 0x43, 0x12, 0x42,
	0xd6, 0x08, 0xd5, 0xa2, 0x74, 0x9d, 0x91, 0x4b, 0x30, 0x00, 0x22, 0xec, 0x9d, 0x99, 0x97, 0xe2,
	0x06, 0xd6, 0x25, 0xa4, 0xc1, 0xc5, 0x94, 0x59, 0x2c, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x67, 0x24,
	0xa1, 0x87, 0xa4, 0x4d, 0x0f, 0x49, 0x6d, 0x10, 0x53, 0x66, 0xb1, 0x90, 0x16, 0x17, 0x73, 0x5e,
	0x7e, 0x89, 0x04, 0x13, 0x01, 0xa5, 0x20, 0x45, 0x60, 0x53, 0xf3, 0x24, 0x98, 0x15, 0x98, 0x09,
	0x98, 0x9a, 0x27, 0xa4, 0xc7, 0xc5, 0x9a, 0x97, 0x5f, 0xe2, 0x99, 0x27, 0xc1, 0x42, 0x40, 0x31,
	0x44, 0x99, 0x90, 0x10, 0x17, 0x4b, 0x46, 0x62, 0x71, 0x86, 0x04, 0xab, 0x02, 0xa3, 0x06, 0x67,
	0x10, 0x98, 0xed, 0x64, 0x1f, 0x65, 0x9b, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f,
	0xab, 0x6f, 0x64, 0x58, 0x5c, 0x92, 0x99, 0xaf, 0x9f, 0x9e, 0xaf, 0x5b, 0x90, 0x93, 0x58, 0x99,
	0x5e, 0x94, 0x5f, 0x9a, 0x97, 0xa2, 0x9f, 0x5e, 0x54, 0x90, 0xac, 0x5f, 0x9c, 0x9c, 0x91, 0x9a,
	0x9b, 0x88, 0x19, 0xa8, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x18, 0x90, 0x9c, 0x7a, 0x01,
	0x00, 0x00,
}
